package com.digicube.fabric.client.model;

import com.digicube.Constants;
import com.digicube.fabric.client.render.DigimonRenderState;
import net.minecraft.client.animation.KeyframeAnimation;

import java.util.HashMap;
import java.util.Map;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * AgumonModel -- GENERATED by the DigiCube model harness from digimon/agumon.py.
 * Geometry matches the Blender rig bone for bone; edit the spec and regenerate rather
 * than hand-tuning coordinates here. setupAnim is a starting point and may be edited.
 *
 * Vanilla model space: Y down, ground at y=24, front at -Z. Atlas 128x64.
 */
public class AgumonModel extends EntityModel<DigimonRenderState> {

    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Constants.id("agumon"), "main");

    private final ModelPart body;
    private final ModelPart head;
    private final ModelPart jaw;
    private final ModelPart leftArm;
    private final ModelPart leftClaw0A;
    private final ModelPart leftClaw0B;
    private final ModelPart leftClaw1A;
    private final ModelPart leftClaw1B;
    private final ModelPart leftClaw2A;
    private final ModelPart leftClaw2B;
    private final ModelPart rightArm;
    private final ModelPart rightClaw0A;
    private final ModelPart rightClaw0B;
    private final ModelPart rightClaw1A;
    private final ModelPart rightClaw1B;
    private final ModelPart rightClaw2A;
    private final ModelPart rightClaw2B;
    private final ModelPart leftLeg;
    private final ModelPart rightLeg;
    private final ModelPart tail;
    private final ModelPart tailTip;

    /** Baked once per model instance; keyed by harness animation name. */
    private final Map<String, KeyframeAnimation> animations = new HashMap<>();

    public AgumonModel(ModelPart root) {
        super(root);
        this.body = root.getChild("body");
        this.head = root.getChild("body").getChild("head");
        this.jaw = root.getChild("body").getChild("head").getChild("jaw");
        this.leftArm = root.getChild("body").getChild("left_arm");
        this.leftClaw0A = root.getChild("body").getChild("left_arm").getChild("left_claw0_a");
        this.leftClaw0B = root.getChild("body").getChild("left_arm").getChild("left_claw0_b");
        this.leftClaw1A = root.getChild("body").getChild("left_arm").getChild("left_claw1_a");
        this.leftClaw1B = root.getChild("body").getChild("left_arm").getChild("left_claw1_b");
        this.leftClaw2A = root.getChild("body").getChild("left_arm").getChild("left_claw2_a");
        this.leftClaw2B = root.getChild("body").getChild("left_arm").getChild("left_claw2_b");
        this.rightArm = root.getChild("body").getChild("right_arm");
        this.rightClaw0A = root.getChild("body").getChild("right_arm").getChild("right_claw0_a");
        this.rightClaw0B = root.getChild("body").getChild("right_arm").getChild("right_claw0_b");
        this.rightClaw1A = root.getChild("body").getChild("right_arm").getChild("right_claw1_a");
        this.rightClaw1B = root.getChild("body").getChild("right_arm").getChild("right_claw1_b");
        this.rightClaw2A = root.getChild("body").getChild("right_arm").getChild("right_claw2_a");
        this.rightClaw2B = root.getChild("body").getChild("right_arm").getChild("right_claw2_b");
        this.leftLeg = root.getChild("left_leg");
        this.rightLeg = root.getChild("right_leg");
        this.tail = root.getChild("body").getChild("tail");
        this.tailTip = root.getChild("body").getChild("tail").getChild("tail_tip");
        AgumonAnimations.BY_NAME.forEach((name, definition) -> this.animations.put(name, definition.bake(root)));
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                        .texOffs(44, 0).addBox(-5.0F, -9.0F, -4.0F, 10.0F, 9.0F, 8.0F)   // body
                , PartPose.offsetAndRotation(0.0F, 15.0F, 0.0F, rad(8.0F), rad(0.0F), rad(0.0F)));

        PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(-6.0F, -10.0F, -4.0F, 12.0F, 10.0F, 10.0F)   // head
                        .texOffs(0, 20).addBox(-5.0F, -5.0F, -11.0F, 10.0F, 4.0F, 7.0F)   // snout
                , PartPose.offsetAndRotation(0.0F, -9.0F, -1.0F, rad(-8.0F), rad(0.0F), rad(0.0F)));

        head.addOrReplaceChild("jaw", CubeListBuilder.create()
                        .texOffs(86, 20).addBox(-5.0F, 0.0F, -7.0F, 10.0F, 2.0F, 7.0F)   // jaw
                , PartPose.offset(0.0F, -1.0F, -4.0F));

        PartDefinition leftArm = body.addOrReplaceChild("left_arm", CubeListBuilder.create()
                        .texOffs(0, 31).addBox(0.0F, 0.0F, -1.5F, 3.0F, 6.0F, 3.0F)   // left_arm
                        .texOffs(12, 31).addBox(-1.0F, 6.0F, -2.0F, 5.0F, 3.0F, 4.0F)   // left_hand
                , PartPose.offsetAndRotation(5.0F, -7.5F, -1.0F, rad(-25.0F), rad(0.0F), rad(-10.0F)));

        leftArm.addOrReplaceChild("left_claw0_a", CubeListBuilder.create()
                        .texOffs(50, 31).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F)   // left_claw0_a
                , PartPose.offsetAndRotation(-0.5F, 9.0F, 0.0F, rad(0.0F), rad(-45.0F), rad(0.0F)));

        leftArm.addOrReplaceChild("left_claw0_b", CubeListBuilder.create()
                        .texOffs(50, 31).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F)   // left_claw0_b
                , PartPose.offsetAndRotation(-0.5F, 9.0F, 0.0F, rad(0.0F), rad(45.0F), rad(0.0F)));

        leftArm.addOrReplaceChild("left_claw1_a", CubeListBuilder.create()
                        .texOffs(50, 31).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F)   // left_claw1_a
                , PartPose.offsetAndRotation(1.5F, 9.0F, 0.0F, rad(0.0F), rad(-45.0F), rad(0.0F)));

        leftArm.addOrReplaceChild("left_claw1_b", CubeListBuilder.create()
                        .texOffs(50, 31).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F)   // left_claw1_b
                , PartPose.offsetAndRotation(1.5F, 9.0F, 0.0F, rad(0.0F), rad(45.0F), rad(0.0F)));

        leftArm.addOrReplaceChild("left_claw2_a", CubeListBuilder.create()
                        .texOffs(50, 31).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F)   // left_claw2_a
                , PartPose.offsetAndRotation(3.5F, 9.0F, 0.0F, rad(0.0F), rad(-45.0F), rad(0.0F)));

        leftArm.addOrReplaceChild("left_claw2_b", CubeListBuilder.create()
                        .texOffs(50, 31).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F)   // left_claw2_b
                , PartPose.offsetAndRotation(3.5F, 9.0F, 0.0F, rad(0.0F), rad(45.0F), rad(0.0F)));

        PartDefinition rightArm = body.addOrReplaceChild("right_arm", CubeListBuilder.create().mirror()
                        .texOffs(0, 31).addBox(-3.0F, 0.0F, -1.5F, 3.0F, 6.0F, 3.0F)   // right_arm
                        .texOffs(12, 31).addBox(-4.0F, 6.0F, -2.0F, 5.0F, 3.0F, 4.0F)   // right_hand
                , PartPose.offsetAndRotation(-5.0F, -7.5F, -1.0F, rad(-25.0F), rad(0.0F), rad(10.0F)));

        rightArm.addOrReplaceChild("right_claw0_a", CubeListBuilder.create()
                        .texOffs(50, 31).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F)   // right_claw0_a
                , PartPose.offsetAndRotation(0.5F, 9.0F, 0.0F, rad(0.0F), rad(-45.0F), rad(0.0F)));

        rightArm.addOrReplaceChild("right_claw0_b", CubeListBuilder.create()
                        .texOffs(50, 31).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F)   // right_claw0_b
                , PartPose.offsetAndRotation(0.5F, 9.0F, 0.0F, rad(0.0F), rad(45.0F), rad(0.0F)));

        rightArm.addOrReplaceChild("right_claw1_a", CubeListBuilder.create()
                        .texOffs(50, 31).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F)   // right_claw1_a
                , PartPose.offsetAndRotation(-1.5F, 9.0F, 0.0F, rad(0.0F), rad(-45.0F), rad(0.0F)));

        rightArm.addOrReplaceChild("right_claw1_b", CubeListBuilder.create()
                        .texOffs(50, 31).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F)   // right_claw1_b
                , PartPose.offsetAndRotation(-1.5F, 9.0F, 0.0F, rad(0.0F), rad(45.0F), rad(0.0F)));

        rightArm.addOrReplaceChild("right_claw2_a", CubeListBuilder.create()
                        .texOffs(50, 31).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F)   // right_claw2_a
                , PartPose.offsetAndRotation(-3.5F, 9.0F, 0.0F, rad(0.0F), rad(-45.0F), rad(0.0F)));

        rightArm.addOrReplaceChild("right_claw2_b", CubeListBuilder.create()
                        .texOffs(50, 31).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F)   // right_claw2_b
                , PartPose.offsetAndRotation(-3.5F, 9.0F, 0.0F, rad(0.0F), rad(45.0F), rad(0.0F)));

        PartDefinition tail = body.addOrReplaceChild("tail", CubeListBuilder.create()
                        .texOffs(66, 20).addBox(-2.0F, -2.0F, -1.0F, 4.0F, 4.0F, 6.0F)   // tail
                , PartPose.offsetAndRotation(0.0F, -2.0F, 4.0F, rad(-25.0F), rad(0.0F), rad(0.0F)));

        tail.addOrReplaceChild("tail_tip", CubeListBuilder.create()
                        .texOffs(30, 31).addBox(-1.5F, -1.5F, 0.0F, 3.0F, 3.0F, 4.0F)   // tail_tip
                , PartPose.offsetAndRotation(0.0F, 0.0F, 5.0F, rad(-20.0F), rad(0.0F), rad(0.0F)));

        root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                        .texOffs(80, 0).addBox(-2.5F, 0.0F, -2.5F, 5.0F, 7.0F, 5.0F)   // left_leg
                        .texOffs(34, 20).addBox(-4.0F, 7.0F, -6.0F, 8.0F, 3.0F, 8.0F)   // left_foot
                        .texOffs(44, 31).addBox(-3.0F, 8.0F, -9.0F, 0.0F, 2.0F, 3.0F)   // left_toe0
                        .addBox(0.0F, 8.0F, -9.0F, 0.0F, 2.0F, 3.0F)   // left_toe1
                        .addBox(3.0F, 8.0F, -9.0F, 0.0F, 2.0F, 3.0F)   // left_toe2
                , PartPose.offset(3.5F, 14.0F, 0.0F));

        root.addOrReplaceChild("right_leg", CubeListBuilder.create().mirror()
                        .texOffs(80, 0).addBox(-2.5F, 0.0F, -2.5F, 5.0F, 7.0F, 5.0F)   // right_leg
                        .texOffs(34, 20).addBox(-4.0F, 7.0F, -6.0F, 8.0F, 3.0F, 8.0F)   // right_foot
                        .texOffs(44, 31).addBox(3.0F, 8.0F, -9.0F, 0.0F, 2.0F, 3.0F)   // right_toe0
                        .addBox(0.0F, 8.0F, -9.0F, 0.0F, 2.0F, 3.0F)   // right_toe1
                        .addBox(-3.0F, 8.0F, -9.0F, 0.0F, 2.0F, 3.0F)   // right_toe2
                , PartPose.offset(-3.5F, 14.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    @Override
    public void setupAnim(DigimonRenderState state) {
        super.setupAnim(state);   // restores the rest pose; everything below is a delta

        this.head.yRot += state.yRot * Mth.DEG_TO_RAD;
        this.head.xRot += state.xRot * Mth.DEG_TO_RAD;

        float stride = Mth.cos(state.walkAnimationPos * 0.6662F) * state.walkAnimationSpeed;
        this.rightLeg.xRot += stride;
        this.leftLeg.xRot -= stride;
        this.leftArm.xRot += stride * 0.6F;
        this.rightArm.xRot -= stride * 0.6F;

        float sway = Mth.cos(state.ageInTicks * 0.09F) * 0.04F;
        this.leftArm.zRot -= sway;
        this.rightArm.zRot += sway;
        this.tail.yRot += Mth.sin(state.ageInTicks * 0.1F) * 0.12F
                + Mth.cos(state.walkAnimationPos * 0.6662F) * 0.25F * state.walkAnimationSpeed;

        // Attack keyframes (see AgumonAnimations) layer on top of the idle/walk pose.
        KeyframeAnimation attack = state.attackAnimationName == null ? null : this.animations.get(state.attackAnimationName);
        if (attack != null) {
            attack.apply(state.attackAnimation, state.ageInTicks);
        }
    }

    private static float rad(float degrees) {
        return degrees * Mth.DEG_TO_RAD;
    }
}
