package com.digicube.fabric.client.model;

import com.digicube.Constants;
import com.digicube.fabric.client.render.BlueBlasterRenderState;
import net.minecraft.client.animation.KeyframeAnimation;

import java.util.HashMap;
import java.util.Map;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * BlueBlasterModel -- GENERATED by the DigiCube model harness from digimon/blue_blaster.py.
 * Geometry matches the Blender rig bone for bone; edit the spec and regenerate rather
 * than hand-tuning coordinates here. setupAnim is a starting point and may be edited.
 *
 * Vanilla model space: Y down, ground at y=24, front at -Z. Atlas 512x256.
 */
public class BlueBlasterModel extends EntityModel<BlueBlasterRenderState> {

    /** Client model layer used when baking this species. */
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Constants.id("blue_blaster"), "main");

    private final ModelPart eddy0;
    private final ModelPart eddy0Sheet0;
    private final ModelPart eddy0Sheet1;
    private final ModelPart eddy0Sheet2;
    private final ModelPart eddy1;
    private final ModelPart eddy1Sheet0;
    private final ModelPart eddy1Sheet1;
    private final ModelPart eddy1Sheet2;
    private final ModelPart eddy2;
    private final ModelPart eddy2Sheet0;
    private final ModelPart eddy2Sheet1;
    private final ModelPart eddy2Sheet2;
    private final ModelPart eddy3;
    private final ModelPart eddy3Sheet0;
    private final ModelPart eddy3Sheet1;
    private final ModelPart eddy3Sheet2;
    private final ModelPart eddy4;
    private final ModelPart eddy4Sheet0;
    private final ModelPart eddy4Sheet1;
    private final ModelPart eddy4Sheet2;
    private final ModelPart eddy5;
    private final ModelPart eddy5Sheet0;
    private final ModelPart eddy5Sheet1;
    private final ModelPart eddy5Sheet2;
    private final ModelPart eddy6;
    private final ModelPart eddy6Sheet0;
    private final ModelPart eddy6Sheet1;
    private final ModelPart eddy6Sheet2;
    private final ModelPart eddy7;
    private final ModelPart eddy7Sheet0;
    private final ModelPart eddy7Sheet1;
    private final ModelPart eddy7Sheet2;
    private final ModelPart eddy8;
    private final ModelPart eddy8Sheet0;
    private final ModelPart eddy8Sheet1;
    private final ModelPart eddy8Sheet2;
    private final ModelPart eddy9;
    private final ModelPart eddy9Sheet0;
    private final ModelPart eddy9Sheet1;
    private final ModelPart eddy9Sheet2;
    private final ModelPart eddy10;
    private final ModelPart eddy10Sheet0;
    private final ModelPart eddy10Sheet1;
    private final ModelPart eddy10Sheet2;
    private final ModelPart eddy11;
    private final ModelPart eddy11Sheet0;
    private final ModelPart eddy11Sheet1;
    private final ModelPart eddy11Sheet2;
    private final ModelPart eddy12;
    private final ModelPart eddy12Sheet0;
    private final ModelPart eddy12Sheet1;
    private final ModelPart eddy12Sheet2;
    private final ModelPart eddy13;
    private final ModelPart eddy13Sheet0;
    private final ModelPart eddy13Sheet1;
    private final ModelPart eddy13Sheet2;
    private final ModelPart eddy14;
    private final ModelPart eddy14Sheet0;
    private final ModelPart eddy14Sheet1;
    private final ModelPart eddy14Sheet2;
    private final ModelPart eddy15;
    private final ModelPart eddy15Sheet0;
    private final ModelPart eddy15Sheet1;
    private final ModelPart eddy15Sheet2;
    private final ModelPart throat0;
    private final ModelPart throat1;
    private final ModelPart throat2;

    /** Baked once per model instance; keyed by harness animation name. */
    private final Map<String, KeyframeAnimation> animations = new HashMap<>();

    /**
     * Creates the model and binds its animation bones.
     * @param root baked root from this model's layer
     */
    public BlueBlasterModel(ModelPart root) {
        super(root);
        this.eddy0 = root.getChild("eddy0");
        this.eddy0Sheet0 = root.getChild("eddy0").getChild("eddy0_sheet0");
        this.eddy0Sheet1 = root.getChild("eddy0").getChild("eddy0_sheet1");
        this.eddy0Sheet2 = root.getChild("eddy0").getChild("eddy0_sheet2");
        this.eddy1 = root.getChild("eddy1");
        this.eddy1Sheet0 = root.getChild("eddy1").getChild("eddy1_sheet0");
        this.eddy1Sheet1 = root.getChild("eddy1").getChild("eddy1_sheet1");
        this.eddy1Sheet2 = root.getChild("eddy1").getChild("eddy1_sheet2");
        this.eddy2 = root.getChild("eddy2");
        this.eddy2Sheet0 = root.getChild("eddy2").getChild("eddy2_sheet0");
        this.eddy2Sheet1 = root.getChild("eddy2").getChild("eddy2_sheet1");
        this.eddy2Sheet2 = root.getChild("eddy2").getChild("eddy2_sheet2");
        this.eddy3 = root.getChild("eddy3");
        this.eddy3Sheet0 = root.getChild("eddy3").getChild("eddy3_sheet0");
        this.eddy3Sheet1 = root.getChild("eddy3").getChild("eddy3_sheet1");
        this.eddy3Sheet2 = root.getChild("eddy3").getChild("eddy3_sheet2");
        this.eddy4 = root.getChild("eddy4");
        this.eddy4Sheet0 = root.getChild("eddy4").getChild("eddy4_sheet0");
        this.eddy4Sheet1 = root.getChild("eddy4").getChild("eddy4_sheet1");
        this.eddy4Sheet2 = root.getChild("eddy4").getChild("eddy4_sheet2");
        this.eddy5 = root.getChild("eddy5");
        this.eddy5Sheet0 = root.getChild("eddy5").getChild("eddy5_sheet0");
        this.eddy5Sheet1 = root.getChild("eddy5").getChild("eddy5_sheet1");
        this.eddy5Sheet2 = root.getChild("eddy5").getChild("eddy5_sheet2");
        this.eddy6 = root.getChild("eddy6");
        this.eddy6Sheet0 = root.getChild("eddy6").getChild("eddy6_sheet0");
        this.eddy6Sheet1 = root.getChild("eddy6").getChild("eddy6_sheet1");
        this.eddy6Sheet2 = root.getChild("eddy6").getChild("eddy6_sheet2");
        this.eddy7 = root.getChild("eddy7");
        this.eddy7Sheet0 = root.getChild("eddy7").getChild("eddy7_sheet0");
        this.eddy7Sheet1 = root.getChild("eddy7").getChild("eddy7_sheet1");
        this.eddy7Sheet2 = root.getChild("eddy7").getChild("eddy7_sheet2");
        this.eddy8 = root.getChild("eddy8");
        this.eddy8Sheet0 = root.getChild("eddy8").getChild("eddy8_sheet0");
        this.eddy8Sheet1 = root.getChild("eddy8").getChild("eddy8_sheet1");
        this.eddy8Sheet2 = root.getChild("eddy8").getChild("eddy8_sheet2");
        this.eddy9 = root.getChild("eddy9");
        this.eddy9Sheet0 = root.getChild("eddy9").getChild("eddy9_sheet0");
        this.eddy9Sheet1 = root.getChild("eddy9").getChild("eddy9_sheet1");
        this.eddy9Sheet2 = root.getChild("eddy9").getChild("eddy9_sheet2");
        this.eddy10 = root.getChild("eddy10");
        this.eddy10Sheet0 = root.getChild("eddy10").getChild("eddy10_sheet0");
        this.eddy10Sheet1 = root.getChild("eddy10").getChild("eddy10_sheet1");
        this.eddy10Sheet2 = root.getChild("eddy10").getChild("eddy10_sheet2");
        this.eddy11 = root.getChild("eddy11");
        this.eddy11Sheet0 = root.getChild("eddy11").getChild("eddy11_sheet0");
        this.eddy11Sheet1 = root.getChild("eddy11").getChild("eddy11_sheet1");
        this.eddy11Sheet2 = root.getChild("eddy11").getChild("eddy11_sheet2");
        this.eddy12 = root.getChild("eddy12");
        this.eddy12Sheet0 = root.getChild("eddy12").getChild("eddy12_sheet0");
        this.eddy12Sheet1 = root.getChild("eddy12").getChild("eddy12_sheet1");
        this.eddy12Sheet2 = root.getChild("eddy12").getChild("eddy12_sheet2");
        this.eddy13 = root.getChild("eddy13");
        this.eddy13Sheet0 = root.getChild("eddy13").getChild("eddy13_sheet0");
        this.eddy13Sheet1 = root.getChild("eddy13").getChild("eddy13_sheet1");
        this.eddy13Sheet2 = root.getChild("eddy13").getChild("eddy13_sheet2");
        this.eddy14 = root.getChild("eddy14");
        this.eddy14Sheet0 = root.getChild("eddy14").getChild("eddy14_sheet0");
        this.eddy14Sheet1 = root.getChild("eddy14").getChild("eddy14_sheet1");
        this.eddy14Sheet2 = root.getChild("eddy14").getChild("eddy14_sheet2");
        this.eddy15 = root.getChild("eddy15");
        this.eddy15Sheet0 = root.getChild("eddy15").getChild("eddy15_sheet0");
        this.eddy15Sheet1 = root.getChild("eddy15").getChild("eddy15_sheet1");
        this.eddy15Sheet2 = root.getChild("eddy15").getChild("eddy15_sheet2");
        this.throat0 = root.getChild("throat0");
        this.throat1 = root.getChild("throat1");
        this.throat2 = root.getChild("throat2");
        BlueBlasterAnimations.BY_NAME.forEach((name, definition) -> this.animations.put(name, definition.bake(root)));
    }

    /**
     * Builds the authored geometry and texture layout.
     * @return the layer to register with the client
     */
    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

        PartDefinition eddy0 = root.addOrReplaceChild("eddy0", CubeListBuilder.create()
                        .texOffs(176, 0).addBox(-10.0F, -10.0F, -12.0F, 20.0F, 20.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // eddy0_billow
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        eddy0.addOrReplaceChild("eddy0_sheet0", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy0_sheet0
                , PartPose.offset(0.0F, 0.0F, 0.0F));

        eddy0.addOrReplaceChild("eddy0_sheet1", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy0_sheet1
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(60.0F)));

        eddy0.addOrReplaceChild("eddy0_sheet2", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy0_sheet2
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(120.0F)));

        PartDefinition eddy1 = root.addOrReplaceChild("eddy1", CubeListBuilder.create()
                        .texOffs(216, 0).addBox(-10.0F, -10.0F, -12.0F, 20.0F, 20.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // eddy1_billow
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        eddy1.addOrReplaceChild("eddy1_sheet0", CubeListBuilder.create()
                        .texOffs(48, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy1_sheet0
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(17.0F)));

        eddy1.addOrReplaceChild("eddy1_sheet1", CubeListBuilder.create()
                        .texOffs(48, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy1_sheet1
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(77.0F)));

        eddy1.addOrReplaceChild("eddy1_sheet2", CubeListBuilder.create()
                        .texOffs(48, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy1_sheet2
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(137.0F)));

        PartDefinition eddy2 = root.addOrReplaceChild("eddy2", CubeListBuilder.create()
                        .texOffs(256, 0).addBox(-10.0F, -10.0F, -12.0F, 20.0F, 20.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // eddy2_billow
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        eddy2.addOrReplaceChild("eddy2_sheet0", CubeListBuilder.create()
                        .texOffs(96, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy2_sheet0
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(34.0F)));

        eddy2.addOrReplaceChild("eddy2_sheet1", CubeListBuilder.create()
                        .texOffs(96, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy2_sheet1
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(94.0F)));

        eddy2.addOrReplaceChild("eddy2_sheet2", CubeListBuilder.create()
                        .texOffs(96, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy2_sheet2
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(154.0F)));

        PartDefinition eddy3 = root.addOrReplaceChild("eddy3", CubeListBuilder.create()
                        .texOffs(176, 0).addBox(-10.0F, -10.0F, -12.0F, 20.0F, 20.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // eddy3_billow
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        eddy3.addOrReplaceChild("eddy3_sheet0", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy3_sheet0
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(51.0F)));

        eddy3.addOrReplaceChild("eddy3_sheet1", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy3_sheet1
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(111.0F)));

        eddy3.addOrReplaceChild("eddy3_sheet2", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy3_sheet2
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(171.0F)));

        PartDefinition eddy4 = root.addOrReplaceChild("eddy4", CubeListBuilder.create()
                        .texOffs(216, 0).addBox(-10.0F, -10.0F, -12.0F, 20.0F, 20.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // eddy4_billow
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        eddy4.addOrReplaceChild("eddy4_sheet0", CubeListBuilder.create()
                        .texOffs(48, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy4_sheet0
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(68.0F)));

        eddy4.addOrReplaceChild("eddy4_sheet1", CubeListBuilder.create()
                        .texOffs(48, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy4_sheet1
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(128.0F)));

        eddy4.addOrReplaceChild("eddy4_sheet2", CubeListBuilder.create()
                        .texOffs(48, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy4_sheet2
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(188.0F)));

        PartDefinition eddy5 = root.addOrReplaceChild("eddy5", CubeListBuilder.create()
                        .texOffs(256, 0).addBox(-10.0F, -10.0F, -12.0F, 20.0F, 20.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // eddy5_billow
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        eddy5.addOrReplaceChild("eddy5_sheet0", CubeListBuilder.create()
                        .texOffs(96, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy5_sheet0
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(85.0F)));

        eddy5.addOrReplaceChild("eddy5_sheet1", CubeListBuilder.create()
                        .texOffs(96, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy5_sheet1
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(145.0F)));

        eddy5.addOrReplaceChild("eddy5_sheet2", CubeListBuilder.create()
                        .texOffs(96, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy5_sheet2
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(205.0F)));

        PartDefinition eddy6 = root.addOrReplaceChild("eddy6", CubeListBuilder.create()
                        .texOffs(176, 0).addBox(-10.0F, -10.0F, -12.0F, 20.0F, 20.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // eddy6_billow
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        eddy6.addOrReplaceChild("eddy6_sheet0", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy6_sheet0
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(102.0F)));

        eddy6.addOrReplaceChild("eddy6_sheet1", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy6_sheet1
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(162.0F)));

        eddy6.addOrReplaceChild("eddy6_sheet2", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy6_sheet2
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(222.0F)));

        PartDefinition eddy7 = root.addOrReplaceChild("eddy7", CubeListBuilder.create()
                        .texOffs(216, 0).addBox(-10.0F, -10.0F, -12.0F, 20.0F, 20.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // eddy7_billow
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        eddy7.addOrReplaceChild("eddy7_sheet0", CubeListBuilder.create()
                        .texOffs(48, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy7_sheet0
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(119.0F)));

        eddy7.addOrReplaceChild("eddy7_sheet1", CubeListBuilder.create()
                        .texOffs(48, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy7_sheet1
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(179.0F)));

        eddy7.addOrReplaceChild("eddy7_sheet2", CubeListBuilder.create()
                        .texOffs(48, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy7_sheet2
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(239.0F)));

        PartDefinition eddy8 = root.addOrReplaceChild("eddy8", CubeListBuilder.create()
                        .texOffs(256, 0).addBox(-10.0F, -10.0F, -12.0F, 20.0F, 20.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // eddy8_billow
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        eddy8.addOrReplaceChild("eddy8_sheet0", CubeListBuilder.create()
                        .texOffs(96, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy8_sheet0
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(136.0F)));

        eddy8.addOrReplaceChild("eddy8_sheet1", CubeListBuilder.create()
                        .texOffs(96, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy8_sheet1
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(196.0F)));

        eddy8.addOrReplaceChild("eddy8_sheet2", CubeListBuilder.create()
                        .texOffs(96, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy8_sheet2
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(256.0F)));

        PartDefinition eddy9 = root.addOrReplaceChild("eddy9", CubeListBuilder.create()
                        .texOffs(176, 0).addBox(-10.0F, -10.0F, -12.0F, 20.0F, 20.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // eddy9_billow
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        eddy9.addOrReplaceChild("eddy9_sheet0", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy9_sheet0
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(153.0F)));

        eddy9.addOrReplaceChild("eddy9_sheet1", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy9_sheet1
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(213.0F)));

        eddy9.addOrReplaceChild("eddy9_sheet2", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy9_sheet2
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(273.0F)));

        PartDefinition eddy10 = root.addOrReplaceChild("eddy10", CubeListBuilder.create()
                        .texOffs(216, 0).addBox(-10.0F, -10.0F, -12.0F, 20.0F, 20.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // eddy10_billow
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        eddy10.addOrReplaceChild("eddy10_sheet0", CubeListBuilder.create()
                        .texOffs(48, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy10_sheet0
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(170.0F)));

        eddy10.addOrReplaceChild("eddy10_sheet1", CubeListBuilder.create()
                        .texOffs(48, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy10_sheet1
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(230.0F)));

        eddy10.addOrReplaceChild("eddy10_sheet2", CubeListBuilder.create()
                        .texOffs(48, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy10_sheet2
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(290.0F)));

        PartDefinition eddy11 = root.addOrReplaceChild("eddy11", CubeListBuilder.create()
                        .texOffs(256, 0).addBox(-10.0F, -10.0F, -12.0F, 20.0F, 20.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // eddy11_billow
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        eddy11.addOrReplaceChild("eddy11_sheet0", CubeListBuilder.create()
                        .texOffs(96, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy11_sheet0
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(187.0F)));

        eddy11.addOrReplaceChild("eddy11_sheet1", CubeListBuilder.create()
                        .texOffs(96, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy11_sheet1
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(247.0F)));

        eddy11.addOrReplaceChild("eddy11_sheet2", CubeListBuilder.create()
                        .texOffs(96, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy11_sheet2
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(307.0F)));

        PartDefinition eddy12 = root.addOrReplaceChild("eddy12", CubeListBuilder.create()
                        .texOffs(176, 0).addBox(-10.0F, -10.0F, -12.0F, 20.0F, 20.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // eddy12_billow
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        eddy12.addOrReplaceChild("eddy12_sheet0", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy12_sheet0
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(204.0F)));

        eddy12.addOrReplaceChild("eddy12_sheet1", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy12_sheet1
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(264.0F)));

        eddy12.addOrReplaceChild("eddy12_sheet2", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy12_sheet2
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(324.0F)));

        PartDefinition eddy13 = root.addOrReplaceChild("eddy13", CubeListBuilder.create()
                        .texOffs(216, 0).addBox(-10.0F, -10.0F, -12.0F, 20.0F, 20.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // eddy13_billow
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        eddy13.addOrReplaceChild("eddy13_sheet0", CubeListBuilder.create()
                        .texOffs(48, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy13_sheet0
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(221.0F)));

        eddy13.addOrReplaceChild("eddy13_sheet1", CubeListBuilder.create()
                        .texOffs(48, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy13_sheet1
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(281.0F)));

        eddy13.addOrReplaceChild("eddy13_sheet2", CubeListBuilder.create()
                        .texOffs(48, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy13_sheet2
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(341.0F)));

        PartDefinition eddy14 = root.addOrReplaceChild("eddy14", CubeListBuilder.create()
                        .texOffs(256, 0).addBox(-10.0F, -10.0F, -12.0F, 20.0F, 20.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // eddy14_billow
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        eddy14.addOrReplaceChild("eddy14_sheet0", CubeListBuilder.create()
                        .texOffs(96, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy14_sheet0
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(238.0F)));

        eddy14.addOrReplaceChild("eddy14_sheet1", CubeListBuilder.create()
                        .texOffs(96, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy14_sheet1
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(298.0F)));

        eddy14.addOrReplaceChild("eddy14_sheet2", CubeListBuilder.create()
                        .texOffs(96, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy14_sheet2
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(358.0F)));

        PartDefinition eddy15 = root.addOrReplaceChild("eddy15", CubeListBuilder.create()
                        .texOffs(176, 0).addBox(-10.0F, -10.0F, -12.0F, 20.0F, 20.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // eddy15_billow
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        eddy15.addOrReplaceChild("eddy15_sheet0", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy15_sheet0
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(255.0F)));

        eddy15.addOrReplaceChild("eddy15_sheet1", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy15_sheet1
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(315.0F)));

        eddy15.addOrReplaceChild("eddy15_sheet2", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(0.0F, -10.0F, -24.0F, 0.0F, 20.0F, 24.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // eddy15_sheet2
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(0.0F), rad(375.0F)));

        root.addOrReplaceChild("throat0", CubeListBuilder.create()
                        .texOffs(144, 0).addBox(0.0F, -4.0F, -16.0F, 0.0F, 8.0F, 16.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // throat0
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        root.addOrReplaceChild("throat1", CubeListBuilder.create()
                        .texOffs(144, 0).addBox(0.0F, -4.0F, -16.0F, 0.0F, 8.0F, 16.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // throat1
                , PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, rad(0.0F), rad(0.0F), rad(60.0F)));

        root.addOrReplaceChild("throat2", CubeListBuilder.create()
                        .texOffs(144, 0).addBox(0.0F, -4.0F, -16.0F, 0.0F, 8.0F, 16.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // throat2
                , PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, rad(0.0F), rad(0.0F), rad(120.0F)));
        return LayerDefinition.create(mesh, 512, 256);
    }

    @Override
    public void setupAnim(BlueBlasterRenderState state) {
        super.setupAnim(state);
        this.animations.get("flow").apply((long) (state.ageInTicks * 50.0F), 1.0F);
        this.eddy0.visible = -this.eddy0.z + 0.024F < state.length * 16.0F;
        this.eddy0.zScale = Math.min(this.eddy0.zScale, Math.max(0.001F, (state.length * 16.0F + this.eddy0.z) / 24.0F));
        this.eddy1.visible = -this.eddy1.z + 0.024F < state.length * 16.0F;
        this.eddy1.zScale = Math.min(this.eddy1.zScale, Math.max(0.001F, (state.length * 16.0F + this.eddy1.z) / 24.0F));
        this.eddy2.visible = -this.eddy2.z + 0.024F < state.length * 16.0F;
        this.eddy2.zScale = Math.min(this.eddy2.zScale, Math.max(0.001F, (state.length * 16.0F + this.eddy2.z) / 24.0F));
        this.eddy3.visible = -this.eddy3.z + 0.024F < state.length * 16.0F;
        this.eddy3.zScale = Math.min(this.eddy3.zScale, Math.max(0.001F, (state.length * 16.0F + this.eddy3.z) / 24.0F));
        this.eddy4.visible = -this.eddy4.z + 0.024F < state.length * 16.0F;
        this.eddy4.zScale = Math.min(this.eddy4.zScale, Math.max(0.001F, (state.length * 16.0F + this.eddy4.z) / 24.0F));
        this.eddy5.visible = -this.eddy5.z + 0.024F < state.length * 16.0F;
        this.eddy5.zScale = Math.min(this.eddy5.zScale, Math.max(0.001F, (state.length * 16.0F + this.eddy5.z) / 24.0F));
        this.eddy6.visible = -this.eddy6.z + 0.024F < state.length * 16.0F;
        this.eddy6.zScale = Math.min(this.eddy6.zScale, Math.max(0.001F, (state.length * 16.0F + this.eddy6.z) / 24.0F));
        this.eddy7.visible = -this.eddy7.z + 0.024F < state.length * 16.0F;
        this.eddy7.zScale = Math.min(this.eddy7.zScale, Math.max(0.001F, (state.length * 16.0F + this.eddy7.z) / 24.0F));
        this.eddy8.visible = -this.eddy8.z + 0.024F < state.length * 16.0F;
        this.eddy8.zScale = Math.min(this.eddy8.zScale, Math.max(0.001F, (state.length * 16.0F + this.eddy8.z) / 24.0F));
        this.eddy9.visible = -this.eddy9.z + 0.024F < state.length * 16.0F;
        this.eddy9.zScale = Math.min(this.eddy9.zScale, Math.max(0.001F, (state.length * 16.0F + this.eddy9.z) / 24.0F));
        this.eddy10.visible = -this.eddy10.z + 0.024F < state.length * 16.0F;
        this.eddy10.zScale = Math.min(this.eddy10.zScale, Math.max(0.001F, (state.length * 16.0F + this.eddy10.z) / 24.0F));
        this.eddy11.visible = -this.eddy11.z + 0.024F < state.length * 16.0F;
        this.eddy11.zScale = Math.min(this.eddy11.zScale, Math.max(0.001F, (state.length * 16.0F + this.eddy11.z) / 24.0F));
        this.eddy12.visible = -this.eddy12.z + 0.024F < state.length * 16.0F;
        this.eddy12.zScale = Math.min(this.eddy12.zScale, Math.max(0.001F, (state.length * 16.0F + this.eddy12.z) / 24.0F));
        this.eddy13.visible = -this.eddy13.z + 0.024F < state.length * 16.0F;
        this.eddy13.zScale = Math.min(this.eddy13.zScale, Math.max(0.001F, (state.length * 16.0F + this.eddy13.z) / 24.0F));
        this.eddy14.visible = -this.eddy14.z + 0.024F < state.length * 16.0F;
        this.eddy14.zScale = Math.min(this.eddy14.zScale, Math.max(0.001F, (state.length * 16.0F + this.eddy14.z) / 24.0F));
        this.eddy15.visible = -this.eddy15.z + 0.024F < state.length * 16.0F;
        this.eddy15.zScale = Math.min(this.eddy15.zScale, Math.max(0.001F, (state.length * 16.0F + this.eddy15.z) / 24.0F));
        this.throat0.zScale = Math.min(this.throat0.zScale, state.length);
        this.throat1.zScale = Math.min(this.throat1.zScale, state.length);
        this.throat2.zScale = Math.min(this.throat2.zScale, state.length);
    }

    private static float rad(float degrees) {
        return degrees * Mth.DEG_TO_RAD;
    }
}
