package com.digicube.fabric.client.model;

import com.digicube.Constants;
import com.digicube.fabric.client.render.BubbleBlowRenderState;
import net.minecraft.client.animation.KeyframeAnimation;

import java.util.HashMap;
import java.util.Map;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * BubbleBlowModel -- GENERATED by the DigiCube model harness from digimon/bubble_blow.py.
 * Geometry matches the Blender rig bone for bone; edit the spec and regenerate rather
 * than hand-tuning coordinates here. setupAnim is a starting point and may be edited.
 *
 * Vanilla model space: Y down, ground at y=24, front at -Z. Atlas 128x64.
 */
public class BubbleBlowModel extends EntityModel<BubbleBlowRenderState> {

    /** Client model layer used when baking this species. */
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Constants.id("bubble_blow"), "main");

    private final ModelPart bubble0;
    private final ModelPart disk0;
    private final ModelPart pop0;
    private final ModelPart bubble1;
    private final ModelPart disk1;
    private final ModelPart pop1;
    private final ModelPart bubble2;
    private final ModelPart disk2;
    private final ModelPart pop2;
    private final ModelPart bubble3;
    private final ModelPart disk3;
    private final ModelPart pop3;
    private final ModelPart bubble4;
    private final ModelPart disk4;
    private final ModelPart pop4;
    private final ModelPart bubble5;
    private final ModelPart disk5;
    private final ModelPart pop5;
    private final ModelPart bubble6;
    private final ModelPart disk6;
    private final ModelPart pop6;

    /** Baked once per model instance; keyed by harness animation name. */
    private final Map<String, KeyframeAnimation> animations = new HashMap<>();

    /**
     * Creates the model and binds its animation bones.
     * @param root baked root from this model's layer
     */
    public BubbleBlowModel(ModelPart root) {
        super(root);
        this.bubble0 = root.getChild("bubble0");
        this.disk0 = root.getChild("bubble0").getChild("disk0");
        this.pop0 = root.getChild("bubble0").getChild("pop0");
        this.bubble1 = root.getChild("bubble1");
        this.disk1 = root.getChild("bubble1").getChild("disk1");
        this.pop1 = root.getChild("bubble1").getChild("pop1");
        this.bubble2 = root.getChild("bubble2");
        this.disk2 = root.getChild("bubble2").getChild("disk2");
        this.pop2 = root.getChild("bubble2").getChild("pop2");
        this.bubble3 = root.getChild("bubble3");
        this.disk3 = root.getChild("bubble3").getChild("disk3");
        this.pop3 = root.getChild("bubble3").getChild("pop3");
        this.bubble4 = root.getChild("bubble4");
        this.disk4 = root.getChild("bubble4").getChild("disk4");
        this.pop4 = root.getChild("bubble4").getChild("pop4");
        this.bubble5 = root.getChild("bubble5");
        this.disk5 = root.getChild("bubble5").getChild("disk5");
        this.pop5 = root.getChild("bubble5").getChild("pop5");
        this.bubble6 = root.getChild("bubble6");
        this.disk6 = root.getChild("bubble6").getChild("disk6");
        this.pop6 = root.getChild("bubble6").getChild("pop6");
        BubbleBlowAnimations.BY_NAME.forEach((name, definition) -> this.animations.put(name, definition.bake(root)));
    }

    /**
     * Builds the authored geometry and texture layout.
     * @return the layer to register with the client
     */
    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

        PartDefinition bubble0 = root.addOrReplaceChild("bubble0", CubeListBuilder.create(), PartPose.offset(0.0F, 24.0F, 0.0F));

        bubble0.addOrReplaceChild("disk0", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(-5.0F, -5.0F, 0.0F, 10.0F, 10.0F, 0.0F)   // disk0
                , PartPose.offset(0.0F, 0.0F, 0.0F));

        bubble0.addOrReplaceChild("pop0", CubeListBuilder.create()
                        .texOffs(20, 0).addBox(-5.0F, -5.0F, 0.0F, 10.0F, 10.0F, 0.0F)   // pop0
                , PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition bubble1 = root.addOrReplaceChild("bubble1", CubeListBuilder.create(), PartPose.offset(-4.0F, 22.0F, 6.0F));

        bubble1.addOrReplaceChild("disk1", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(-5.0F, -5.0F, 0.0F, 10.0F, 10.0F, 0.0F)   // disk1
                , PartPose.offset(0.0F, 0.0F, 0.0F));

        bubble1.addOrReplaceChild("pop1", CubeListBuilder.create()
                        .texOffs(20, 0).addBox(-5.0F, -5.0F, 0.0F, 10.0F, 10.0F, 0.0F)   // pop1
                , PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition bubble2 = root.addOrReplaceChild("bubble2", CubeListBuilder.create(), PartPose.offset(4.0F, 26.0F, 10.0F));

        bubble2.addOrReplaceChild("disk2", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(-5.0F, -5.0F, 0.0F, 10.0F, 10.0F, 0.0F)   // disk2
                , PartPose.offset(0.0F, 0.0F, 0.0F));

        bubble2.addOrReplaceChild("pop2", CubeListBuilder.create()
                        .texOffs(20, 0).addBox(-5.0F, -5.0F, 0.0F, 10.0F, 10.0F, 0.0F)   // pop2
                , PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition bubble3 = root.addOrReplaceChild("bubble3", CubeListBuilder.create(), PartPose.offset(-3.0F, 27.0F, 15.0F));

        bubble3.addOrReplaceChild("disk3", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(-5.0F, -5.0F, 0.0F, 10.0F, 10.0F, 0.0F)   // disk3
                , PartPose.offset(0.0F, 0.0F, 0.0F));

        bubble3.addOrReplaceChild("pop3", CubeListBuilder.create()
                        .texOffs(20, 0).addBox(-5.0F, -5.0F, 0.0F, 10.0F, 10.0F, 0.0F)   // pop3
                , PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition bubble4 = root.addOrReplaceChild("bubble4", CubeListBuilder.create(), PartPose.offset(5.0F, 21.0F, 20.0F));

        bubble4.addOrReplaceChild("disk4", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(-5.0F, -5.0F, 0.0F, 10.0F, 10.0F, 0.0F)   // disk4
                , PartPose.offset(0.0F, 0.0F, 0.0F));

        bubble4.addOrReplaceChild("pop4", CubeListBuilder.create()
                        .texOffs(20, 0).addBox(-5.0F, -5.0F, 0.0F, 10.0F, 10.0F, 0.0F)   // pop4
                , PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition bubble5 = root.addOrReplaceChild("bubble5", CubeListBuilder.create(), PartPose.offset(-5.0F, 23.0F, 24.0F));

        bubble5.addOrReplaceChild("disk5", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(-5.0F, -5.0F, 0.0F, 10.0F, 10.0F, 0.0F)   // disk5
                , PartPose.offset(0.0F, 0.0F, 0.0F));

        bubble5.addOrReplaceChild("pop5", CubeListBuilder.create()
                        .texOffs(20, 0).addBox(-5.0F, -5.0F, 0.0F, 10.0F, 10.0F, 0.0F)   // pop5
                , PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition bubble6 = root.addOrReplaceChild("bubble6", CubeListBuilder.create(), PartPose.offset(1.0F, 26.0F, 29.0F));

        bubble6.addOrReplaceChild("disk6", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(-5.0F, -5.0F, 0.0F, 10.0F, 10.0F, 0.0F)   // disk6
                , PartPose.offset(0.0F, 0.0F, 0.0F));

        bubble6.addOrReplaceChild("pop6", CubeListBuilder.create()
                        .texOffs(20, 0).addBox(-5.0F, -5.0F, 0.0F, 10.0F, 10.0F, 0.0F)   // pop6
                , PartPose.offset(0.0F, 0.0F, 0.0F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    @Override
    public void setupAnim(BubbleBlowRenderState state) {
        super.setupAnim(state);
        this.animations.get(state.popped ? "pop" : "flight").apply(
                (long) ((state.popped ? state.popTicks : state.ageInTicks) * 50.0F), 1.0F);
        this.disk0.visible = !state.popped && state.ageInTicks >= 0.0F;
        this.pop0.visible = state.popped && state.ageInTicks >= 0.0F;
        this.disk0.xRot = this.pop0.xRot = state.billboardPitch;
        this.disk0.yRot = this.pop0.yRot = state.billboardYaw;
        this.disk1.visible = !state.popped && state.ageInTicks >= 1.0F;
        this.pop1.visible = state.popped && state.ageInTicks >= 1.0F;
        this.disk1.xRot = this.pop1.xRot = state.billboardPitch;
        this.disk1.yRot = this.pop1.yRot = state.billboardYaw;
        this.disk2.visible = !state.popped && state.ageInTicks >= 1.0F;
        this.pop2.visible = state.popped && state.ageInTicks >= 1.0F;
        this.disk2.xRot = this.pop2.xRot = state.billboardPitch;
        this.disk2.yRot = this.pop2.yRot = state.billboardYaw;
        this.disk3.visible = !state.popped && state.ageInTicks >= 2.0F;
        this.pop3.visible = state.popped && state.ageInTicks >= 2.0F;
        this.disk3.xRot = this.pop3.xRot = state.billboardPitch;
        this.disk3.yRot = this.pop3.yRot = state.billboardYaw;
        this.disk4.visible = !state.popped && state.ageInTicks >= 2.0F;
        this.pop4.visible = state.popped && state.ageInTicks >= 2.0F;
        this.disk4.xRot = this.pop4.xRot = state.billboardPitch;
        this.disk4.yRot = this.pop4.yRot = state.billboardYaw;
        this.disk5.visible = !state.popped && state.ageInTicks >= 2.0F;
        this.pop5.visible = state.popped && state.ageInTicks >= 2.0F;
        this.disk5.xRot = this.pop5.xRot = state.billboardPitch;
        this.disk5.yRot = this.pop5.yRot = state.billboardYaw;
        this.disk6.visible = !state.popped && state.ageInTicks >= 3.0F;
        this.pop6.visible = state.popped && state.ageInTicks >= 3.0F;
        this.disk6.xRot = this.pop6.xRot = state.billboardPitch;
        this.disk6.yRot = this.pop6.yRot = state.billboardYaw;
    }

    private static float rad(float degrees) {
        return degrees * Mth.DEG_TO_RAD;
    }
}
