package com.digicube.fabric.client.model;

import com.digicube.Constants;
import com.digicube.fabric.client.render.DigimonRenderState;
import net.minecraft.client.animation.KeyframeAnimation;

import java.util.HashMap;
import java.util.Map;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * GabumonModel -- GENERATED by the DigiCube model harness from digimon/gabumon.py.
 * Geometry matches the Blender rig bone for bone; edit the spec and regenerate rather
 * than hand-tuning coordinates here. setupAnim is a starting point and may be edited.
 *
 * Vanilla model space: Y down, ground at y=24, front at -Z. Atlas 256x64.
 */
public class GabumonModel extends EntityModel<DigimonRenderState> {

    /** Client model layer used when baking this species. */
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Constants.id("gabumon"), "main");

    private final ModelPart body;
    private final ModelPart peltBack;
    private final ModelPart leftCapeEdge;
    private final ModelPart rightCapeEdge;
    private final ModelPart head;
    private final ModelPart leftEyeSocket;
    private final ModelPart leftEar;
    private final ModelPart leftEarFold;
    private final ModelPart rightEyeSocket;
    private final ModelPart rightEar;
    private final ModelPart rightEarFold;
    private final ModelPart jaw;
    private final ModelPart horn;
    private final ModelPart hornPointA;
    private final ModelPart hornPointB;
    private final ModelPart leftArm;
    private final ModelPart leftForearm;
    private final ModelPart leftPeltClaw0;
    private final ModelPart leftPeltNail0A;
    private final ModelPart leftPeltNail0B;
    private final ModelPart leftPeltClaw1;
    private final ModelPart leftPeltNail1A;
    private final ModelPart leftPeltNail1B;
    private final ModelPart leftPeltClaw2;
    private final ModelPart leftPeltNail2A;
    private final ModelPart leftPeltNail2B;
    private final ModelPart leftInnerArm;
    private final ModelPart leftLeg;
    private final ModelPart leftFoot;
    private final ModelPart rightArm;
    private final ModelPart rightForearm;
    private final ModelPart rightPeltClaw0;
    private final ModelPart rightPeltNail0A;
    private final ModelPart rightPeltNail0B;
    private final ModelPart rightPeltClaw1;
    private final ModelPart rightPeltNail1A;
    private final ModelPart rightPeltNail1B;
    private final ModelPart rightPeltClaw2;
    private final ModelPart rightPeltNail2A;
    private final ModelPart rightPeltNail2B;
    private final ModelPart rightInnerArm;
    private final ModelPart rightLeg;
    private final ModelPart rightFoot;
    private final ModelPart tail;
    private final ModelPart tailMid;
    private final ModelPart tailTip;

    /** Baked once per model instance; keyed by harness animation name. */
    private final Map<String, KeyframeAnimation> animations = new HashMap<>();

    /**
     * Creates the model and binds its animation bones.
     * @param root baked root from this model's layer
     */
    public GabumonModel(ModelPart root) {
        super(root);
        this.body = root.getChild("body");
        this.peltBack = root.getChild("body").getChild("pelt_back");
        this.leftCapeEdge = root.getChild("body").getChild("pelt_back").getChild("left_cape_edge");
        this.rightCapeEdge = root.getChild("body").getChild("pelt_back").getChild("right_cape_edge");
        this.head = root.getChild("body").getChild("head");
        this.leftEyeSocket = root.getChild("body").getChild("head").getChild("left_eye_socket");
        this.leftEar = root.getChild("body").getChild("head").getChild("left_ear");
        this.leftEarFold = root.getChild("body").getChild("head").getChild("left_ear").getChild("left_ear_fold");
        this.rightEyeSocket = root.getChild("body").getChild("head").getChild("right_eye_socket");
        this.rightEar = root.getChild("body").getChild("head").getChild("right_ear");
        this.rightEarFold = root.getChild("body").getChild("head").getChild("right_ear").getChild("right_ear_fold");
        this.jaw = root.getChild("body").getChild("head").getChild("jaw");
        this.horn = root.getChild("body").getChild("head").getChild("horn");
        this.hornPointA = root.getChild("body").getChild("head").getChild("horn").getChild("horn_point_a");
        this.hornPointB = root.getChild("body").getChild("head").getChild("horn").getChild("horn_point_b");
        this.leftArm = root.getChild("body").getChild("left_arm");
        this.leftForearm = root.getChild("body").getChild("left_arm").getChild("left_forearm");
        this.leftPeltClaw0 = root.getChild("body").getChild("left_arm").getChild("left_forearm").getChild("left_pelt_claw0");
        this.leftPeltNail0A = root.getChild("body").getChild("left_arm").getChild("left_forearm").getChild("left_pelt_claw0").getChild("left_pelt_nail0_a");
        this.leftPeltNail0B = root.getChild("body").getChild("left_arm").getChild("left_forearm").getChild("left_pelt_claw0").getChild("left_pelt_nail0_b");
        this.leftPeltClaw1 = root.getChild("body").getChild("left_arm").getChild("left_forearm").getChild("left_pelt_claw1");
        this.leftPeltNail1A = root.getChild("body").getChild("left_arm").getChild("left_forearm").getChild("left_pelt_claw1").getChild("left_pelt_nail1_a");
        this.leftPeltNail1B = root.getChild("body").getChild("left_arm").getChild("left_forearm").getChild("left_pelt_claw1").getChild("left_pelt_nail1_b");
        this.leftPeltClaw2 = root.getChild("body").getChild("left_arm").getChild("left_forearm").getChild("left_pelt_claw2");
        this.leftPeltNail2A = root.getChild("body").getChild("left_arm").getChild("left_forearm").getChild("left_pelt_claw2").getChild("left_pelt_nail2_a");
        this.leftPeltNail2B = root.getChild("body").getChild("left_arm").getChild("left_forearm").getChild("left_pelt_claw2").getChild("left_pelt_nail2_b");
        this.leftInnerArm = root.getChild("body").getChild("left_inner_arm");
        this.leftLeg = root.getChild("left_leg");
        this.leftFoot = root.getChild("left_leg").getChild("left_foot");
        this.rightArm = root.getChild("body").getChild("right_arm");
        this.rightForearm = root.getChild("body").getChild("right_arm").getChild("right_forearm");
        this.rightPeltClaw0 = root.getChild("body").getChild("right_arm").getChild("right_forearm").getChild("right_pelt_claw0");
        this.rightPeltNail0A = root.getChild("body").getChild("right_arm").getChild("right_forearm").getChild("right_pelt_claw0").getChild("right_pelt_nail0_a");
        this.rightPeltNail0B = root.getChild("body").getChild("right_arm").getChild("right_forearm").getChild("right_pelt_claw0").getChild("right_pelt_nail0_b");
        this.rightPeltClaw1 = root.getChild("body").getChild("right_arm").getChild("right_forearm").getChild("right_pelt_claw1");
        this.rightPeltNail1A = root.getChild("body").getChild("right_arm").getChild("right_forearm").getChild("right_pelt_claw1").getChild("right_pelt_nail1_a");
        this.rightPeltNail1B = root.getChild("body").getChild("right_arm").getChild("right_forearm").getChild("right_pelt_claw1").getChild("right_pelt_nail1_b");
        this.rightPeltClaw2 = root.getChild("body").getChild("right_arm").getChild("right_forearm").getChild("right_pelt_claw2");
        this.rightPeltNail2A = root.getChild("body").getChild("right_arm").getChild("right_forearm").getChild("right_pelt_claw2").getChild("right_pelt_nail2_a");
        this.rightPeltNail2B = root.getChild("body").getChild("right_arm").getChild("right_forearm").getChild("right_pelt_claw2").getChild("right_pelt_nail2_b");
        this.rightInnerArm = root.getChild("body").getChild("right_inner_arm");
        this.rightLeg = root.getChild("right_leg");
        this.rightFoot = root.getChild("right_leg").getChild("right_foot");
        this.tail = root.getChild("body").getChild("tail");
        this.tailMid = root.getChild("body").getChild("tail").getChild("tail_mid");
        this.tailTip = root.getChild("body").getChild("tail").getChild("tail_mid").getChild("tail_tip");
        GabumonAnimations.BY_NAME.forEach((name, definition) -> this.animations.put(name, definition.bake(root)));
    }

    /**
     * Builds the authored geometry and texture layout.
     * @return the layer to register with the client
     */
    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(-6.0F, -9.0F, -4.0F, 12.0F, 12.0F, 8.0F)   // belly
                        .texOffs(208, 0).addBox(-5.0F, -13.0F, -3.5F, 10.0F, 5.0F, 7.0F)   // chest
                        .texOffs(84, 20).addBox(-5.0F, 1.0F, -3.0F, 10.0F, 4.0F, 7.0F)   // hips
                        .texOffs(184, 0).addBox(-6.0F, -8.0F, -4.13F, 12.0F, 13.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // belly_emblem
                , PartPose.offset(0.0F, 14.0F, 0.0F));

        PartDefinition peltBack = body.addOrReplaceChild("pelt_back", CubeListBuilder.create()
                        .texOffs(124, 0).addBox(-7.0F, -3.0F, -0.5F, 14.0F, 12.0F, 3.0F)   // cape_upper
                        .texOffs(118, 20).addBox(3.0F, 8.0F, -0.5F, 4.0F, 8.0F, 3.0F)   // left_cape_lower
                        .texOffs(154, 32).addBox(2.0F, 14.0F, 2.55F, 5.0F, 5.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_cape_hem
                        .texOffs(118, 20).addBox(-7.0F, 8.0F, -0.5F, 4.0F, 8.0F, 3.0F)   // right_cape_lower
                        .texOffs(154, 32).addBox(-7.0F, 14.0F, 2.55F, 5.0F, 5.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_cape_hem
                , PartPose.offset(0.0F, -12.0F, 4.0F));

        peltBack.addOrReplaceChild("left_cape_edge", CubeListBuilder.create()
                        .texOffs(40, 0).addBox(-1.0F, -8.0F, -4.0F, 2.0F, 14.0F, 5.0F)   // left_mantle_side
                        .texOffs(242, 0).addBox(-1.5F, -5.0F, -4.15F, 3.0F, 12.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_mantle_fringe
                , PartPose.offsetAndRotation(6.0F, 7.0F, -0.5F, rad(0.0F), rad(-10.0F), rad(0.0F)));

        peltBack.addOrReplaceChild("right_cape_edge", CubeListBuilder.create()
                        .texOffs(40, 0).addBox(-1.0F, -8.0F, -4.0F, 2.0F, 14.0F, 5.0F)   // right_mantle_side
                        .texOffs(242, 0).addBox(-1.5F, -5.0F, -4.15F, 3.0F, 12.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_mantle_fringe
                , PartPose.offsetAndRotation(-6.0F, 7.0F, -0.5F, rad(0.0F), rad(10.0F), rad(0.0F)));

        PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create()
                        .texOffs(54, 0).addBox(-7.0F, -8.0F, -3.5F, 14.0F, 9.0F, 10.0F)   // hood
                        .texOffs(132, 20).addBox(-6.0F, -9.0F, -3.0F, 12.0F, 2.0F, 9.0F)   // crown
                        .texOffs(0, 32).addBox(6.0F, -4.0F, -2.4F, 4.0F, 7.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_cheek_tuft
                        .texOffs(8, 32).addBox(-10.0F, -4.0F, -2.4F, 4.0F, 7.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_cheek_tuft
                        .texOffs(16, 32).addBox(-5.0F, -2.0F, -7.5F, 10.0F, 3.0F, 4.0F)   // muzzle
                        .texOffs(164, 32).addBox(-3.0F, -3.0F, -6.5F, 6.0F, 2.0F, 3.0F)   // muzzle_bridge
                        .texOffs(246, 32).addBox(-1.5F, -2.5F, -8.3F, 3.0F, 2.0F, 1.0F)   // nose
                        .texOffs(0, 39).addBox(-5.0F, 0.0F, -7.63F, 10.0F, 3.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // hood_fangs
                        .texOffs(44, 32).addBox(5.12F, 0.0F, -7.0F, 0.0F, 3.0F, 4.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // left_side_fangs
                        .addBox(-5.12F, 0.0F, -7.0F, 0.0F, 3.0F, 4.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // right_side_fangs
                , PartPose.offset(0.0F, -12.0F, -0.5F));

        head.addOrReplaceChild("left_eye_socket", CubeListBuilder.create()
                        .texOffs(220, 20).addBox(-3F, -3.5F, -0.4F, 6.0F, 7.0F, 2.0F)   // left_brow
                        .texOffs(52, 32).addBox(-3F, -3.5F, -0.54F, 6.0F, 7.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_eye
                        .texOffs(20, 39).addBox(-3F, 2.5F, -0.56F, 6.0F, 3.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_cheek_marks
                , PartPose.offsetAndRotation(4.7F, -4.0F, -4.1F, rad(0.0F), rad(-18.0F), rad(0.0F)));

        PartDefinition leftEar = head.addOrReplaceChild("left_ear", CubeListBuilder.create()
                        .texOffs(228, 32).addBox(-1.5F, -1.0F, -1.0F, 3.0F, 2.0F, 2.0F)   // left_ear_root
                        .texOffs(182, 32).addBox(0.0F, -3.0F, -1.15F, 8.0F, 5.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_ear_sheet
                , PartPose.offsetAndRotation(6.4F, -7.2F, 1.0F, rad(0.0F), rad(-5.0F), rad(11.0F)));

        leftEar.addOrReplaceChild("left_ear_fold", CubeListBuilder.create()
                        .texOffs(32, 39).addBox(-0.5F, -2.0F, -0.05F, 4.0F, 3.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_ear_tip
                , PartPose.offsetAndRotation(5.1F, 0.0F, -1.15F, rad(18.0F), rad(0.0F), rad(0.0F)));

        head.addOrReplaceChild("right_eye_socket", CubeListBuilder.create()
                        .texOffs(220, 20).addBox(-3.0F, -3.5F, -0.4F, 6.0F, 7.0F, 2.0F)   // right_brow
                        .texOffs(64, 32).addBox(-3.0F, -3.5F, -0.54F, 6.0F, 7.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_eye
                        .texOffs(40, 39).addBox(-3.0F, 2.5F, -0.56F, 6.0F, 3.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_cheek_marks
                , PartPose.offsetAndRotation(-4.7F, -4.0F, -4.1F, rad(0.0F), rad(18.0F), rad(0.0F)));

        PartDefinition rightEar = head.addOrReplaceChild("right_ear", CubeListBuilder.create()
                        .texOffs(228, 32).addBox(-1.5F, -1.0F, -1.0F, 3.0F, 2.0F, 2.0F)   // right_ear_root
                        .texOffs(198, 32).addBox(-8F, -3.0F, -1.15F, 8.0F, 5.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_ear_sheet
                , PartPose.offsetAndRotation(-6.4F, -7.2F, 1.0F, rad(0.0F), rad(5.0F), rad(-11.0F)));

        rightEar.addOrReplaceChild("right_ear_fold", CubeListBuilder.create()
                        .texOffs(52, 39).addBox(-3.5F, -2.0F, -0.05F, 4.0F, 3.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_ear_tip
                , PartPose.offsetAndRotation(-5.1F, 0.0F, -1.15F, rad(-18.0F), rad(0.0F), rad(0.0F)));

        head.addOrReplaceChild("jaw", CubeListBuilder.create()
                        .texOffs(76, 32).addBox(-4.0F, 0.0F, -4.5F, 8.0F, 2.0F, 5.0F)   // yellow_jaw
                        .texOffs(114, 32).addBox(-3.0F, 1.0F, -4.0F, 6.0F, 2.0F, 4.0F)   // chin
                , PartPose.offset(0.0F, 1.0F, -2.5F));

        PartDefinition horn = head.addOrReplaceChild("horn", CubeListBuilder.create()
                        .texOffs(102, 32).addBox(-1.5F, -3.0F, -1.5F, 3.0F, 4.0F, 3.0F)   // horn_base
                        .texOffs(214, 32).addBox(-1.0F, -6.0F, -1.0F, 2.0F, 3.0F, 2.0F)   // horn_mid
                        .texOffs(238, 32).addBox(-0.5F, -9.0F, -0.5F, 1.0F, 3.0F, 1.0F)   // horn_high
                , PartPose.offsetAndRotation(0.0F, -8.0F, -1.3F, rad(7.0F), rad(0.0F), rad(0.0F)));

        horn.addOrReplaceChild("horn_point_a", CubeListBuilder.create()
                        .texOffs(98, 39).addBox(-0.5F, -2.0F, 0.0F, 1.0F, 2.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // horn_point_a
                , PartPose.offsetAndRotation(0.0F, -8.5F, 0.0F, rad(0.0F), rad(-45.0F), rad(0.0F)));

        horn.addOrReplaceChild("horn_point_b", CubeListBuilder.create()
                        .texOffs(98, 39).addBox(-0.5F, -2.0F, 0.0F, 1.0F, 2.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // horn_point_b
                , PartPose.offsetAndRotation(0.0F, -8.5F, 0.0F, rad(0.0F), rad(45.0F), rad(0.0F)));

        PartDefinition leftArm = body.addOrReplaceChild("left_arm", CubeListBuilder.create()
                        .texOffs(102, 0).addBox(-1.8F, -1.0F, -3.0F, 5.0F, 10.0F, 6.0F)   // left_sleeve_upper
                , PartPose.offsetAndRotation(7.3F, -12.0F, 0.0F, rad(-3.0F), rad(0.0F), rad(-6.0F)));

        PartDefinition leftForearm = leftArm.addOrReplaceChild("left_forearm", CubeListBuilder.create()
                        .texOffs(158, 0).addBox(-2.9F, -1.5F, -3.5F, 6.0F, 8.0F, 7.0F)   // left_sleeve_lower
                        .texOffs(0, 20).addBox(-3.4F, 4.5F, -4.5F, 7.0F, 4.0F, 8.0F)   // left_pelt_paw
                        .texOffs(60, 39).addBox(-3.4F, 6.5F, -4.62F, 7.0F, 3.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_cuff_fringe
                , PartPose.offset(1.1F, 9.0F, -0.5F));

        PartDefinition leftPeltClaw0 = leftForearm.addOrReplaceChild("left_pelt_claw0", CubeListBuilder.create(), PartPose.offsetAndRotation(-2.3F, 8.0F, -3.3F, rad(-20.0F), rad(0.0F), rad(0.0F)));

        leftPeltClaw0.addOrReplaceChild("left_pelt_nail0_a", CubeListBuilder.create()
                        .texOffs(242, 32).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_pelt_nail0_a
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(-30.0F), rad(0.0F)));

        leftPeltClaw0.addOrReplaceChild("left_pelt_nail0_b", CubeListBuilder.create()
                        .texOffs(242, 32).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_pelt_nail0_b
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(30.0F), rad(0.0F)));

        PartDefinition leftPeltClaw1 = leftForearm.addOrReplaceChild("left_pelt_claw1", CubeListBuilder.create(), PartPose.offsetAndRotation(0.1F, 8.0F, -3.3F, rad(-20.0F), rad(0.0F), rad(0.0F)));

        leftPeltClaw1.addOrReplaceChild("left_pelt_nail1_a", CubeListBuilder.create()
                        .texOffs(242, 32).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_pelt_nail1_a
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(-30.0F), rad(0.0F)));

        leftPeltClaw1.addOrReplaceChild("left_pelt_nail1_b", CubeListBuilder.create()
                        .texOffs(242, 32).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_pelt_nail1_b
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(30.0F), rad(0.0F)));

        PartDefinition leftPeltClaw2 = leftForearm.addOrReplaceChild("left_pelt_claw2", CubeListBuilder.create(), PartPose.offsetAndRotation(2.5F, 8.0F, -3.3F, rad(-20.0F), rad(0.0F), rad(0.0F)));

        leftPeltClaw2.addOrReplaceChild("left_pelt_nail2_a", CubeListBuilder.create()
                        .texOffs(242, 32).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_pelt_nail2_a
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(-30.0F), rad(0.0F)));

        leftPeltClaw2.addOrReplaceChild("left_pelt_nail2_b", CubeListBuilder.create()
                        .texOffs(242, 32).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_pelt_nail2_b
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(30.0F), rad(0.0F)));

        body.addOrReplaceChild("left_inner_arm", CubeListBuilder.create()
                        .texOffs(30, 20).addBox(-0.8F, 0.0F, -2.5F, 2.0F, 9.0F, 3.0F)   // left_yellow_arm
                        .texOffs(134, 32).addBox(-1.6F, 8.0F, -3.5F, 3.0F, 3.0F, 3.0F)   // left_yellow_hand
                , PartPose.offsetAndRotation(5.8F, -8.0F, -2.0F, rad(-5.0F), rad(0.0F), rad(4.0F)));

        PartDefinition rightArm = body.addOrReplaceChild("right_arm", CubeListBuilder.create()
                        .texOffs(102, 0).addBox(-3.2F, -1.0F, -3.0F, 5.0F, 10.0F, 6.0F)   // right_sleeve_upper
                , PartPose.offsetAndRotation(-7.3F, -12.0F, 0.0F, rad(-3.0F), rad(0.0F), rad(6.0F)));

        PartDefinition rightForearm = rightArm.addOrReplaceChild("right_forearm", CubeListBuilder.create()
                        .texOffs(158, 0).addBox(-3.1F, -1.5F, -3.5F, 6.0F, 8.0F, 7.0F)   // right_sleeve_lower
                        .texOffs(0, 20).addBox(-3.6F, 4.5F, -4.5F, 7.0F, 4.0F, 8.0F)   // right_pelt_paw
                        .texOffs(60, 39).addBox(-3.6F, 6.5F, -4.62F, 7.0F, 3.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_cuff_fringe
                , PartPose.offset(-1.1F, 9.0F, -0.5F));

        PartDefinition rightPeltClaw0 = rightForearm.addOrReplaceChild("right_pelt_claw0", CubeListBuilder.create(), PartPose.offsetAndRotation(-2.5F, 8.0F, -3.3F, rad(-20.0F), rad(0.0F), rad(0.0F)));

        rightPeltClaw0.addOrReplaceChild("right_pelt_nail0_a", CubeListBuilder.create()
                        .texOffs(242, 32).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_pelt_nail0_a
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(-30.0F), rad(0.0F)));

        rightPeltClaw0.addOrReplaceChild("right_pelt_nail0_b", CubeListBuilder.create()
                        .texOffs(242, 32).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_pelt_nail0_b
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(30.0F), rad(0.0F)));

        PartDefinition rightPeltClaw1 = rightForearm.addOrReplaceChild("right_pelt_claw1", CubeListBuilder.create(), PartPose.offsetAndRotation(-0.1F, 8.0F, -3.3F, rad(-20.0F), rad(0.0F), rad(0.0F)));

        rightPeltClaw1.addOrReplaceChild("right_pelt_nail1_a", CubeListBuilder.create()
                        .texOffs(242, 32).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_pelt_nail1_a
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(-30.0F), rad(0.0F)));

        rightPeltClaw1.addOrReplaceChild("right_pelt_nail1_b", CubeListBuilder.create()
                        .texOffs(242, 32).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_pelt_nail1_b
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(30.0F), rad(0.0F)));

        PartDefinition rightPeltClaw2 = rightForearm.addOrReplaceChild("right_pelt_claw2", CubeListBuilder.create(), PartPose.offsetAndRotation(2.3F, 8.0F, -3.3F, rad(-20.0F), rad(0.0F), rad(0.0F)));

        rightPeltClaw2.addOrReplaceChild("right_pelt_nail2_a", CubeListBuilder.create()
                        .texOffs(242, 32).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_pelt_nail2_a
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(-30.0F), rad(0.0F)));

        rightPeltClaw2.addOrReplaceChild("right_pelt_nail2_b", CubeListBuilder.create()
                        .texOffs(242, 32).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_pelt_nail2_b
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(30.0F), rad(0.0F)));

        body.addOrReplaceChild("right_inner_arm", CubeListBuilder.create()
                        .texOffs(30, 20).addBox(-1.2F, 0.0F, -2.5F, 2.0F, 9.0F, 3.0F)   // right_yellow_arm
                        .texOffs(134, 32).addBox(-1.4F, 8.0F, -3.5F, 3.0F, 3.0F, 3.0F)   // right_yellow_hand
                , PartPose.offsetAndRotation(-5.8F, -8.0F, -2.0F, rad(-5.0F), rad(0.0F), rad(-4.0F)));

        PartDefinition tail = body.addOrReplaceChild("tail", CubeListBuilder.create()
                        .texOffs(60, 20).addBox(-2.5F, -3.0F, 0.0F, 5.0F, 5.0F, 7.0F)   // tail_base
                        .texOffs(80, 39).addBox(-1.5F, -3.85F, 3.0F, 3.0F, 1.0F, 2.0F)   // tail_scute0
                , PartPose.offsetAndRotation(0.0F, 2.5F, 3.5F, rad(18.0F), rad(20.0F), rad(0.0F)));

        PartDefinition tailMid = tail.addOrReplaceChild("tail_mid", CubeListBuilder.create()
                        .texOffs(174, 20).addBox(-2.0F, -2.5F, 0.0F, 4.0F, 4.0F, 7.0F)   // tail_middle
                        .texOffs(80, 39).addBox(-1.5F, -3.35F, 2.0F, 3.0F, 1.0F, 2.0F)   // tail_scute1
                        .texOffs(90, 39).addBox(-1.0F, -3.35F, 5.5F, 2.0F, 1.0F, 2.0F)   // tail_scute2
                , PartPose.offsetAndRotation(0.0F, -0.5F, 6.0F, rad(12.0F), rad(0.0F), rad(0.0F)));

        tailMid.addOrReplaceChild("tail_tip", CubeListBuilder.create()
                        .texOffs(236, 20).addBox(-1.0F, -1.0F, 0.0F, 2.0F, 2.0F, 6.0F)   // tail_end
                        .texOffs(146, 32).addBox(0.0F, -1.0F, 5.0F, 0.0F, 2.0F, 4.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // tail_point
                        .texOffs(90, 39).addBox(-1.0F, -1.85F, 2.5F, 2.0F, 1.0F, 2.0F)   // tail_scute3
                , PartPose.offsetAndRotation(0.0F, -0.5F, 6.0F, rad(8.0F), rad(0.0F), rad(0.0F)));

        PartDefinition leftLeg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                        .texOffs(40, 20).addBox(-2.5F, -1.0F, -2.2F, 5.0F, 7.0F, 5.0F)   // left_thigh
                , PartPose.offset(3.7F, 16.0F, 0.0F));

        leftLeg.addOrReplaceChild("left_foot", CubeListBuilder.create()
                        .texOffs(196, 20).addBox(-2.5F, -1.0F, -4.7F, 5.0F, 3.0F, 7.0F)   // left_foot_pad
                        .texOffs(74, 39).addBox(-2.3F, 0.4F, -5.2F, 1.0F, 1.0F, 2.0F)   // left_toe_root0
                        .texOffs(222, 32).addBox(-1.8F, -0.25F, -7.2F, 0.0F, 2.0F, 3.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // left_toe0
                        .texOffs(74, 39).addBox(-0.5F, 0.4F, -5.2F, 1.0F, 1.0F, 2.0F)   // left_toe_root1
                        .texOffs(222, 32).addBox(0.0F, -0.25F, -7.2F, 0.0F, 2.0F, 3.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // left_toe1
                        .texOffs(74, 39).addBox(1.3F, 0.4F, -5.2F, 1.0F, 1.0F, 2.0F)   // left_toe_root2
                        .texOffs(222, 32).addBox(1.8F, -0.25F, -7.2F, 0.0F, 2.0F, 3.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // left_toe2
                , PartPose.offset(0.0F, 6.0F, -1.0F));

        PartDefinition rightLeg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                        .texOffs(40, 20).addBox(-2.5F, -1.0F, -2.2F, 5.0F, 7.0F, 5.0F)   // right_thigh
                , PartPose.offset(-3.7F, 16.0F, 0.0F));

        rightLeg.addOrReplaceChild("right_foot", CubeListBuilder.create()
                        .texOffs(196, 20).addBox(-2.5F, -1.0F, -4.7F, 5.0F, 3.0F, 7.0F)   // right_foot_pad
                        .texOffs(74, 39).addBox(-2.3F, 0.4F, -5.2F, 1.0F, 1.0F, 2.0F)   // right_toe_root0
                        .texOffs(222, 32).addBox(-1.8F, -0.25F, -7.2F, 0.0F, 2.0F, 3.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // right_toe0
                        .texOffs(74, 39).addBox(-0.5F, 0.4F, -5.2F, 1.0F, 1.0F, 2.0F)   // right_toe_root1
                        .texOffs(222, 32).addBox(0.0F, -0.25F, -7.2F, 0.0F, 2.0F, 3.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // right_toe1
                        .texOffs(74, 39).addBox(1.3F, 0.4F, -5.2F, 1.0F, 1.0F, 2.0F)   // right_toe_root2
                        .texOffs(222, 32).addBox(1.8F, -0.25F, -7.2F, 0.0F, 2.0F, 3.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // right_toe2
                , PartPose.offset(0.0F, 6.0F, -1.0F));
        return LayerDefinition.create(mesh, 256, 64);
    }

    @Override
    public void setupAnim(DigimonRenderState state) {
        super.setupAnim(state);
        this.animations.get("walk").applyWalk(state.walkAnimationPos, state.walkAnimationSpeed, 2.5F, 2.5F);
        this.head.yRot += Mth.clamp(state.yRot, -25.0F, 25.0F) * Mth.DEG_TO_RAD;
        this.head.xRot += Mth.clamp(state.xRot, -15.0F, 15.0F) * Mth.DEG_TO_RAD;
    }

    private static float rad(float degrees) {
        return degrees * Mth.DEG_TO_RAD;
    }
}
