package com.digicube.fabric.client.model;

import com.digicube.Constants;
import com.mojang.blaze3d.vertex.PoseStack;
import com.digicube.fabric.client.render.DigimonRenderState;
import net.minecraft.client.animation.KeyframeAnimation;

import java.util.HashMap;
import java.util.Map;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * GabumonModel -- GENERATED by the DigiCube model harness from digimon/gabumon_locomotion.py.
 * Geometry matches the Blender rig bone for bone; edit the spec and regenerate rather
 * than hand-tuning coordinates here. setupAnim is a starting point and may be edited.
 *
 * Vanilla model space: Y down, ground at y=24, front at -Z. Atlas 256x64.
 */
public class GabumonModel extends EntityModel<DigimonRenderState> {

    /** Client model layer used when baking this species. */
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Constants.id("gabumon"), "main");

    private final ModelPart body;
    private final ModelPart leftLeg;
    private final ModelPart rightLeg;
    private final ModelPart peltBack;
    private final ModelPart head;
    private final ModelPart tail;
    private final ModelPart abdomenTop;
    private final ModelPart abdomenLower;
    private final ModelPart leftShin;
    private final ModelPart rightShin;
    private final ModelPart leftInnerArm;
    private final ModelPart rightInnerArm;
    private final ModelPart leftCapeEdge;
    private final ModelPart rightCapeEdge;
    private final ModelPart leftEyeSocket;
    private final ModelPart leftEar;
    private final ModelPart rightEyeSocket;
    private final ModelPart rightEar;
    private final ModelPart jaw;
    private final ModelPart horn;
    private final ModelPart leftFoot;
    private final ModelPart rightFoot;
    private final ModelPart tailMid;
    private final ModelPart leftYellowForearm;
    private final ModelPart leftArm;
    private final ModelPart rightYellowForearm;
    private final ModelPart rightArm;
    private final ModelPart leftEarFold;
    private final ModelPart rightEarFold;
    private final ModelPart hornPointA;
    private final ModelPart hornPointB;
    private final ModelPart tailTip;
    private final ModelPart leftYellowHandJoint;
    private final ModelPart leftForearm;
    private final ModelPart rightYellowHandJoint;
    private final ModelPart rightForearm;
    private final ModelPart leftPeltGrip;
    private final ModelPart rightPeltGrip;
    private final ModelPart leftPeltClaw0;
    private final ModelPart leftPeltClaw1;
    private final ModelPart leftPeltClaw2;
    private final ModelPart rightPeltClaw0;
    private final ModelPart rightPeltClaw1;
    private final ModelPart rightPeltClaw2;
    private final ModelPart leftPeltNail0A;
    private final ModelPart leftPeltNail0B;
    private final ModelPart leftPeltNail1A;
    private final ModelPart leftPeltNail1B;
    private final ModelPart leftPeltNail2A;
    private final ModelPart leftPeltNail2B;
    private final ModelPart rightPeltNail0A;
    private final ModelPart rightPeltNail0B;
    private final ModelPart rightPeltNail1A;
    private final ModelPart rightPeltNail1B;
    private final ModelPart rightPeltNail2A;
    private final ModelPart rightPeltNail2B;

    /** Baked once per model instance; keyed by harness animation name. */
    private final Map<String, KeyframeAnimation> animations = new HashMap<>();

    /**
     * Creates the model and binds its animation bones.
     * @param root baked root from this model's layer
     */
    public GabumonModel(ModelPart root) {
        super(root);
        this.body = root.getChild("body");
        this.leftLeg = root.getChild("left_leg");
        this.rightLeg = root.getChild("right_leg");
        this.peltBack = root.getChild("body").getChild("pelt_back");
        this.head = root.getChild("body").getChild("head");
        this.tail = root.getChild("body").getChild("tail");
        this.abdomenTop = root.getChild("body").getChild("abdomen_top");
        this.abdomenLower = root.getChild("body").getChild("abdomen_lower");
        this.leftShin = root.getChild("left_leg").getChild("left_shin");
        this.rightShin = root.getChild("right_leg").getChild("right_shin");
        this.leftInnerArm = root.getChild("body").getChild("left_inner_arm");
        this.rightInnerArm = root.getChild("body").getChild("right_inner_arm");
        this.leftCapeEdge = root.getChild("body").getChild("pelt_back").getChild("left_cape_edge");
        this.rightCapeEdge = root.getChild("body").getChild("pelt_back").getChild("right_cape_edge");
        this.leftEyeSocket = root.getChild("body").getChild("head").getChild("left_eye_socket");
        this.leftEar = root.getChild("body").getChild("head").getChild("left_ear");
        this.rightEyeSocket = root.getChild("body").getChild("head").getChild("right_eye_socket");
        this.rightEar = root.getChild("body").getChild("head").getChild("right_ear");
        this.jaw = root.getChild("body").getChild("head").getChild("jaw");
        this.horn = root.getChild("body").getChild("head").getChild("horn");
        this.leftFoot = root.getChild("left_leg").getChild("left_shin").getChild("left_foot");
        this.rightFoot = root.getChild("right_leg").getChild("right_shin").getChild("right_foot");
        this.tailMid = root.getChild("body").getChild("tail").getChild("tail_mid");
        this.leftYellowForearm = root.getChild("body").getChild("left_inner_arm").getChild("left_yellow_forearm");
        this.leftArm = root.getChild("body").getChild("left_inner_arm").getChild("left_arm");
        this.rightYellowForearm = root.getChild("body").getChild("right_inner_arm").getChild("right_yellow_forearm");
        this.rightArm = root.getChild("body").getChild("right_inner_arm").getChild("right_arm");
        this.leftEarFold = root.getChild("body").getChild("head").getChild("left_ear").getChild("left_ear_fold");
        this.rightEarFold = root.getChild("body").getChild("head").getChild("right_ear").getChild("right_ear_fold");
        this.hornPointA = root.getChild("body").getChild("head").getChild("horn").getChild("horn_point_a");
        this.hornPointB = root.getChild("body").getChild("head").getChild("horn").getChild("horn_point_b");
        this.tailTip = root.getChild("body").getChild("tail").getChild("tail_mid").getChild("tail_tip");
        this.leftYellowHandJoint = root.getChild("body").getChild("left_inner_arm").getChild("left_yellow_forearm").getChild("left_yellow_hand_joint");
        this.leftForearm = root.getChild("body").getChild("left_inner_arm").getChild("left_yellow_forearm").getChild("left_forearm");
        this.rightYellowHandJoint = root.getChild("body").getChild("right_inner_arm").getChild("right_yellow_forearm").getChild("right_yellow_hand_joint");
        this.rightForearm = root.getChild("body").getChild("right_inner_arm").getChild("right_yellow_forearm").getChild("right_forearm");
        this.leftPeltGrip = root.getChild("body").getChild("left_inner_arm").getChild("left_yellow_forearm").getChild("left_yellow_hand_joint").getChild("left_pelt_grip");
        this.rightPeltGrip = root.getChild("body").getChild("right_inner_arm").getChild("right_yellow_forearm").getChild("right_yellow_hand_joint").getChild("right_pelt_grip");
        this.leftPeltClaw0 = root.getChild("body").getChild("left_inner_arm").getChild("left_yellow_forearm").getChild("left_yellow_hand_joint").getChild("left_pelt_grip").getChild("left_pelt_claw0");
        this.leftPeltClaw1 = root.getChild("body").getChild("left_inner_arm").getChild("left_yellow_forearm").getChild("left_yellow_hand_joint").getChild("left_pelt_grip").getChild("left_pelt_claw1");
        this.leftPeltClaw2 = root.getChild("body").getChild("left_inner_arm").getChild("left_yellow_forearm").getChild("left_yellow_hand_joint").getChild("left_pelt_grip").getChild("left_pelt_claw2");
        this.rightPeltClaw0 = root.getChild("body").getChild("right_inner_arm").getChild("right_yellow_forearm").getChild("right_yellow_hand_joint").getChild("right_pelt_grip").getChild("right_pelt_claw0");
        this.rightPeltClaw1 = root.getChild("body").getChild("right_inner_arm").getChild("right_yellow_forearm").getChild("right_yellow_hand_joint").getChild("right_pelt_grip").getChild("right_pelt_claw1");
        this.rightPeltClaw2 = root.getChild("body").getChild("right_inner_arm").getChild("right_yellow_forearm").getChild("right_yellow_hand_joint").getChild("right_pelt_grip").getChild("right_pelt_claw2");
        this.leftPeltNail0A = root.getChild("body").getChild("left_inner_arm").getChild("left_yellow_forearm").getChild("left_yellow_hand_joint").getChild("left_pelt_grip").getChild("left_pelt_claw0").getChild("left_pelt_nail0_a");
        this.leftPeltNail0B = root.getChild("body").getChild("left_inner_arm").getChild("left_yellow_forearm").getChild("left_yellow_hand_joint").getChild("left_pelt_grip").getChild("left_pelt_claw0").getChild("left_pelt_nail0_b");
        this.leftPeltNail1A = root.getChild("body").getChild("left_inner_arm").getChild("left_yellow_forearm").getChild("left_yellow_hand_joint").getChild("left_pelt_grip").getChild("left_pelt_claw1").getChild("left_pelt_nail1_a");
        this.leftPeltNail1B = root.getChild("body").getChild("left_inner_arm").getChild("left_yellow_forearm").getChild("left_yellow_hand_joint").getChild("left_pelt_grip").getChild("left_pelt_claw1").getChild("left_pelt_nail1_b");
        this.leftPeltNail2A = root.getChild("body").getChild("left_inner_arm").getChild("left_yellow_forearm").getChild("left_yellow_hand_joint").getChild("left_pelt_grip").getChild("left_pelt_claw2").getChild("left_pelt_nail2_a");
        this.leftPeltNail2B = root.getChild("body").getChild("left_inner_arm").getChild("left_yellow_forearm").getChild("left_yellow_hand_joint").getChild("left_pelt_grip").getChild("left_pelt_claw2").getChild("left_pelt_nail2_b");
        this.rightPeltNail0A = root.getChild("body").getChild("right_inner_arm").getChild("right_yellow_forearm").getChild("right_yellow_hand_joint").getChild("right_pelt_grip").getChild("right_pelt_claw0").getChild("right_pelt_nail0_a");
        this.rightPeltNail0B = root.getChild("body").getChild("right_inner_arm").getChild("right_yellow_forearm").getChild("right_yellow_hand_joint").getChild("right_pelt_grip").getChild("right_pelt_claw0").getChild("right_pelt_nail0_b");
        this.rightPeltNail1A = root.getChild("body").getChild("right_inner_arm").getChild("right_yellow_forearm").getChild("right_yellow_hand_joint").getChild("right_pelt_grip").getChild("right_pelt_claw1").getChild("right_pelt_nail1_a");
        this.rightPeltNail1B = root.getChild("body").getChild("right_inner_arm").getChild("right_yellow_forearm").getChild("right_yellow_hand_joint").getChild("right_pelt_grip").getChild("right_pelt_claw1").getChild("right_pelt_nail1_b");
        this.rightPeltNail2A = root.getChild("body").getChild("right_inner_arm").getChild("right_yellow_forearm").getChild("right_yellow_hand_joint").getChild("right_pelt_grip").getChild("right_pelt_claw2").getChild("right_pelt_nail2_a");
        this.rightPeltNail2B = root.getChild("body").getChild("right_inner_arm").getChild("right_yellow_forearm").getChild("right_yellow_hand_joint").getChild("right_pelt_grip").getChild("right_pelt_claw2").getChild("right_pelt_nail2_b");
        GabumonAnimations.BY_NAME.forEach((name, definition) -> this.animations.put(name, definition.bake(root)));
    }

    /**
     * Builds the authored geometry and texture layout.
     * @return the layer to register with the client
     */
    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                        .texOffs(150, 0).addBox(-5.0F, -13.25F, -3.5F, 10.0F, 5.0F, 7.0F)   // chest
                        .texOffs(62, 0).addBox(-7.0F, -4.0F, -6.5F, 14.0F, 5.0F, 10.0F)   // belly
                        .texOffs(20, 19).addBox(-4.0F, -9.0F, -2.5F, 8.0F, 6.0F, 5.0F)   // belly_core
                        .texOffs(24, 31).addBox(-4.0F, 2.0F, -3.25F, 8.0F, 2.0F, 6.0F)   // hips
                , PartPose.offset(0.0F, 14.0F, 0.0F));

        PartDefinition peltBack = body.addOrReplaceChild("pelt_back", CubeListBuilder.create()
                        .texOffs(52, 31).addBox(-7.0F, 4.0F, -0.5F, 14.0F, 5.0F, 3.0F)   // cape_upper
                        .texOffs(146, 19).addBox(3.0F, 9.0F, -0.5F, 4.0F, 7.0F, 3.0F)   // left_cape_lower
                        .texOffs(84, 40).addBox(2.0F, 14.0F, 2.55F, 5.0F, 5.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_cape_hem
                        .texOffs(146, 19).addBox(-7.0F, 9.0F, -0.5F, 4.0F, 7.0F, 3.0F)   // right_cape_lower
                        .texOffs(84, 40).addBox(-7.0F, 14.0F, 2.55F, 5.0F, 5.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_cape_hem
                        .texOffs(160, 19).addBox(-6.0F, -3.0F, -0.5F, 12.0F, 7.0F, 3.0F)   // cape_collar
                , PartPose.offset(0.0F, -12.0F, 4.0F));

        peltBack.addOrReplaceChild("left_cape_edge", CubeListBuilder.create()
                        .texOffs(48, 0).addBox(-1.0F, -8.125F, -4.0F, 2.0F, 14.0F, 5.0F)   // left_mantle_side
                        .texOffs(250, 0).addBox(-1.5F, -5.0F, -4.15F, 3.0F, 12.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_mantle_fringe
                , PartPose.offsetAndRotation(6.0F, 7.0F, -0.5F, rad(0.0F), rad(-10.0F), rad(0.0F)));

        peltBack.addOrReplaceChild("right_cape_edge", CubeListBuilder.create()
                        .texOffs(48, 0).addBox(-1.0F, -8.125F, -4.0F, 2.0F, 14.0F, 5.0F)   // right_mantle_side
                        .texOffs(250, 0).addBox(-1.5F, -5.0F, -4.15F, 3.0F, 12.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_mantle_fringe
                , PartPose.offsetAndRotation(-6.0F, 7.0F, -0.5F, rad(0.0F), rad(10.0F), rad(0.0F)));

        PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(-7.0F, -8.0F, -3.5F, 14.0F, 9.0F, 10.0F)   // hood
                        .texOffs(66, 19).addBox(-6.0F, -9.0F, -3.0F, 12.0F, 2.0F, 9.0F)   // crown
                        .texOffs(142, 31).addBox(6.0F, -4.0F, -2.4F, 4.0F, 7.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_cheek_tuft
                        .texOffs(150, 31).addBox(-10.0F, -4.0F, -2.4F, 4.0F, 7.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_cheek_tuft
                        .texOffs(158, 31).addBox(-5.0F, -2.0F, -7.5F, 10.0F, 3.0F, 4.0F)   // muzzle
                        .texOffs(94, 40).addBox(-3.0F, -3.0F, -6.5F, 6.0F, 2.0F, 3.0F)   // muzzle_bridge
                        .texOffs(182, 40).addBox(-1.5F, -2.5F, -8.3F, 3.0F, 2.0F, 1.0F)   // nose
                        .texOffs(190, 40).addBox(-5.0F, 0.0F, -7.63F, 10.0F, 3.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // hood_fangs
                        .texOffs(186, 31).addBox(5.12F, 0.0F, -7.0F, 0.0F, 3.0F, 4.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // left_side_fangs
                        .addBox(-5.12F, 0.0F, -7.0F, 0.0F, 3.0F, 4.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // right_side_fangs
                , PartPose.offset(0.0F, -12.0F, -0.5F));

        head.addOrReplaceChild("left_eye_socket", CubeListBuilder.create()
                        .texOffs(226, 19).addBox(-3F, -3.5F, -0.4F, 6.0F, 7.0F, 2.0F)   // left_brow
                        .texOffs(212, 31).addBox(-3F, -3.5F, -0.54F, 6.0F, 7.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_eye
                        .texOffs(220, 40).addBox(-3F, 2.5F, -0.56F, 6.0F, 3.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_cheek_marks
                , PartPose.offsetAndRotation(4.7F, -4.0F, -4.1F, rad(0.0F), rad(-18.0F), rad(0.0F)));

        PartDefinition leftEar = head.addOrReplaceChild("left_ear", CubeListBuilder.create()
                        .texOffs(152, 40).addBox(-1.5F, -1.0F, -1.0F, 3.0F, 2.0F, 2.0F)   // left_ear_root
                        .texOffs(112, 40).addBox(0.0F, -3.0F, -1.15F, 8.0F, 5.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_ear_sheet
                , PartPose.offsetAndRotation(6.4F, -7.2F, 1.0F, rad(0.0F), rad(-5.0F), rad(11.0F)));

        leftEar.addOrReplaceChild("left_ear_fold", CubeListBuilder.create()
                        .texOffs(8, 47).addBox(-0.5F, -2.0F, -0.05F, 4.0F, 3.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_ear_tip
                , PartPose.offsetAndRotation(5.1F, 0.0F, -1.15F, rad(18.0F), rad(0.0F), rad(0.0F)));

        head.addOrReplaceChild("right_eye_socket", CubeListBuilder.create()
                        .texOffs(226, 19).addBox(-3.0F, -3.5F, -0.4F, 6.0F, 7.0F, 2.0F)   // right_brow
                        .texOffs(224, 31).addBox(-3.0F, -3.5F, -0.54F, 6.0F, 7.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_eye
                        .texOffs(232, 40).addBox(-3.0F, 2.5F, -0.56F, 6.0F, 3.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_cheek_marks
                , PartPose.offsetAndRotation(-4.7F, -4.0F, -4.1F, rad(0.0F), rad(18.0F), rad(0.0F)));

        PartDefinition rightEar = head.addOrReplaceChild("right_ear", CubeListBuilder.create()
                        .texOffs(152, 40).addBox(-1.5F, -1.0F, -1.0F, 3.0F, 2.0F, 2.0F)   // right_ear_root
                        .texOffs(128, 40).addBox(-8F, -3.0F, -1.15F, 8.0F, 5.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_ear_sheet
                , PartPose.offsetAndRotation(-6.4F, -7.2F, 1.0F, rad(0.0F), rad(5.0F), rad(-11.0F)));

        rightEar.addOrReplaceChild("right_ear_fold", CubeListBuilder.create()
                        .texOffs(16, 47).addBox(-3.5F, -2.0F, -0.05F, 4.0F, 3.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_ear_tip
                , PartPose.offsetAndRotation(-5.1F, 0.0F, -1.15F, rad(-18.0F), rad(0.0F), rad(0.0F)));

        head.addOrReplaceChild("jaw", CubeListBuilder.create()
                        .texOffs(0, 40).addBox(-4.0F, 0.0F, -4.5F, 8.0F, 2.0F, 5.0F)   // yellow_jaw
                        .texOffs(56, 40).addBox(-3.0F, 1.0F, -4.0F, 6.0F, 2.0F, 4.0F)   // chin
                , PartPose.offset(0.0F, 1.0F, -2.5F));

        PartDefinition horn = head.addOrReplaceChild("horn", CubeListBuilder.create()
                        .texOffs(26, 40).addBox(-1.5F, -3.0F, -1.5F, 3.0F, 4.0F, 3.0F)   // horn_base
                        .texOffs(144, 40).addBox(-1.0F, -6.0F, -1.0F, 2.0F, 3.0F, 2.0F)   // horn_mid
                        .texOffs(162, 40).addBox(-0.5F, -9.0F, -0.5F, 1.0F, 3.0F, 1.0F)   // horn_high
                , PartPose.offsetAndRotation(0.0F, -8.0F, -1.3F, rad(7.0F), rad(0.0F), rad(0.0F)));

        horn.addOrReplaceChild("horn_point_a", CubeListBuilder.create()
                        .texOffs(34, 47).addBox(-0.5F, -2.0F, 0.0F, 1.0F, 2.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // horn_point_a
                , PartPose.offsetAndRotation(0.0F, -8.5F, 0.0F, rad(0.0F), rad(-45.0F), rad(0.0F)));

        horn.addOrReplaceChild("horn_point_b", CubeListBuilder.create()
                        .texOffs(34, 47).addBox(-0.5F, -2.0F, 0.0F, 1.0F, 2.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // horn_point_b
                , PartPose.offsetAndRotation(0.0F, -8.5F, 0.0F, rad(0.0F), rad(45.0F), rad(0.0F)));

        PartDefinition tail = body.addOrReplaceChild("tail", CubeListBuilder.create()
                        .texOffs(184, 0).addBox(-2.5F, -3.0F, 0.0F, 5.0F, 5.0F, 7.0F)   // tail_base
                        .texOffs(210, 40).addBox(-1.5F, -3.85F, 3.0F, 3.0F, 1.0F, 2.0F)   // tail_scute0
                , PartPose.offsetAndRotation(0.0F, 2.5F, 3.5F, rad(18.0F), rad(20.0F), rad(0.0F)));

        PartDefinition tailMid = tail.addOrReplaceChild("tail_mid", CubeListBuilder.create()
                        .texOffs(124, 19).addBox(-2.0F, -2.5F, 0.0F, 4.0F, 4.0F, 7.0F)   // tail_middle
                        .texOffs(210, 40).addBox(-1.5F, -3.35F, 2.0F, 3.0F, 1.0F, 2.0F)   // tail_scute1
                        .texOffs(0, 47).addBox(-1.0F, -3.35F, 5.5F, 2.0F, 1.0F, 2.0F)   // tail_scute2
                , PartPose.offsetAndRotation(0.0F, -0.5F, 6.0F, rad(12.0F), rad(0.0F), rad(0.0F)));

        tailMid.addOrReplaceChild("tail_tip", CubeListBuilder.create()
                        .texOffs(126, 31).addBox(-1.0F, -1.0F, 0.0F, 2.0F, 2.0F, 6.0F)   // tail_end
                        .texOffs(76, 40).addBox(0.0F, -1.0F, 5.0F, 0.0F, 2.0F, 4.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // tail_point
                        .texOffs(0, 47).addBox(-1.0F, -2.0F, 2.5F, 2.0F, 1.0F, 2.0F)   // tail_scute3
                , PartPose.offsetAndRotation(0.0F, -0.5F, 6.0F, rad(8.0F), rad(0.0F), rad(0.0F)));

        body.addOrReplaceChild("abdomen_top", CubeListBuilder.create()
                        .texOffs(110, 0).addBox(-6.0F, -5.0F, 0.0F, 12.0F, 5.0F, 8.0F)   // belly_top
                , PartPose.offsetAndRotation(0.0F, -4.0F, -6.5F, rad(-14.0F), rad(0.0F), rad(0.0F)));

        body.addOrReplaceChild("abdomen_lower", CubeListBuilder.create()
                        .texOffs(208, 0).addBox(-6.0F, 0.0F, 0.0F, 12.0F, 3.0F, 9.0F)   // belly_lower
                , PartPose.offsetAndRotation(0.0F, 1.0F, -6.5F, rad(18.0F), rad(0.0F), rad(0.0F)));

        PartDefinition leftInnerArm = body.addOrReplaceChild("left_inner_arm", CubeListBuilder.create()
                        .texOffs(194, 31).addBox(-2.6F, -0.625F, -2.0F, 5.0F, 3.0F, 4.0F)   // left_deltoid
                        .texOffs(108, 19).addBox(-1.5F, -0.5F, -2.5F, 4.0F, 7.0F, 4.0F)   // left_upper_arm_skin
                , PartPose.offsetAndRotation(5.5F, -11.5F, 0.0F, rad(90F), rad(95F), rad(47F)));

        PartDefinition leftYellowForearm = leftInnerArm.addOrReplaceChild("left_yellow_forearm", CubeListBuilder.create()
                        .texOffs(190, 19).addBox(-2.0F, -1.0F, -2.0F, 4.0F, 6.0F, 4.0F)   // left_forearm_skin
                , PartPose.offsetAndRotation(0.5F, 6.0F, -0.5F, rad(-16.0F), rad(0.0F), rad(6.0F)));

        PartDefinition leftYellowHandJoint = leftYellowForearm.addOrReplaceChild("left_yellow_hand_joint", CubeListBuilder.create()
                        .texOffs(38, 40).addBox(-2.5F, -1.0F, -3.0F, 5.0F, 3.0F, 4.0F)   // left_palm
                        .texOffs(24, 47).addBox(-1.75F, -0.5F, -3.75F, 4.0F, 2.0F, 1.0F)   // left_curled_fingers
                        .texOffs(36, 47).addBox(-1.75F, 1.5F, -3.25F, 4.0F, 1.0F, 1.0F)   // left_finger_tips
                        .texOffs(170, 40).addBox(-2.65F, -1.75F, -4.0F, 2.0F, 2.0F, 2.0F)   // left_thumb
                , PartPose.offset(0.0F, 5.0F, 0.0F));

        PartDefinition leftPeltGrip = leftYellowHandJoint.addOrReplaceChild("left_pelt_grip", CubeListBuilder.create()
                        .texOffs(0, 31).addBox(-3.5F, -0.875F, -0.25F, 7.0F, 4.0F, 5.0F)   // left_coat_paw
                , PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition leftPeltClaw0 = leftPeltGrip.addOrReplaceChild("left_pelt_claw0", CubeListBuilder.create(), PartPose.offsetAndRotation(-2.4F, 2.5F, 1.0F, rad(-12.0F), rad(0.0F), rad(0.0F)));

        leftPeltClaw0.addOrReplaceChild("left_pelt_nail0_a", CubeListBuilder.create()
                        .texOffs(178, 40).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_pelt_nail0_a
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(-30.0F), rad(0.0F)));

        leftPeltClaw0.addOrReplaceChild("left_pelt_nail0_b", CubeListBuilder.create()
                        .texOffs(178, 40).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_pelt_nail0_b
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(30.0F), rad(0.0F)));

        PartDefinition leftPeltClaw1 = leftPeltGrip.addOrReplaceChild("left_pelt_claw1", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 2.5F, 1.0F, rad(-12.0F), rad(0.0F), rad(0.0F)));

        leftPeltClaw1.addOrReplaceChild("left_pelt_nail1_a", CubeListBuilder.create()
                        .texOffs(178, 40).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_pelt_nail1_a
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(-30.0F), rad(0.0F)));

        leftPeltClaw1.addOrReplaceChild("left_pelt_nail1_b", CubeListBuilder.create()
                        .texOffs(178, 40).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_pelt_nail1_b
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(30.0F), rad(0.0F)));

        PartDefinition leftPeltClaw2 = leftPeltGrip.addOrReplaceChild("left_pelt_claw2", CubeListBuilder.create(), PartPose.offsetAndRotation(2.4F, 2.5F, 1.0F, rad(-12.0F), rad(0.0F), rad(0.0F)));

        leftPeltClaw2.addOrReplaceChild("left_pelt_nail2_a", CubeListBuilder.create()
                        .texOffs(178, 40).addBox(-1F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_pelt_nail2_a
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(-30.0F), rad(0.0F)));

        leftPeltClaw2.addOrReplaceChild("left_pelt_nail2_b", CubeListBuilder.create()
                        .texOffs(178, 40).addBox(-1F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_pelt_nail2_b
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(30.0F), rad(0.0F)));

        leftYellowForearm.addOrReplaceChild("left_forearm", CubeListBuilder.create()
                        .texOffs(206, 19).addBox(-3.0F, -0.5F, 1.0F, 6.0F, 6.0F, 4.0F)   // left_coat_lower
                , PartPose.offset(0.0F, 0.0F, 0.0F));

        leftInnerArm.addOrReplaceChild("left_arm", CubeListBuilder.create()
                        .texOffs(0, 19).addBox(-2.5F, 0.375F, 0.5F, 6.0F, 6.0F, 4.0F)   // left_coat_upper
                , PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition rightInnerArm = body.addOrReplaceChild("right_inner_arm", CubeListBuilder.create()
                        .texOffs(194, 31).addBox(-2.4F, -0.625F, -2.0F, 5.0F, 3.0F, 4.0F)   // right_deltoid
                        .texOffs(108, 19).addBox(-2.5F, -0.5F, -2.5F, 4.0F, 7.0F, 4.0F)   // right_upper_arm_skin
                , PartPose.offsetAndRotation(-5.5F, -11.5F, 0.0F, rad(90.0001F), rad(-95F), rad(-47.0001F)));

        PartDefinition rightYellowForearm = rightInnerArm.addOrReplaceChild("right_yellow_forearm", CubeListBuilder.create()
                        .texOffs(190, 19).addBox(-2.0F, -1.0F, -2.0F, 4.0F, 6.0F, 4.0F)   // right_forearm_skin
                , PartPose.offsetAndRotation(-0.5F, 6.0F, -0.5F, rad(-16.0F), rad(0.0F), rad(-6.0F)));

        PartDefinition rightYellowHandJoint = rightYellowForearm.addOrReplaceChild("right_yellow_hand_joint", CubeListBuilder.create()
                        .texOffs(38, 40).addBox(-2.5F, -1.0F, -3.0F, 5.0F, 3.0F, 4.0F)   // right_palm
                        .texOffs(24, 47).addBox(-2.25F, -0.5F, -3.75F, 4.0F, 2.0F, 1.0F)   // right_curled_fingers
                        .texOffs(36, 47).addBox(-2.25F, 1.5F, -3.25F, 4.0F, 1.0F, 1.0F)   // right_finger_tips
                        .texOffs(170, 40).addBox(0.65F, -1.75F, -4.0F, 2.0F, 2.0F, 2.0F)   // right_thumb
                , PartPose.offset(0.0F, 5.0F, 0.0F));

        PartDefinition rightPeltGrip = rightYellowHandJoint.addOrReplaceChild("right_pelt_grip", CubeListBuilder.create()
                        .texOffs(0, 31).addBox(-3.5F, -0.875F, -0.25F, 7.0F, 4.0F, 5.0F)   // right_coat_paw
                , PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition rightPeltClaw0 = rightPeltGrip.addOrReplaceChild("right_pelt_claw0", CubeListBuilder.create(), PartPose.offsetAndRotation(-2.4F, 2.5F, 1.0F, rad(-12.0F), rad(0.0F), rad(0.0F)));

        rightPeltClaw0.addOrReplaceChild("right_pelt_nail0_a", CubeListBuilder.create()
                        .texOffs(178, 40).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_pelt_nail0_a
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(-30.0F), rad(0.0F)));

        rightPeltClaw0.addOrReplaceChild("right_pelt_nail0_b", CubeListBuilder.create()
                        .texOffs(178, 40).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_pelt_nail0_b
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(30.0F), rad(0.0F)));

        PartDefinition rightPeltClaw1 = rightPeltGrip.addOrReplaceChild("right_pelt_claw1", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 2.5F, 1.0F, rad(-12.0F), rad(0.0F), rad(0.0F)));

        rightPeltClaw1.addOrReplaceChild("right_pelt_nail1_a", CubeListBuilder.create()
                        .texOffs(178, 40).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_pelt_nail1_a
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(-30.0F), rad(0.0F)));

        rightPeltClaw1.addOrReplaceChild("right_pelt_nail1_b", CubeListBuilder.create()
                        .texOffs(178, 40).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_pelt_nail1_b
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(30.0F), rad(0.0F)));

        PartDefinition rightPeltClaw2 = rightPeltGrip.addOrReplaceChild("right_pelt_claw2", CubeListBuilder.create(), PartPose.offsetAndRotation(2.4F, 2.5F, 1.0F, rad(-12.0F), rad(0.0F), rad(0.0F)));

        rightPeltClaw2.addOrReplaceChild("right_pelt_nail2_a", CubeListBuilder.create()
                        .texOffs(178, 40).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_pelt_nail2_a
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(-30.0F), rad(0.0F)));

        rightPeltClaw2.addOrReplaceChild("right_pelt_nail2_b", CubeListBuilder.create()
                        .texOffs(178, 40).addBox(-1.0F, 0.0F, 0.0F, 2.0F, 4.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_pelt_nail2_b
                , PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, rad(0.0F), rad(30.0F), rad(0.0F)));

        rightYellowForearm.addOrReplaceChild("right_forearm", CubeListBuilder.create()
                        .texOffs(206, 19).addBox(-3.0F, -0.5F, 1.0F, 6.0F, 6.0F, 4.0F)   // right_coat_lower
                , PartPose.offset(0.0F, 0.0F, 0.0F));

        rightInnerArm.addOrReplaceChild("right_arm", CubeListBuilder.create()
                        .texOffs(0, 19).addBox(-3.5F, 0.375F, 0.5F, 6.0F, 6.0F, 4.0F)   // right_coat_upper
                , PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition leftLeg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                        .texOffs(46, 19).addBox(-2.0F, 1.0F, -2.0F, 5.0F, 6.0F, 5.0F)   // left_haunch
                , PartPose.offset(8.0F, 12.5F, 0.5F));

        PartDefinition leftShin = leftLeg.addOrReplaceChild("left_shin", CubeListBuilder.create()
                        .texOffs(86, 31).addBox(-1.875F, -1.0F, -1.75F, 4.0F, 4.0F, 4.0F)   // left_calf
                , PartPose.offset(0.0F, 6.5F, 0.0F));

        leftShin.addOrReplaceChild("left_foot", CubeListBuilder.create()
                        .texOffs(102, 31).addBox(-3.0F, 0.0F, -6.0F, 6.0F, 2.0F, 6.0F)   // left_foot_pad
                        .texOffs(244, 40).addBox(-2.5F, 0.25F, -7.0F, 1.0F, 1.0F, 2.0F)   // left_toe_root0
                        .texOffs(166, 40).addBox(-2.0F, -0.5F, -8.0F, 0.0F, 2.0F, 2.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // left_toe0
                        .texOffs(244, 40).addBox(-0.5F, 0.25F, -7.0F, 1.0F, 1.0F, 2.0F)   // left_toe_root1
                        .texOffs(166, 40).addBox(0.0F, -0.5F, -8.0F, 0.0F, 2.0F, 2.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // left_toe1
                        .texOffs(244, 40).addBox(1.5F, 0.25F, -7.0F, 1.0F, 1.0F, 2.0F)   // left_toe_root2
                        .texOffs(166, 40).addBox(2.0F, -0.5F, -8.0F, 0.0F, 2.0F, 2.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // left_toe2
                , PartPose.offsetAndRotation(0.0F, 3.0F, 0.0F, rad(0.0F), rad(-6.0F), rad(0.0F)));

        PartDefinition rightLeg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                        .texOffs(46, 19).addBox(-3.0F, 1.0F, -2.0F, 5.0F, 6.0F, 5.0F)   // right_haunch
                , PartPose.offset(-8.0F, 12.5F, 0.5F));

        PartDefinition rightShin = rightLeg.addOrReplaceChild("right_shin", CubeListBuilder.create()
                        .texOffs(86, 31).addBox(-2.125F, -1.0F, -1.75F, 4.0F, 4.0F, 4.0F)   // right_calf
                , PartPose.offset(0.0F, 6.5F, 0.0F));

        rightShin.addOrReplaceChild("right_foot", CubeListBuilder.create()
                        .texOffs(102, 31).addBox(-3.0F, 0.0F, -6.0F, 6.0F, 2.0F, 6.0F)   // right_foot_pad
                        .texOffs(244, 40).addBox(-2.5F, 0.25F, -7.0F, 1.0F, 1.0F, 2.0F)   // right_toe_root0
                        .texOffs(166, 40).addBox(-2.0F, -0.5F, -8.0F, 0.0F, 2.0F, 2.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // right_toe0
                        .texOffs(244, 40).addBox(-0.5F, 0.25F, -7.0F, 1.0F, 1.0F, 2.0F)   // right_toe_root1
                        .texOffs(166, 40).addBox(0.0F, -0.5F, -8.0F, 0.0F, 2.0F, 2.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // right_toe1
                        .texOffs(244, 40).addBox(1.5F, 0.25F, -7.0F, 1.0F, 1.0F, 2.0F)   // right_toe_root2
                        .texOffs(166, 40).addBox(2.0F, -0.5F, -8.0F, 0.0F, 2.0F, 2.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // right_toe2
                , PartPose.offsetAndRotation(0.0F, 3.0F, 0.0F, rad(0.0F), rad(6.0F), rad(0.0F)));
        return LayerDefinition.create(mesh, 256, 64);
    }

    @Override
    public void setupAnim(DigimonRenderState state) {
        super.setupAnim(state);
        float motion = Mth.clamp(state.walkAnimationSpeed * 2.5F, 0.0F, 1.0F);
        float running = Mth.clamp(state.runAnimationAmount, 0.0F, 1.0F);
        this.animations.get("walk").applyWalk(state.walkAnimationPos, motion * (1.0F - running), 2.5F, 1.0F);
        this.animations.get("run").applyWalk(state.walkAnimationPos, motion * running, 1.25F, 1.0F);
        if (motion > 0.0F && motion < 1.0F) {
            // Carry the hands clear before the thighs start stepping; reverse on stopping.
            float remaining = 1.0F - motion;
            float armFactor = (1.0F - remaining * remaining * remaining) / motion;
            carryArm(leftInnerArm, armFactor);
            carryArm(rightInnerArm, armFactor);
            carryArm(leftYellowForearm, armFactor);
            carryArm(rightYellowForearm, armFactor);
            float clearance = 10.0F * Mth.sin(Mth.PI * motion) * Mth.DEG_TO_RAD;
            leftInnerArm.zRot -= clearance;
            rightInnerArm.zRot += clearance;
        }
        if (motion > 0.0F && (motion < 1.0F || running > 0.0F && running < 1.0F)) {
            keepTransitionFeetAboveGround();
        }
        this.head.yRot += Mth.clamp(state.yRot, -25.0F, 25.0F) * Mth.DEG_TO_RAD;
        this.head.xRot += Mth.clamp(state.xRot, -15.0F, 15.0F) * Mth.DEG_TO_RAD;
    }

    private static void carryArm(ModelPart arm, float factor) {
        PartPose idle = arm.getInitialPose();
        arm.xRot = idle.xRot() + (arm.xRot - idle.xRot()) * factor;
        arm.yRot = idle.yRot() + (arm.yRot - idle.yRot()) * factor;
        arm.zRot = idle.zRot() + (arm.zRot - idle.zRot()) * factor;
    }

    // Blending rotations is not a linear blend of foot positions. Correct only the
    // transition's penetration, preserving the native cycle's planted/airborne poses.
    private void keepTransitionFeetAboveGround() {
        PoseStack pose = new PoseStack();
        root.translateAndRotate(pose);
        float[] lowest = {1.5F}; // Model ground is y=24 pixels; Y points down.
        pose.pushPose();
        leftLeg.translateAndRotate(pose);
        leftShin.translateAndRotate(pose);
        leftFoot.getExtentsForGui(pose, p -> lowest[0] = Math.max(lowest[0], p.y()));
        pose.popPose();
        rightLeg.translateAndRotate(pose);
        rightShin.translateAndRotate(pose);
        rightFoot.getExtentsForGui(pose, p -> lowest[0] = Math.max(lowest[0], p.y()));
        root.y -= (lowest[0] - 1.5F) * 16.0F;
    }

    private static float rad(float degrees) {
        return degrees * Mth.DEG_TO_RAD;
    }
}
