package com.digicube.fabric.client.model;

import com.digicube.Constants;
import com.digicube.fabric.client.render.DigimonRenderState;
import net.minecraft.client.animation.KeyframeAnimation;

import java.util.HashMap;
import java.util.Map;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.util.Mth;

/**
 * GarurumonModel -- GENERATED by the DigiCube model harness from digimon/garurumon.py.
 * Geometry matches the Blender rig bone for bone; edit the spec and regenerate rather
 * than hand-tuning coordinates here. Exported from approved native Blender files; regenerate with export_garurumon_release.py.
 *
 * Vanilla model space: Y down, ground at y=24, front at -Z. Atlas 256x128.
 */
public class GarurumonModel extends EntityModel<DigimonRenderState> implements AnimatedRiderModel {

    private static final net.minecraft.resources.Identifier GEOMETRY = Constants.id("models/entity/garurumon.mesh.json");

    /** Client model layer used when baking this species. */
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Constants.id("garurumon"), "main");

    private final ModelPart body;
    private final ModelPart chest;
    private final ModelPart pelvis;
    private final ModelPart neck;
    private final ModelPart head;
    private final ModelPart jaw;
    private final ModelPart leftEyeSocket;
    private final ModelPart leftEar;
    private final ModelPart leftEarTip;
    private final ModelPart leftCheekMass;
    private final ModelPart leftCheek0;
    private final ModelPart leftCheek1;
    private final ModelPart leftCheek2;
    private final ModelPart leftCheek3;
    private final ModelPart leftCheek4;
    private final ModelPart leftTemple;
    private final ModelPart leftRuffProfile0;
    private final ModelPart leftRuffProfile1;
    private final ModelPart leftRuffProfile2;
    private final ModelPart leftShoulderQuill0;
    private final ModelPart leftHipQuill0;
    private final ModelPart leftShoulderQuill1;
    private final ModelPart leftHipQuill1;
    private final ModelPart leftShoulderQuill2;
    private final ModelPart leftHipQuill2;
    private final ModelPart leftBib0;
    private final ModelPart leftBib1;
    private final ModelPart leftBib2;
    private final ModelPart leftUpperTeeth;
    private final ModelPart leftArm;
    private final ModelPart leftForearm;
    private final ModelPart leftFrontPaw;
    private final ModelPart leftLeg;
    private final ModelPart leftShin;
    private final ModelPart leftHock;
    private final ModelPart leftRearPaw;
    private final ModelPart leftUpperFore;
    private final ModelPart leftLowerFore;
    private final ModelPart leftThigh;
    private final ModelPart leftCalf;
    private final ModelPart leftMetatarsal;
    private final ModelPart leftFrontClaw0;
    private final ModelPart leftFrontClaw1;
    private final ModelPart leftFrontClaw2;
    private final ModelPart leftFrontClaw3;
    private final ModelPart leftRearClaw0;
    private final ModelPart leftRearClaw1;
    private final ModelPart leftRearClaw2;
    private final ModelPart leftRearClaw3;
    private final ModelPart leftElbowTuft;
    private final ModelPart rightEyeSocket;
    private final ModelPart rightEar;
    private final ModelPart rightEarTip;
    private final ModelPart rightCheekMass;
    private final ModelPart rightCheek0;
    private final ModelPart rightCheek1;
    private final ModelPart rightCheek2;
    private final ModelPart rightCheek3;
    private final ModelPart rightCheek4;
    private final ModelPart rightTemple;
    private final ModelPart rightRuffProfile0;
    private final ModelPart rightRuffProfile1;
    private final ModelPart rightRuffProfile2;
    private final ModelPart rightShoulderQuill0;
    private final ModelPart rightHipQuill0;
    private final ModelPart rightShoulderQuill1;
    private final ModelPart rightHipQuill1;
    private final ModelPart rightShoulderQuill2;
    private final ModelPart rightHipQuill2;
    private final ModelPart rightBib0;
    private final ModelPart rightBib1;
    private final ModelPart rightBib2;
    private final ModelPart rightUpperTeeth;
    private final ModelPart rightArm;
    private final ModelPart rightForearm;
    private final ModelPart rightFrontPaw;
    private final ModelPart rightLeg;
    private final ModelPart rightShin;
    private final ModelPart rightHock;
    private final ModelPart rightRearPaw;
    private final ModelPart rightUpperFore;
    private final ModelPart rightLowerFore;
    private final ModelPart rightThigh;
    private final ModelPart rightCalf;
    private final ModelPart rightMetatarsal;
    private final ModelPart rightFrontClaw0;
    private final ModelPart rightFrontClaw1;
    private final ModelPart rightFrontClaw2;
    private final ModelPart rightFrontClaw3;
    private final ModelPart rightRearClaw0;
    private final ModelPart rightRearClaw1;
    private final ModelPart rightRearClaw2;
    private final ModelPart rightRearClaw3;
    private final ModelPart rightElbowTuft;
    private final ModelPart frontUpperTeeth;
    private final ModelPart tail00;
    private final ModelPart tail00Section;
    private final ModelPart tail01;
    private final ModelPart tail01Section;
    private final ModelPart tail02;
    private final ModelPart tail02Section;
    private final ModelPart tail03;
    private final ModelPart tail03Section;
    private final ModelPart tail04;
    private final ModelPart tail04Section;
    private final ModelPart tail05;
    private final ModelPart tail05Section;
    private final ModelPart tail06;
    private final ModelPart tail06Section;
    private final ModelPart tail07;
    private final ModelPart tail07Section;
    private final ModelPart tail08;
    private final ModelPart tail08Section;
    private final ModelPart tail09;
    private final ModelPart tail09Section;
    private final ModelPart tail10;
    private final ModelPart tail10Section;
    private final ModelPart tail11;
    private final ModelPart tail11Section;
    private final ModelPart tailTip;
    private final ModelPart riderSeat;

    /** Baked once per model instance; keyed by harness animation name. */
    private final Map<String, KeyframeAnimation> animations = new HashMap<>();

    /**
     * Creates the model and binds its animation bones.
     * @param root baked root from this model's layer
     */
    public GarurumonModel(ModelPart root) {
        super(NativeModelGeometry.apply(root, GEOMETRY));
        this.body = root.getChild("body");
        this.chest = root.getChild("body").getChild("chest");
        this.pelvis = root.getChild("body").getChild("pelvis");
        this.neck = root.getChild("body").getChild("chest").getChild("neck");
        this.head = root.getChild("body").getChild("chest").getChild("neck").getChild("head");
        this.jaw = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("jaw");
        this.leftEyeSocket = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("left_eye_socket");
        this.leftEar = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("left_ear");
        this.leftEarTip = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("left_ear").getChild("left_ear_tip");
        this.leftCheekMass = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("left_cheek_mass");
        this.leftCheek0 = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("left_cheek_0");
        this.leftCheek1 = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("left_cheek_1");
        this.leftCheek2 = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("left_cheek_2");
        this.leftCheek3 = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("left_cheek_3");
        this.leftCheek4 = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("left_cheek_4");
        this.leftTemple = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("left_temple");
        this.leftRuffProfile0 = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("left_ruff_profile_0");
        this.leftRuffProfile1 = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("left_ruff_profile_1");
        this.leftRuffProfile2 = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("left_ruff_profile_2");
        this.leftShoulderQuill0 = root.getChild("body").getChild("chest").getChild("left_shoulder_quill_0");
        this.leftHipQuill0 = root.getChild("body").getChild("pelvis").getChild("left_hip_quill_0");
        this.leftShoulderQuill1 = root.getChild("body").getChild("chest").getChild("left_shoulder_quill_1");
        this.leftHipQuill1 = root.getChild("body").getChild("pelvis").getChild("left_hip_quill_1");
        this.leftShoulderQuill2 = root.getChild("body").getChild("chest").getChild("left_shoulder_quill_2");
        this.leftHipQuill2 = root.getChild("body").getChild("pelvis").getChild("left_hip_quill_2");
        this.leftBib0 = root.getChild("body").getChild("chest").getChild("neck").getChild("left_bib_0");
        this.leftBib1 = root.getChild("body").getChild("chest").getChild("neck").getChild("left_bib_1");
        this.leftBib2 = root.getChild("body").getChild("chest").getChild("neck").getChild("left_bib_2");
        this.leftUpperTeeth = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("left_upper_teeth");
        this.leftArm = root.getChild("body").getChild("chest").getChild("left_arm");
        this.leftForearm = root.getChild("body").getChild("chest").getChild("left_arm").getChild("left_forearm");
        this.leftFrontPaw = root.getChild("body").getChild("chest").getChild("left_arm").getChild("left_forearm").getChild("left_front_paw");
        this.leftLeg = root.getChild("body").getChild("pelvis").getChild("left_leg");
        this.leftShin = root.getChild("body").getChild("pelvis").getChild("left_leg").getChild("left_shin");
        this.leftHock = root.getChild("body").getChild("pelvis").getChild("left_leg").getChild("left_shin").getChild("left_hock");
        this.leftRearPaw = root.getChild("body").getChild("pelvis").getChild("left_leg").getChild("left_shin").getChild("left_hock").getChild("left_rear_paw");
        this.leftUpperFore = root.getChild("body").getChild("chest").getChild("left_arm").getChild("left_upper_fore");
        this.leftLowerFore = root.getChild("body").getChild("chest").getChild("left_arm").getChild("left_forearm").getChild("left_lower_fore");
        this.leftThigh = root.getChild("body").getChild("pelvis").getChild("left_leg").getChild("left_thigh");
        this.leftCalf = root.getChild("body").getChild("pelvis").getChild("left_leg").getChild("left_shin").getChild("left_calf");
        this.leftMetatarsal = root.getChild("body").getChild("pelvis").getChild("left_leg").getChild("left_shin").getChild("left_hock").getChild("left_metatarsal");
        this.leftFrontClaw0 = root.getChild("body").getChild("chest").getChild("left_arm").getChild("left_forearm").getChild("left_front_paw").getChild("left_front_claw_0");
        this.leftFrontClaw1 = root.getChild("body").getChild("chest").getChild("left_arm").getChild("left_forearm").getChild("left_front_paw").getChild("left_front_claw_1");
        this.leftFrontClaw2 = root.getChild("body").getChild("chest").getChild("left_arm").getChild("left_forearm").getChild("left_front_paw").getChild("left_front_claw_2");
        this.leftFrontClaw3 = root.getChild("body").getChild("chest").getChild("left_arm").getChild("left_forearm").getChild("left_front_paw").getChild("left_front_claw_3");
        this.leftRearClaw0 = root.getChild("body").getChild("pelvis").getChild("left_leg").getChild("left_shin").getChild("left_hock").getChild("left_rear_paw").getChild("left_rear_claw_0");
        this.leftRearClaw1 = root.getChild("body").getChild("pelvis").getChild("left_leg").getChild("left_shin").getChild("left_hock").getChild("left_rear_paw").getChild("left_rear_claw_1");
        this.leftRearClaw2 = root.getChild("body").getChild("pelvis").getChild("left_leg").getChild("left_shin").getChild("left_hock").getChild("left_rear_paw").getChild("left_rear_claw_2");
        this.leftRearClaw3 = root.getChild("body").getChild("pelvis").getChild("left_leg").getChild("left_shin").getChild("left_hock").getChild("left_rear_paw").getChild("left_rear_claw_3");
        this.leftElbowTuft = root.getChild("body").getChild("chest").getChild("left_arm").getChild("left_elbow_tuft");
        this.rightEyeSocket = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("right_eye_socket");
        this.rightEar = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("right_ear");
        this.rightEarTip = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("right_ear").getChild("right_ear_tip");
        this.rightCheekMass = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("right_cheek_mass");
        this.rightCheek0 = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("right_cheek_0");
        this.rightCheek1 = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("right_cheek_1");
        this.rightCheek2 = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("right_cheek_2");
        this.rightCheek3 = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("right_cheek_3");
        this.rightCheek4 = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("right_cheek_4");
        this.rightTemple = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("right_temple");
        this.rightRuffProfile0 = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("right_ruff_profile_0");
        this.rightRuffProfile1 = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("right_ruff_profile_1");
        this.rightRuffProfile2 = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("right_ruff_profile_2");
        this.rightShoulderQuill0 = root.getChild("body").getChild("chest").getChild("right_shoulder_quill_0");
        this.rightHipQuill0 = root.getChild("body").getChild("pelvis").getChild("right_hip_quill_0");
        this.rightShoulderQuill1 = root.getChild("body").getChild("chest").getChild("right_shoulder_quill_1");
        this.rightHipQuill1 = root.getChild("body").getChild("pelvis").getChild("right_hip_quill_1");
        this.rightShoulderQuill2 = root.getChild("body").getChild("chest").getChild("right_shoulder_quill_2");
        this.rightHipQuill2 = root.getChild("body").getChild("pelvis").getChild("right_hip_quill_2");
        this.rightBib0 = root.getChild("body").getChild("chest").getChild("neck").getChild("right_bib_0");
        this.rightBib1 = root.getChild("body").getChild("chest").getChild("neck").getChild("right_bib_1");
        this.rightBib2 = root.getChild("body").getChild("chest").getChild("neck").getChild("right_bib_2");
        this.rightUpperTeeth = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("right_upper_teeth");
        this.rightArm = root.getChild("body").getChild("chest").getChild("right_arm");
        this.rightForearm = root.getChild("body").getChild("chest").getChild("right_arm").getChild("right_forearm");
        this.rightFrontPaw = root.getChild("body").getChild("chest").getChild("right_arm").getChild("right_forearm").getChild("right_front_paw");
        this.rightLeg = root.getChild("body").getChild("pelvis").getChild("right_leg");
        this.rightShin = root.getChild("body").getChild("pelvis").getChild("right_leg").getChild("right_shin");
        this.rightHock = root.getChild("body").getChild("pelvis").getChild("right_leg").getChild("right_shin").getChild("right_hock");
        this.rightRearPaw = root.getChild("body").getChild("pelvis").getChild("right_leg").getChild("right_shin").getChild("right_hock").getChild("right_rear_paw");
        this.rightUpperFore = root.getChild("body").getChild("chest").getChild("right_arm").getChild("right_upper_fore");
        this.rightLowerFore = root.getChild("body").getChild("chest").getChild("right_arm").getChild("right_forearm").getChild("right_lower_fore");
        this.rightThigh = root.getChild("body").getChild("pelvis").getChild("right_leg").getChild("right_thigh");
        this.rightCalf = root.getChild("body").getChild("pelvis").getChild("right_leg").getChild("right_shin").getChild("right_calf");
        this.rightMetatarsal = root.getChild("body").getChild("pelvis").getChild("right_leg").getChild("right_shin").getChild("right_hock").getChild("right_metatarsal");
        this.rightFrontClaw0 = root.getChild("body").getChild("chest").getChild("right_arm").getChild("right_forearm").getChild("right_front_paw").getChild("right_front_claw_0");
        this.rightFrontClaw1 = root.getChild("body").getChild("chest").getChild("right_arm").getChild("right_forearm").getChild("right_front_paw").getChild("right_front_claw_1");
        this.rightFrontClaw2 = root.getChild("body").getChild("chest").getChild("right_arm").getChild("right_forearm").getChild("right_front_paw").getChild("right_front_claw_2");
        this.rightFrontClaw3 = root.getChild("body").getChild("chest").getChild("right_arm").getChild("right_forearm").getChild("right_front_paw").getChild("right_front_claw_3");
        this.rightRearClaw0 = root.getChild("body").getChild("pelvis").getChild("right_leg").getChild("right_shin").getChild("right_hock").getChild("right_rear_paw").getChild("right_rear_claw_0");
        this.rightRearClaw1 = root.getChild("body").getChild("pelvis").getChild("right_leg").getChild("right_shin").getChild("right_hock").getChild("right_rear_paw").getChild("right_rear_claw_1");
        this.rightRearClaw2 = root.getChild("body").getChild("pelvis").getChild("right_leg").getChild("right_shin").getChild("right_hock").getChild("right_rear_paw").getChild("right_rear_claw_2");
        this.rightRearClaw3 = root.getChild("body").getChild("pelvis").getChild("right_leg").getChild("right_shin").getChild("right_hock").getChild("right_rear_paw").getChild("right_rear_claw_3");
        this.rightElbowTuft = root.getChild("body").getChild("chest").getChild("right_arm").getChild("right_elbow_tuft");
        this.frontUpperTeeth = root.getChild("body").getChild("chest").getChild("neck").getChild("head").getChild("front_upper_teeth");
        this.tail00 = root.getChild("body").getChild("pelvis").getChild("tail_00");
        this.tail00Section = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_00_section");
        this.tail01 = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_01");
        this.tail01Section = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_01").getChild("tail_01_section");
        this.tail02 = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_01").getChild("tail_02");
        this.tail02Section = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_01").getChild("tail_02").getChild("tail_02_section");
        this.tail03 = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_01").getChild("tail_02").getChild("tail_03");
        this.tail03Section = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_01").getChild("tail_02").getChild("tail_03").getChild("tail_03_section");
        this.tail04 = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_01").getChild("tail_02").getChild("tail_03").getChild("tail_04");
        this.tail04Section = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_01").getChild("tail_02").getChild("tail_03").getChild("tail_04").getChild("tail_04_section");
        this.tail05 = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_01").getChild("tail_02").getChild("tail_03").getChild("tail_04").getChild("tail_05");
        this.tail05Section = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_01").getChild("tail_02").getChild("tail_03").getChild("tail_04").getChild("tail_05").getChild("tail_05_section");
        this.tail06 = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_01").getChild("tail_02").getChild("tail_03").getChild("tail_04").getChild("tail_05").getChild("tail_06");
        this.tail06Section = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_01").getChild("tail_02").getChild("tail_03").getChild("tail_04").getChild("tail_05").getChild("tail_06").getChild("tail_06_section");
        this.tail07 = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_01").getChild("tail_02").getChild("tail_03").getChild("tail_04").getChild("tail_05").getChild("tail_06").getChild("tail_07");
        this.tail07Section = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_01").getChild("tail_02").getChild("tail_03").getChild("tail_04").getChild("tail_05").getChild("tail_06").getChild("tail_07").getChild("tail_07_section");
        this.tail08 = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_01").getChild("tail_02").getChild("tail_03").getChild("tail_04").getChild("tail_05").getChild("tail_06").getChild("tail_07").getChild("tail_08");
        this.tail08Section = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_01").getChild("tail_02").getChild("tail_03").getChild("tail_04").getChild("tail_05").getChild("tail_06").getChild("tail_07").getChild("tail_08").getChild("tail_08_section");
        this.tail09 = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_01").getChild("tail_02").getChild("tail_03").getChild("tail_04").getChild("tail_05").getChild("tail_06").getChild("tail_07").getChild("tail_08").getChild("tail_09");
        this.tail09Section = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_01").getChild("tail_02").getChild("tail_03").getChild("tail_04").getChild("tail_05").getChild("tail_06").getChild("tail_07").getChild("tail_08").getChild("tail_09").getChild("tail_09_section");
        this.tail10 = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_01").getChild("tail_02").getChild("tail_03").getChild("tail_04").getChild("tail_05").getChild("tail_06").getChild("tail_07").getChild("tail_08").getChild("tail_09").getChild("tail_10");
        this.tail10Section = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_01").getChild("tail_02").getChild("tail_03").getChild("tail_04").getChild("tail_05").getChild("tail_06").getChild("tail_07").getChild("tail_08").getChild("tail_09").getChild("tail_10").getChild("tail_10_section");
        this.tail11 = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_01").getChild("tail_02").getChild("tail_03").getChild("tail_04").getChild("tail_05").getChild("tail_06").getChild("tail_07").getChild("tail_08").getChild("tail_09").getChild("tail_10").getChild("tail_11");
        this.tail11Section = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_01").getChild("tail_02").getChild("tail_03").getChild("tail_04").getChild("tail_05").getChild("tail_06").getChild("tail_07").getChild("tail_08").getChild("tail_09").getChild("tail_10").getChild("tail_11").getChild("tail_11_section");
        this.tailTip = root.getChild("body").getChild("pelvis").getChild("tail_00").getChild("tail_01").getChild("tail_02").getChild("tail_03").getChild("tail_04").getChild("tail_05").getChild("tail_06").getChild("tail_07").getChild("tail_08").getChild("tail_09").getChild("tail_10").getChild("tail_11").getChild("tail_tip");
        this.riderSeat = root.getChild("body").getChild("rider_seat");
        GarurumonAnimations.BY_NAME.forEach((name, definition) -> this.animations.put(name, definition.bake(root)));
    }

    /**
     * Builds the authored geometry and texture layout.
     * @return the layer to register with the client
     */
    public static LayerDefinition createBodyLayer() {
        return NativeModelGeometry.createLayer(GEOMETRY);
    }

    @Override
    public void setupAnim(DigimonRenderState state) {
        super.setupAnim(state);
        float motion = Mth.clamp(state.walkAnimationSpeed * 3.0F, 0.0F, 1.0F);
        this.animations.get("run").applyWalk(state.walkAnimationPos, motion, 0.828235294F, 1.0F);
        if (motion > 0.0F && motion < 1.0F) keepTransitionFeetAboveGround();
        if (!state.isBeingRidden) {
            this.head.yRot += Mth.clamp(state.yRot, -25.0F, 25.0F) * Mth.DEG_TO_RAD;
            this.head.xRot += Mth.clamp(state.xRot, -12.0F, 12.0F) * Mth.DEG_TO_RAD;
        }
    }


    private void keepTransitionFeetAboveGround() {
        var pose = new com.mojang.blaze3d.vertex.PoseStack();
        float[] lowest = {1.5F};
        root.visit(pose, (stack, path, index, cube) -> {
            if (path.contains("_front_paw") || path.contains("_rear_paw")) {
                for (var polygon : cube.polygons) for (var v : polygon.vertices()) {
                    var p = stack.pose().transformPosition(v.worldX(), v.worldY(), v.worldZ(), new org.joml.Vector3f());
                    lowest[0] = Math.max(lowest[0], p.y);
                }
            }
        });
        root.y -= (lowest[0] - 1.5F) * 16.0F;
    }

    @Override
    public net.minecraft.world.phys.Vec3 riderOffset(DigimonRenderState state) {
        setupAnim(state);
        var pose = new com.mojang.blaze3d.vertex.PoseStack();
        root.translateAndRotate(pose);
        body.translateAndRotate(pose);
        riderSeat.translateAndRotate(pose);
        var p = pose.last().pose().transformPosition(0, 0, 0, new org.joml.Vector3f());
        return new net.minecraft.world.phys.Vec3(p.x, 1.5F - p.y - 2.1875F, -p.z + .375F).scale(state.modelScale);
    }

    @Override
    public RiderPose riderPose() {
        return new RiderPose(-1.10F, .75F, .12F);
    }

    @Override
    public double cullingMargin() {
        return 3.0;
    }

    private static float rad(float degrees) {
        return degrees * Mth.DEG_TO_RAD;
    }
}
