package com.digicube.fabric.client.model;

import com.digicube.Constants;
import com.digicube.fabric.client.render.DigimonRenderState;
import net.minecraft.client.animation.KeyframeAnimation;

import java.util.HashMap;
import java.util.Map;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.util.Mth;

/**
 * GomamonModel -- GENERATED by the DigiCube model harness from digimon/gomamon.py.
 * Geometry matches the Blender rig bone for bone; edit the spec and regenerate rather
 * than hand-tuning coordinates here. Exported from the saved native clips by export_gomamon_release.py.
 *
 * Vanilla model space: Y down, ground at y=24, front at -Z. Atlas 128x128.
 */
public class GomamonModel extends EntityModel<DigimonRenderState> {

    private static final net.minecraft.resources.Identifier GEOMETRY = Constants.id("models/entity/gomamon.mesh.json");

    /** Client model layer used when baking this species. */
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Constants.id("gomamon"), "main");

    private final ModelPart body;
    private final ModelPart breast;
    private final ModelPart hips;
    private final ModelPart head;
    private final ModelPart leftCheek;
    private final ModelPart rightCheek;
    private final ModelPart leftEar;
    private final ModelPart leftEarTip;
    private final ModelPart rightEar;
    private final ModelPart rightEarTip;
    private final ModelPart crest;
    private final ModelPart leftCrestBlade;
    private final ModelPart rightCrestBlade;
    private final ModelPart napeFur;
    private final ModelPart leftArm;
    private final ModelPart leftHand;
    private final ModelPart leftFrontClaw0;
    private final ModelPart leftFrontClaw1;
    private final ModelPart leftFrontClaw2;
    private final ModelPart leftLeg;
    private final ModelPart leftHindClaw0;
    private final ModelPart leftHindClaw1;
    private final ModelPart leftHindClaw2;
    private final ModelPart rightArm;
    private final ModelPart rightHand;
    private final ModelPart rightFrontClaw0;
    private final ModelPart rightFrontClaw1;
    private final ModelPart rightFrontClaw2;
    private final ModelPart rightLeg;
    private final ModelPart rightHindClaw0;
    private final ModelPart rightHindClaw1;
    private final ModelPart rightHindClaw2;
    private final ModelPart tail;
    private final ModelPart tailTip;

    /** Baked once per model instance; keyed by harness animation name. */
    private final Map<String, KeyframeAnimation> animations = new HashMap<>();

    /**
     * Creates the model and binds its animation bones.
     * @param root baked root from this model's layer
     */
    public GomamonModel(ModelPart root) {
        super(NativeModelGeometry.apply(root, GEOMETRY));
        this.body = root.getChild("body");
        this.breast = root.getChild("body").getChild("breast");
        this.hips = root.getChild("body").getChild("hips");
        this.head = root.getChild("body").getChild("head");
        this.leftCheek = root.getChild("body").getChild("head").getChild("left_cheek");
        this.rightCheek = root.getChild("body").getChild("head").getChild("right_cheek");
        this.leftEar = root.getChild("body").getChild("head").getChild("left_ear");
        this.leftEarTip = root.getChild("body").getChild("head").getChild("left_ear").getChild("left_ear_tip");
        this.rightEar = root.getChild("body").getChild("head").getChild("right_ear");
        this.rightEarTip = root.getChild("body").getChild("head").getChild("right_ear").getChild("right_ear_tip");
        this.crest = root.getChild("body").getChild("head").getChild("crest");
        this.leftCrestBlade = root.getChild("body").getChild("head").getChild("crest").getChild("left_crest_blade");
        this.rightCrestBlade = root.getChild("body").getChild("head").getChild("crest").getChild("right_crest_blade");
        this.napeFur = root.getChild("body").getChild("head").getChild("nape_fur");
        this.leftArm = root.getChild("body").getChild("left_arm");
        this.leftHand = root.getChild("body").getChild("left_arm").getChild("left_hand");
        this.leftFrontClaw0 = root.getChild("body").getChild("left_arm").getChild("left_hand").getChild("left_front_claw_0");
        this.leftFrontClaw1 = root.getChild("body").getChild("left_arm").getChild("left_hand").getChild("left_front_claw_1");
        this.leftFrontClaw2 = root.getChild("body").getChild("left_arm").getChild("left_hand").getChild("left_front_claw_2");
        this.leftLeg = root.getChild("body").getChild("hips").getChild("left_leg");
        this.leftHindClaw0 = root.getChild("body").getChild("hips").getChild("left_leg").getChild("left_hind_claw_0");
        this.leftHindClaw1 = root.getChild("body").getChild("hips").getChild("left_leg").getChild("left_hind_claw_1");
        this.leftHindClaw2 = root.getChild("body").getChild("hips").getChild("left_leg").getChild("left_hind_claw_2");
        this.rightArm = root.getChild("body").getChild("right_arm");
        this.rightHand = root.getChild("body").getChild("right_arm").getChild("right_hand");
        this.rightFrontClaw0 = root.getChild("body").getChild("right_arm").getChild("right_hand").getChild("right_front_claw_0");
        this.rightFrontClaw1 = root.getChild("body").getChild("right_arm").getChild("right_hand").getChild("right_front_claw_1");
        this.rightFrontClaw2 = root.getChild("body").getChild("right_arm").getChild("right_hand").getChild("right_front_claw_2");
        this.rightLeg = root.getChild("body").getChild("hips").getChild("right_leg");
        this.rightHindClaw0 = root.getChild("body").getChild("hips").getChild("right_leg").getChild("right_hind_claw_0");
        this.rightHindClaw1 = root.getChild("body").getChild("hips").getChild("right_leg").getChild("right_hind_claw_1");
        this.rightHindClaw2 = root.getChild("body").getChild("hips").getChild("right_leg").getChild("right_hind_claw_2");
        this.tail = root.getChild("body").getChild("hips").getChild("tail");
        this.tailTip = root.getChild("body").getChild("hips").getChild("tail").getChild("tail_tip");
        GomamonAnimations.BY_NAME.forEach((name, definition) -> this.animations.put(name, definition.bake(root)));
    }

    /**
     * Builds the authored geometry and texture layout.
     * @return the layer to register with the client
     */
    public static LayerDefinition createBodyLayer() {
        return NativeModelGeometry.createLayer(GEOMETRY);
    }

    @Override
    public void setupAnim(DigimonRenderState state) {
        super.setupAnim(state);
        float water = Mth.clamp(state.swimAnimationAmount, 0.0F, 1.0F);
        water = water * water * (3.0F - 2.0F * water);
        float motion = Mth.clamp(state.walkAnimationSpeed * 10.0F, 0.0F, 1.0F);
        float power = Mth.clamp(state.swimMotionAmount, 0.0F, 1.0F);
        this.animations.get("walk").applyWalk(state.groundAnimationPhase, (1.0F-water)*motion, 1.0F, 1.0F);
        this.animations.get("swim_idle").applyWalk(state.swimAnimationPhase, water*(1.0F-power), 1.0F, 1.0F);
        this.animations.get("swim").applyWalk(state.swimAnimationPhase, water*power, 1.0F, 1.0F);
        this.body.xRot += Mth.clamp(state.xRot, -65.0F, 65.0F) * Mth.DEG_TO_RAD * water;
        this.body.zRot += state.swimBank * Mth.DEG_TO_RAD * water;
        this.head.yRot += Mth.clamp(state.yRot, -20.0F, 20.0F) * Mth.DEG_TO_RAD * (1.0F-water*.75F);
        this.head.xRot += Mth.clamp(state.xRot, -10.0F, 10.0F) * Mth.DEG_TO_RAD * (1.0F-water);
    }

    private static float rad(float degrees) {
        return degrees * Mth.DEG_TO_RAD;
    }
}
