package com.digicube.fabric.client.model;

import com.digicube.Constants;
import com.digicube.fabric.client.render.DigimonRenderState;
import net.minecraft.client.animation.KeyframeAnimation;

import java.util.HashMap;
import java.util.Map;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * GreymonModel -- GENERATED by the DigiCube model harness from digimon/greymon_body_study.py via blender/export_greymon.py.
 * Geometry matches the Blender rig bone for bone; edit the spec and regenerate rather
 * than hand-tuning coordinates here. setupAnim is a starting point and may be edited.
 *
 * Vanilla model space: Y down, ground at y=24, front at -Z. Atlas 256x256.
 */
public class GreymonModel extends EntityModel<DigimonRenderState> {

    /** Client model layer used when baking this species. */
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Constants.id("greymon"), "main");

    private final ModelPart body;
    private final ModelPart chest;
    private final ModelPart head;
    private final ModelPart nasalRidge;
    private final ModelPart jaw;
    private final ModelPart leftTemple;
    private final ModelPart leftHorn;
    private final ModelPart leftHornElbow;
    private final ModelPart leftHornTip;
    private final ModelPart rightTemple;
    private final ModelPart rightHorn;
    private final ModelPart rightHornElbow;
    private final ModelPart rightHornTip;
    private final ModelPart noseHorn;
    private final ModelPart noseTip;
    private final ModelPart leftLeg;
    private final ModelPart leftKneePad;
    private final ModelPart leftShin;
    private final ModelPart leftFoot;
    private final ModelPart leftArm;
    private final ModelPart leftForearm;
    private final ModelPart rightLeg;
    private final ModelPart rightKneePad;
    private final ModelPart rightShin;
    private final ModelPart rightFoot;
    private final ModelPart rightArm;
    private final ModelPart rightForearm;
    private final ModelPart tail;
    private final ModelPart tailMid;
    private final ModelPart tailTip;
    private final ModelPart tailEnd;
    private final ModelPart riderSeat;
    private final ModelPart leftHand;
    private final ModelPart leftUpperDigit;
    private final ModelPart leftUpperNailPlane;
    private final ModelPart leftDigit0;
    private final ModelPart leftNail0Plane;
    private final ModelPart leftDigit1;
    private final ModelPart leftNail1Plane;
    private final ModelPart rightHand;
    private final ModelPart rightUpperDigit;
    private final ModelPart rightUpperNailPlane;
    private final ModelPart rightDigit0;
    private final ModelPart rightNail0Plane;
    private final ModelPart rightDigit1;
    private final ModelPart rightNail1Plane;

    /** Baked once per model instance; keyed by harness animation name. */
    private final Map<String, KeyframeAnimation> animations = new HashMap<>();

    /**
     * Creates the model and binds its animation bones.
     * @param root baked root from this model's layer
     */
    public GreymonModel(ModelPart root) {
        super(root);
        this.body = root.getChild("body");
        this.chest = root.getChild("body").getChild("chest");
        this.head = root.getChild("body").getChild("chest").getChild("head");
        this.nasalRidge = root.getChild("body").getChild("chest").getChild("head").getChild("nasal_ridge");
        this.jaw = root.getChild("body").getChild("chest").getChild("head").getChild("jaw");
        this.leftTemple = root.getChild("body").getChild("chest").getChild("head").getChild("left_temple");
        this.leftHorn = root.getChild("body").getChild("chest").getChild("head").getChild("left_horn");
        this.leftHornElbow = root.getChild("body").getChild("chest").getChild("head").getChild("left_horn").getChild("left_horn_elbow");
        this.leftHornTip = root.getChild("body").getChild("chest").getChild("head").getChild("left_horn").getChild("left_horn_elbow").getChild("left_horn_tip");
        this.rightTemple = root.getChild("body").getChild("chest").getChild("head").getChild("right_temple");
        this.rightHorn = root.getChild("body").getChild("chest").getChild("head").getChild("right_horn");
        this.rightHornElbow = root.getChild("body").getChild("chest").getChild("head").getChild("right_horn").getChild("right_horn_elbow");
        this.rightHornTip = root.getChild("body").getChild("chest").getChild("head").getChild("right_horn").getChild("right_horn_elbow").getChild("right_horn_tip");
        this.noseHorn = root.getChild("body").getChild("chest").getChild("head").getChild("nose_horn");
        this.noseTip = root.getChild("body").getChild("chest").getChild("head").getChild("nose_horn").getChild("nose_tip");
        this.leftLeg = root.getChild("left_leg");
        this.leftKneePad = root.getChild("left_leg").getChild("left_knee_pad");
        this.leftShin = root.getChild("left_leg").getChild("left_shin");
        this.leftFoot = root.getChild("left_leg").getChild("left_shin").getChild("left_foot");
        this.leftArm = root.getChild("body").getChild("chest").getChild("left_arm");
        this.leftForearm = root.getChild("body").getChild("chest").getChild("left_arm").getChild("left_forearm");
        this.rightLeg = root.getChild("right_leg");
        this.rightKneePad = root.getChild("right_leg").getChild("right_knee_pad");
        this.rightShin = root.getChild("right_leg").getChild("right_shin");
        this.rightFoot = root.getChild("right_leg").getChild("right_shin").getChild("right_foot");
        this.rightArm = root.getChild("body").getChild("chest").getChild("right_arm");
        this.rightForearm = root.getChild("body").getChild("chest").getChild("right_arm").getChild("right_forearm");
        this.tail = root.getChild("body").getChild("tail");
        this.tailMid = root.getChild("body").getChild("tail").getChild("tail_mid");
        this.tailTip = root.getChild("body").getChild("tail").getChild("tail_mid").getChild("tail_tip");
        this.tailEnd = root.getChild("body").getChild("tail").getChild("tail_mid").getChild("tail_tip").getChild("tail_end");
        this.riderSeat = root.getChild("body").getChild("chest").getChild("head").getChild("rider_seat");
        this.leftHand = root.getChild("body").getChild("chest").getChild("left_arm").getChild("left_forearm").getChild("left_hand");
        this.leftUpperDigit = root.getChild("body").getChild("chest").getChild("left_arm").getChild("left_forearm").getChild("left_hand").getChild("left_upper_digit");
        this.leftUpperNailPlane = root.getChild("body").getChild("chest").getChild("left_arm").getChild("left_forearm").getChild("left_hand").getChild("left_upper_digit").getChild("left_upper_nail_plane");
        this.leftDigit0 = root.getChild("body").getChild("chest").getChild("left_arm").getChild("left_forearm").getChild("left_hand").getChild("left_digit0");
        this.leftNail0Plane = root.getChild("body").getChild("chest").getChild("left_arm").getChild("left_forearm").getChild("left_hand").getChild("left_digit0").getChild("left_nail0_plane");
        this.leftDigit1 = root.getChild("body").getChild("chest").getChild("left_arm").getChild("left_forearm").getChild("left_hand").getChild("left_digit1");
        this.leftNail1Plane = root.getChild("body").getChild("chest").getChild("left_arm").getChild("left_forearm").getChild("left_hand").getChild("left_digit1").getChild("left_nail1_plane");
        this.rightHand = root.getChild("body").getChild("chest").getChild("right_arm").getChild("right_forearm").getChild("right_hand");
        this.rightUpperDigit = root.getChild("body").getChild("chest").getChild("right_arm").getChild("right_forearm").getChild("right_hand").getChild("right_upper_digit");
        this.rightUpperNailPlane = root.getChild("body").getChild("chest").getChild("right_arm").getChild("right_forearm").getChild("right_hand").getChild("right_upper_digit").getChild("right_upper_nail_plane");
        this.rightDigit0 = root.getChild("body").getChild("chest").getChild("right_arm").getChild("right_forearm").getChild("right_hand").getChild("right_digit0");
        this.rightNail0Plane = root.getChild("body").getChild("chest").getChild("right_arm").getChild("right_forearm").getChild("right_hand").getChild("right_digit0").getChild("right_nail0_plane");
        this.rightDigit1 = root.getChild("body").getChild("chest").getChild("right_arm").getChild("right_forearm").getChild("right_hand").getChild("right_digit1");
        this.rightNail1Plane = root.getChild("body").getChild("chest").getChild("right_arm").getChild("right_forearm").getChild("right_hand").getChild("right_digit1").getChild("right_nail1_plane");
        GreymonAnimations.BY_NAME.forEach((name, definition) -> this.animations.put(name, definition.bake(root)));
    }

    /**
     * Builds the authored geometry and texture layout.
     * @return the layer to register with the client
     */
    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                        .texOffs(140, 0).addBox(-7.0F, -7.0F, -6.0F, 14.0F, 11.0F, 15.0F)   // haunch
                        .texOffs(0, 31).addBox(-10.0F, -15.0F, -10.0F, 20.0F, 9.0F, 17.0F)   // belly
                        .texOffs(0, 57).addBox(-8.0F, -6.0F, -10.0F, 16.0F, 4.0F, 17.0F)   // belly_front
                        .texOffs(66, 57).addBox(-8.0F, -20.0F, -10.0F, 16.0F, 5.0F, 16.0F)   // belly_upper
                        .texOffs(192, 78).addBox(-4.5F, -2.0F, -8.0F, 9.0F, 3.0F, 14.0F)   // belly_lower
                , PartPose.offset(0.0F, 2.0F, 1.0F));

        PartDefinition chest = body.addOrReplaceChild("chest", CubeListBuilder.create()
                        .texOffs(74, 31).addBox(-7.5F, -10.0F, -7.5F, 15.0F, 11.0F, 14.0F)   // chest
                        .texOffs(60, 78).addBox(-4.5F, -14.0F, -5.25F, 9.0F, 8.0F, 10.0F)   // neck
                , PartPose.offset(0.0F, -17.0F, -1.0F));

        PartDefinition head = chest.addOrReplaceChild("head", CubeListBuilder.create()
                        .texOffs(130, 57).addBox(-6.0F, -1.0F, -8.0F, 12.0F, 6.0F, 15.0F)   // skull_skin
                        .texOffs(64, 115).addBox(-5.0F, 1.0F, -9.0F, 10.0F, 6.0F, 5.0F)   // throat
                        .texOffs(184, 57).addBox(-7.0F, -10.0F, -4.0F, 14.0F, 9.0F, 12.0F)   // helmet
                        .texOffs(98, 78).addBox(-8.0F, -2.0F, -17.0F, 16.0F, 5.0F, 13.0F)   // muzzle_back
                        .texOffs(216, 115).addBox(-6.0F, -1.0F, -23.0F, 12.0F, 4.0F, 6.0F)   // muzzle
                        .texOffs(94, 115).addBox(-5.0F, -4.0F, -22.0F, 10.0F, 4.0F, 7.0F)   // nasal_boss
                        .texOffs(52, 138).addBox(8.03F, 3.0F, -16.0F, 0.0F, 3.0F, 2.0F)   // left_upper_tooth0
                        .addBox(8.03F, 3.0F, -12.0F, 0.0F, 3.0F, 2.0F)   // left_upper_tooth1
                        .addBox(8.03F, 3.0F, -8.0F, 0.0F, 3.0F, 2.0F)   // left_upper_tooth2
                        .addBox(-8.03F, 3.0F, -16.0F, 0.0F, 3.0F, 2.0F)   // right_upper_tooth0
                        .addBox(-8.03F, 3.0F, -12.0F, 0.0F, 3.0F, 2.0F)   // right_upper_tooth1
                        .addBox(-8.03F, 3.0F, -8.0F, 0.0F, 3.0F, 2.0F)   // right_upper_tooth2
                        .texOffs(128, 138).addBox(-5.0F, 3.0F, -23.03F, 2.0F, 2.0F, 0.0F)   // front_tooth0
                        .addBox(-2.0F, 3.0F, -23.03F, 2.0F, 2.0F, 0.0F)   // front_tooth1
                        .addBox(1.0F, 3.0F, -23.03F, 2.0F, 2.0F, 0.0F)   // front_tooth2
                        .addBox(4.0F, 3.0F, -23.03F, 2.0F, 2.0F, 0.0F)   // front_tooth3
                , PartPose.offset(0.0F, -15.0F, -1.0F));

        head.addOrReplaceChild("nasal_ridge", CubeListBuilder.create()
                        .texOffs(132, 31).addBox(-5.0F, -3.0F, -1.0F, 10.0F, 7.0F, 16.0F)   // ridge
                , PartPose.offsetAndRotation(0.0F, -1.0F, -16.0F, rad(25.0F), rad(0.0F), rad(0.0F)));

        head.addOrReplaceChild("jaw", CubeListBuilder.create()
                        .texOffs(144, 98).addBox(-7.0F, 0.0F, -12.0F, 14.0F, 3.0F, 12.0F)   // jaw_back
                        .texOffs(84, 128).addBox(-5.0F, 0.0F, -18.0F, 10.0F, 3.0F, 6.0F)   // jaw
                        .texOffs(128, 115).addBox(-6.0F, -1.0F, -11.0F, 12.0F, 1.0F, 10.0F)   // mouth_floor
                        .texOffs(96, 138).addBox(5.0F, -2.0F, -15.0F, 0.0F, 2.0F, 2.0F)   // left_lower_tooth0
                        .addBox(7.0F, -2.0F, -11.0F, 0.0F, 2.0F, 2.0F)   // left_lower_tooth1
                        .addBox(7.0F, -2.0F, -6.0F, 0.0F, 2.0F, 2.0F)   // left_lower_tooth2
                        .addBox(-5.0F, -2.0F, -15.0F, 0.0F, 2.0F, 2.0F)   // right_lower_tooth0
                        .addBox(-7.0F, -2.0F, -11.0F, 0.0F, 2.0F, 2.0F)   // right_lower_tooth1
                        .addBox(-7.0F, -2.0F, -6.0F, 0.0F, 2.0F, 2.0F)   // right_lower_tooth2
                , PartPose.offset(0.0F, 5.0F, -5.0F));

        head.addOrReplaceChild("left_temple", CubeListBuilder.create()
                        .texOffs(44, 115).addBox(-3.0F, -3.5F, 0.0F, 6.0F, 8.0F, 4.0F)   // left_temple
                        .texOffs(56, 138).addBox(-2.0F, -3.0F, -0.04F, 4.0F, 5.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_eye
                        .texOffs(64, 138).addBox(-3.0F, -4.5F, -0.5F, 6.0F, 1.0F, 4.0F)   // left_brow
                , PartPose.offsetAndRotation(7.0F, -6.0F, -5.0F, rad(0.0F), rad(-52.0F), rad(0.0F)));

        PartDefinition leftHorn = head.addOrReplaceChild("left_horn", CubeListBuilder.create()
                        .texOffs(196, 98).addBox(-2.0F, -8.0F, -2.0F, 4.0F, 9.0F, 4.0F)   // left_horn_root
                , PartPose.offsetAndRotation(6.5F, -9.0F, 4.0F, rad(-10.0F), rad(0.0F), rad(75.0F)));

        PartDefinition leftHornElbow = leftHorn.addOrReplaceChild("left_horn_elbow", CubeListBuilder.create()
                        .texOffs(0, 128).addBox(-1.5F, -6.0F, -1.5F, 3.0F, 7.0F, 3.0F)   // left_horn_middle
                , PartPose.offsetAndRotation(0.0F, -7.0F, 0.0F, rad(0.0F), rad(0.0F), rad(-35.0F)));

        leftHornElbow.addOrReplaceChild("left_horn_tip", CubeListBuilder.create()
                        .texOffs(128, 128).addBox(-0.5F, -5.0F, -0.5F, 1.0F, 6.0F, 1.0F)   // left_horn_tip
                , PartPose.offsetAndRotation(0.0F, -5.0F, 0.0F, rad(0.0F), rad(0.0F), rad(-28.0F)));

        head.addOrReplaceChild("right_temple", CubeListBuilder.create()
                        .texOffs(44, 115).addBox(-3.0F, -3.5F, 0.0F, 6.0F, 8.0F, 4.0F)   // right_temple
                        .texOffs(84, 138).addBox(-2.0F, -3.0F, -0.04F, 4.0F, 5.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_eye
                        .texOffs(64, 138).addBox(-3.0F, -4.5F, -0.5F, 6.0F, 1.0F, 4.0F)   // right_brow
                , PartPose.offsetAndRotation(-7.0F, -6.0F, -5.0F, rad(0.0F), rad(52.0F), rad(0.0F)));

        PartDefinition rightHorn = head.addOrReplaceChild("right_horn", CubeListBuilder.create()
                        .texOffs(196, 98).addBox(-2.0F, -8.0F, -2.0F, 4.0F, 9.0F, 4.0F)   // right_horn_root
                , PartPose.offsetAndRotation(-6.5F, -9.0F, 4.0F, rad(-10.0F), rad(0.0F), rad(-75.0F)));

        PartDefinition rightHornElbow = rightHorn.addOrReplaceChild("right_horn_elbow", CubeListBuilder.create()
                        .texOffs(0, 128).addBox(-1.5F, -6.0F, -1.5F, 3.0F, 7.0F, 3.0F)   // right_horn_middle
                , PartPose.offsetAndRotation(0.0F, -7.0F, 0.0F, rad(0.0F), rad(0.0F), rad(35.0F)));

        rightHornElbow.addOrReplaceChild("right_horn_tip", CubeListBuilder.create()
                        .texOffs(128, 128).addBox(-0.5F, -5.0F, -0.5F, 1.0F, 6.0F, 1.0F)   // right_horn_tip
                , PartPose.offsetAndRotation(0.0F, -5.0F, 0.0F, rad(0.0F), rad(0.0F), rad(28.0F)));

        PartDefinition noseHorn = head.addOrReplaceChild("nose_horn", CubeListBuilder.create()
                        .texOffs(212, 98).addBox(-2.0F, -8.0F, -2.0F, 4.0F, 9.0F, 4.0F)   // nose_root
                , PartPose.offsetAndRotation(0.0F, -4.0F, -20.0F, rad(28.0F), rad(0.0F), rad(0.0F)));

        noseHorn.addOrReplaceChild("nose_tip", CubeListBuilder.create()
                        .texOffs(116, 128).addBox(-1.5F, -6.0F, -1.5F, 3.0F, 6.0F, 3.0F)   // nose_middle
                        .texOffs(92, 138).addBox(-0.5F, -10.0F, -0.5F, 1.0F, 4.0F, 1.0F)   // nose_point
                , PartPose.offsetAndRotation(0.0F, -7.0F, 0.0F, rad(-14.0F), rad(0.0F), rad(0.0F)));

        head.addOrReplaceChild("rider_seat", CubeListBuilder.create(), PartPose.offset(0.0F, -11.0F, 3.0F));

        PartDefinition leftArm = chest.addOrReplaceChild("left_arm", CubeListBuilder.create()
                        .texOffs(96, 98).addBox(-1.0F, -1.0F, -2.0F, 6.0F, 10.0F, 6.0F)   // left_upper_arm
                , PartPose.offsetAndRotation(7.0F, -5.0F, -1.0F, rad(-18.0F), rad(0.0F), rad(-26.0F)));

        PartDefinition leftForearm = leftArm.addOrReplaceChild("left_forearm", CubeListBuilder.create()
                        .texOffs(228, 98).addBox(-2.0F, -1.0F, -2.25F, 4.0F, 8.0F, 5.0F)   // left_forearm
                , PartPose.offsetAndRotation(2.0F, 8.0F, 0.0F, rad(-37.0F), rad(0.0F), rad(0.0F)));

        PartDefinition leftHand = leftForearm.addOrReplaceChild("left_hand", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, rad(20.0F), rad(10.0F), rad(0.0F)));

        PartDefinition leftUpperDigit = leftHand.addOrReplaceChild("left_upper_digit", CubeListBuilder.create()
                        .texOffs(132, 128).addBox(-1.5F, -1.5F, -4.5F, 3.0F, 3.0F, 4.0F)   // left_upper_digit
                , PartPose.offsetAndRotation(0.548784F, 0.143696F, -0.927377F, rad(38.0F), rad(0.0F), rad(0.0F)));

        leftUpperDigit.addOrReplaceChild("left_upper_nail_plane", CubeListBuilder.create()
                        .texOffs(100, 138).addBox(-1.5F, 0.0F, -3.0F, 3.0F, 0.0F, 4.0F, java.util.Set.of(net.minecraft.core.Direction.UP))   // left_upper_nail
                , PartPose.offsetAndRotation(0.0F, 0.0F, -4.5F, rad(0.0F), rad(0.0F), rad(45.0F)));

        PartDefinition leftDigit0 = leftHand.addOrReplaceChild("left_digit0", CubeListBuilder.create()
                        .texOffs(146, 128).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 4.0F, 3.0F)   // left_digit0
                , PartPose.offsetAndRotation(-1.61511F, 0.841345F, 0.846375F, rad(-46.4983F), rad(36.5624F), rad(-3.15993F)));

        leftDigit0.addOrReplaceChild("left_nail0_plane", CubeListBuilder.create()
                        .texOffs(158, 128).addBox(0.0F, -1.0F, -1.5F, 0.0F, 4.0F, 3.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // left_nail0
                , PartPose.offsetAndRotation(0.0F, 4.0F, 0.0F, rad(0.0F), rad(45.0F), rad(0.0F)));

        PartDefinition leftDigit1 = leftHand.addOrReplaceChild("left_digit1", CubeListBuilder.create()
                        .texOffs(164, 128).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 4.0F, 3.0F)   // left_digit1
                , PartPose.offsetAndRotation(0.224225F, 1.0439F, 1.17378F, rad(-2.8982F), rad(-16.4958F), rad(1.6535F)));

        leftDigit1.addOrReplaceChild("left_nail1_plane", CubeListBuilder.create()
                        .texOffs(176, 128).addBox(0.0F, -1.0F, -1.5F, 0.0F, 4.0F, 3.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // left_nail1
                , PartPose.offsetAndRotation(0.0F, 4.0F, 0.0F, rad(0.0F), rad(45.0F), rad(0.0F)));

        PartDefinition rightArm = chest.addOrReplaceChild("right_arm", CubeListBuilder.create()
                        .texOffs(120, 98).addBox(-5.0F, -1.0F, -2.0F, 6.0F, 10.0F, 6.0F)   // right_upper_arm
                , PartPose.offsetAndRotation(-7.0F, -5.0F, -1.0F, rad(-18.0F), rad(0.0F), rad(26.0F)));

        PartDefinition rightForearm = rightArm.addOrReplaceChild("right_forearm", CubeListBuilder.create()
                        .texOffs(0, 115).addBox(-2.0F, -1.0F, -2.25F, 4.0F, 8.0F, 5.0F)   // right_forearm
                , PartPose.offsetAndRotation(-2.0F, 8.0F, 0.0F, rad(-37.0F), rad(0.0F), rad(0.0F)));

        PartDefinition rightHand = rightForearm.addOrReplaceChild("right_hand", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 6.0F, 0.0F, rad(20.0F), rad(-10.0F), rad(0.0F)));

        PartDefinition rightUpperDigit = rightHand.addOrReplaceChild("right_upper_digit", CubeListBuilder.create()
                        .texOffs(182, 128).addBox(-1.5F, -1.5F, -4.5F, 3.0F, 3.0F, 4.0F)   // right_upper_digit
                , PartPose.offsetAndRotation(-0.586833F, 0.158731F, -0.812136F, rad(38.0F), rad(0.0F), rad(0.0F)));

        rightUpperDigit.addOrReplaceChild("right_upper_nail_plane", CubeListBuilder.create()
                        .texOffs(114, 138).addBox(-1.5F, 0.0F, -3.0F, 3.0F, 0.0F, 4.0F, java.util.Set.of(net.minecraft.core.Direction.UP))   // right_upper_nail
                , PartPose.offsetAndRotation(0.0F, 0.0F, -4.5F, rad(0.0F), rad(0.0F), rad(-45.0F)));

        PartDefinition rightDigit0 = rightHand.addOrReplaceChild("right_digit0", CubeListBuilder.create()
                        .texOffs(196, 128).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 4.0F, 3.0F)   // right_digit0
                , PartPose.offsetAndRotation(1.56102F, 1.78109F, -0.255123F, rad(-40.3508F), rad(-24.4011F), rad(6.96699F)));

        rightDigit0.addOrReplaceChild("right_nail0_plane", CubeListBuilder.create()
                        .texOffs(208, 128).addBox(0.0F, -1.0F, -1.5F, 0.0F, 4.0F, 3.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // right_nail0
                , PartPose.offsetAndRotation(0.0F, 4.0F, 0.0F, rad(0.0F), rad(-45.0F), rad(0.0F)));

        PartDefinition rightDigit1 = rightHand.addOrReplaceChild("right_digit1", CubeListBuilder.create()
                        .texOffs(214, 128).addBox(-1.5F, 0.0F, -1.5F, 3.0F, 4.0F, 3.0F)   // right_digit1
                , PartPose.offsetAndRotation(-0.850345F, 1.46187F, 0.404743F, rad(-11.993F), rad(37.9363F), rad(5.0885F)));

        rightDigit1.addOrReplaceChild("right_nail1_plane", CubeListBuilder.create()
                        .texOffs(226, 128).addBox(0.0F, -1.0F, -1.5F, 0.0F, 4.0F, 3.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // right_nail1
                , PartPose.offsetAndRotation(0.0F, 4.0F, 0.0F, rad(0.0F), rad(-45.0F), rad(0.0F)));

        PartDefinition tail = body.addOrReplaceChild("tail", CubeListBuilder.create()
                        .texOffs(84, 0).addBox(-6.0F, -6.0F, -1.0F, 12.0F, 11.0F, 16.0F)   // tail
                , PartPose.offsetAndRotation(0.0F, -1.0F, 7.0F, rad(4.0F), rad(0.0F), rad(0.0F)));

        PartDefinition tailMid = tail.addOrReplaceChild("tail_mid", CubeListBuilder.create()
                        .texOffs(184, 31).addBox(-4.0F, -4.0F, -1.0F, 8.0F, 8.0F, 14.0F)   // tail_mid
                , PartPose.offsetAndRotation(0.0F, 0.0F, 14.0F, rad(16.0F), rad(0.0F), rad(0.0F)));

        PartDefinition tailTip = tailMid.addOrReplaceChild("tail_tip", CubeListBuilder.create()
                        .texOffs(156, 78).addBox(-2.5F, -2.5F, -1.0F, 5.0F, 5.0F, 13.0F)   // tail_tip
                , PartPose.offsetAndRotation(0.0F, 0.0F, 12.0F, rad(27.0F), rad(0.0F), rad(0.0F)));

        tailTip.addOrReplaceChild("tail_end", CubeListBuilder.create()
                        .texOffs(18, 115).addBox(-1.5F, -1.5F, -1.0F, 3.0F, 3.0F, 10.0F)   // tail_end
                        .texOffs(40, 138).addBox(-0.5F, -0.5F, 9.0F, 1.0F, 1.0F, 5.0F)   // tail_point
                , PartPose.offsetAndRotation(0.0F, 0.0F, 11.0F, rad(24.0F), rad(0.0F), rad(0.0F)));

        PartDefinition leftLeg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(-2.5F, -7.0F, -6.0F, 9.0F, 19.0F, 12.0F)   // left_thigh
                , PartPose.offsetAndRotation(7.5F, 1.22841F, 2.0F, rad(-20.0F), rad(0.0F), rad(0.0F)));

        leftLeg.addOrReplaceChild("left_knee_pad", CubeListBuilder.create()
                        .texOffs(172, 115).addBox(-3.0F, -3.0F, -2.0F, 7.0F, 7.0F, 4.0F)   // left_knee
                , PartPose.offsetAndRotation(1.5F, 9.0F, -6.0F, rad(20.0F), rad(0.0F), rad(0.0F)));

        PartDefinition leftShin = leftLeg.addOrReplaceChild("left_shin", CubeListBuilder.create()
                        .texOffs(0, 78).addBox(-3.5F, -1.0F, -3.0F, 7.0F, 12.0F, 8.0F)   // left_shin
                , PartPose.offsetAndRotation(2.5F, 11.0F, -3.0F, rad(34.0F), rad(0.0F), rad(0.0F)));

        leftShin.addOrReplaceChild("left_foot", CubeListBuilder.create()
                        .texOffs(0, 98).addBox(-5.0F, 0.0F, -10.0F, 11.0F, 4.0F, 13.0F)   // left_foot
                        .texOffs(232, 128).addBox(-4.5F, -0.25F, -12.0F, 2.0F, 3.0F, 3.0F)   // left_toe_base0
                        .texOffs(12, 128).addBox(-3.5F, 0.0F, -17.0F, 0.0F, 4.0F, 6.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // left_toe0
                        .texOffs(242, 128).addBox(-0.5F, -0.25F, -12.0F, 2.0F, 3.0F, 3.0F)   // left_toe_base1
                        .texOffs(24, 128).addBox(0.5F, 0.0F, -17.0F, 0.0F, 4.0F, 6.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // left_toe1
                        .texOffs(0, 138).addBox(3.5F, -0.25F, -12.0F, 2.0F, 3.0F, 3.0F)   // left_toe_base2
                        .texOffs(36, 128).addBox(4.5F, 0.0F, -17.0F, 0.0F, 4.0F, 6.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // left_toe2
                , PartPose.offsetAndRotation(0.0F, 10.0F, 1.0F, rad(-14.0F), rad(0.0F), rad(0.0F)));

        PartDefinition rightLeg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                        .texOffs(42, 0).addBox(-6.5F, -7.0F, -6.0F, 9.0F, 19.0F, 12.0F)   // right_thigh
                , PartPose.offsetAndRotation(-7.5F, 1.22841F, 2.0F, rad(-20.0F), rad(0.0F), rad(0.0F)));

        rightLeg.addOrReplaceChild("right_knee_pad", CubeListBuilder.create()
                        .texOffs(194, 115).addBox(-4.0F, -3.0F, -2.0F, 7.0F, 7.0F, 4.0F)   // right_knee
                , PartPose.offsetAndRotation(-1.5F, 9.0F, -6.0F, rad(20.0F), rad(0.0F), rad(0.0F)));

        PartDefinition rightShin = rightLeg.addOrReplaceChild("right_shin", CubeListBuilder.create()
                        .texOffs(30, 78).addBox(-3.5F, -1.0F, -3.0F, 7.0F, 12.0F, 8.0F)   // right_shin
                , PartPose.offsetAndRotation(-2.5F, 11.0F, -3.0F, rad(34.0F), rad(0.0F), rad(0.0F)));

        rightShin.addOrReplaceChild("right_foot", CubeListBuilder.create()
                        .texOffs(48, 98).addBox(-6.0F, 0.0F, -10.0F, 11.0F, 4.0F, 13.0F)   // right_foot
                        .texOffs(10, 138).addBox(2.5F, -0.25F, -12.0F, 2.0F, 3.0F, 3.0F)   // right_toe_base0
                        .texOffs(48, 128).addBox(3.5F, 0.0F, -17.0F, 0.0F, 4.0F, 6.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // right_toe0
                        .texOffs(20, 138).addBox(-1.5F, -0.25F, -12.0F, 2.0F, 3.0F, 3.0F)   // right_toe_base1
                        .texOffs(60, 128).addBox(-0.5F, 0.0F, -17.0F, 0.0F, 4.0F, 6.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // right_toe1
                        .texOffs(30, 138).addBox(-5.5F, -0.25F, -12.0F, 2.0F, 3.0F, 3.0F)   // right_toe_base2
                        .texOffs(72, 128).addBox(-4.5F, 0.0F, -17.0F, 0.0F, 4.0F, 6.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // right_toe2
                , PartPose.offsetAndRotation(0.0F, 10.0F, 1.0F, rad(-14.0F), rad(0.0F), rad(0.0F)));
        return LayerDefinition.create(mesh, 256, 256);
    }

    @Override
    public void setupAnim(DigimonRenderState state) {
        super.setupAnim(state);
        this.animations.get("walk").applyWalk(state.walkAnimationPos, state.walkAnimationSpeed, 0.9F, 2.0F);
        this.head.yRot += Mth.clamp(state.yRot, -25.0F, 25.0F) * Mth.DEG_TO_RAD;
        this.head.xRot += Mth.clamp(state.xRot, -15.0F, 15.0F) * Mth.DEG_TO_RAD;
        this.jaw.xRot += Mth.sin(state.ageInTicks * 0.07F) * 0.012F;
    }

    private static float rad(float degrees) {
        return degrees * Mth.DEG_TO_RAD;
    }
}
