package com.digicube.fabric.client.model;

import com.digicube.Constants;
import com.digicube.fabric.client.render.DigimonRenderState;
import net.minecraft.client.animation.KeyframeAnimation;

import java.util.HashMap;
import java.util.Map;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * GreymonModel -- GENERATED by the DigiCube model harness from digimon/greymon_reference.py via blender/export_greymon_reference.py.
 * Geometry matches the Blender rig bone for bone; edit the spec and regenerate rather
 * than hand-tuning coordinates here. setupAnim is a starting point and may be edited.
 *
 * Vanilla model space: Y down, ground at y=24, front at -Z. Atlas 256x256.
 */
public class GreymonModel extends EntityModel<DigimonRenderState> {

    /** Client model layer used when baking this species. */
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Constants.id("greymon"), "main");

    private final ModelPart body;
    private final ModelPart neck;
    private final ModelPart head;
    private final ModelPart leftSocket;
    private final ModelPart leftGuard;
    private final ModelPart leftHorn;
    private final ModelPart leftHornMid;
    private final ModelPart leftHornTip;
    private final ModelPart rightSocket;
    private final ModelPart rightGuard;
    private final ModelPart rightHorn;
    private final ModelPart rightHornMid;
    private final ModelPart rightHornTip;
    private final ModelPart noseHorn;
    private final ModelPart noseHornTip;
    private final ModelPart jaw;
    private final ModelPart tail;
    private final ModelPart tailMid;
    private final ModelPart tailOuter;
    private final ModelPart tailTip;
    private final ModelPart tailEnd;
    private final ModelPart leftArm;
    private final ModelPart leftForearm;
    private final ModelPart leftHand;
    private final ModelPart leftFinger0;
    private final ModelPart leftFinger1;
    private final ModelPart leftFinger2;
    private final ModelPart leftLeg;
    private final ModelPart leftThighSurface;
    private final ModelPart leftShin;
    private final ModelPart leftFoot;
    private final ModelPart rightArm;
    private final ModelPart rightForearm;
    private final ModelPart rightHand;
    private final ModelPart rightFinger0;
    private final ModelPart rightFinger1;
    private final ModelPart rightFinger2;
    private final ModelPart rightLeg;
    private final ModelPart rightThighSurface;
    private final ModelPart rightShin;
    private final ModelPart rightFoot;
    private final ModelPart riderSeat;

    /** Baked once per model instance; keyed by harness animation name. */
    private final Map<String, KeyframeAnimation> animations = new HashMap<>();

    /**
     * Creates the model and binds its animation bones.
     * @param root baked root from this model's layer
     */
    public GreymonModel(ModelPart root) {
        super(root);
        this.body = root.getChild("body");
        this.neck = root.getChild("body").getChild("neck");
        this.head = root.getChild("body").getChild("neck").getChild("head");
        this.leftSocket = root.getChild("body").getChild("neck").getChild("head").getChild("left_socket");
        this.leftGuard = root.getChild("body").getChild("neck").getChild("head").getChild("left_guard");
        this.leftHorn = root.getChild("body").getChild("neck").getChild("head").getChild("left_horn");
        this.leftHornMid = root.getChild("body").getChild("neck").getChild("head").getChild("left_horn").getChild("left_horn_mid");
        this.leftHornTip = root.getChild("body").getChild("neck").getChild("head").getChild("left_horn").getChild("left_horn_mid").getChild("left_horn_tip");
        this.rightSocket = root.getChild("body").getChild("neck").getChild("head").getChild("right_socket");
        this.rightGuard = root.getChild("body").getChild("neck").getChild("head").getChild("right_guard");
        this.rightHorn = root.getChild("body").getChild("neck").getChild("head").getChild("right_horn");
        this.rightHornMid = root.getChild("body").getChild("neck").getChild("head").getChild("right_horn").getChild("right_horn_mid");
        this.rightHornTip = root.getChild("body").getChild("neck").getChild("head").getChild("right_horn").getChild("right_horn_mid").getChild("right_horn_tip");
        this.noseHorn = root.getChild("body").getChild("neck").getChild("head").getChild("nose_horn");
        this.noseHornTip = root.getChild("body").getChild("neck").getChild("head").getChild("nose_horn").getChild("nose_horn_tip");
        this.jaw = root.getChild("body").getChild("neck").getChild("head").getChild("jaw");
        this.tail = root.getChild("body").getChild("tail");
        this.tailMid = root.getChild("body").getChild("tail").getChild("tail_mid");
        this.tailOuter = root.getChild("body").getChild("tail").getChild("tail_mid").getChild("tail_outer");
        this.tailTip = root.getChild("body").getChild("tail").getChild("tail_mid").getChild("tail_outer").getChild("tail_tip");
        this.tailEnd = root.getChild("body").getChild("tail").getChild("tail_mid").getChild("tail_outer").getChild("tail_tip").getChild("tail_end");
        this.leftArm = root.getChild("body").getChild("left_arm");
        this.leftForearm = root.getChild("body").getChild("left_arm").getChild("left_forearm");
        this.leftHand = root.getChild("body").getChild("left_arm").getChild("left_forearm").getChild("left_hand");
        this.leftFinger0 = root.getChild("body").getChild("left_arm").getChild("left_forearm").getChild("left_hand").getChild("left_finger_0");
        this.leftFinger1 = root.getChild("body").getChild("left_arm").getChild("left_forearm").getChild("left_hand").getChild("left_finger_1");
        this.leftFinger2 = root.getChild("body").getChild("left_arm").getChild("left_forearm").getChild("left_hand").getChild("left_finger_2");
        this.leftLeg = root.getChild("left_leg");
        this.leftThighSurface = root.getChild("left_leg").getChild("left_thigh_surface");
        this.leftShin = root.getChild("left_leg").getChild("left_shin");
        this.leftFoot = root.getChild("left_leg").getChild("left_shin").getChild("left_foot");
        this.rightArm = root.getChild("body").getChild("right_arm");
        this.rightForearm = root.getChild("body").getChild("right_arm").getChild("right_forearm");
        this.rightHand = root.getChild("body").getChild("right_arm").getChild("right_forearm").getChild("right_hand");
        this.rightFinger0 = root.getChild("body").getChild("right_arm").getChild("right_forearm").getChild("right_hand").getChild("right_finger_0");
        this.rightFinger1 = root.getChild("body").getChild("right_arm").getChild("right_forearm").getChild("right_hand").getChild("right_finger_1");
        this.rightFinger2 = root.getChild("body").getChild("right_arm").getChild("right_forearm").getChild("right_hand").getChild("right_finger_2");
        this.rightLeg = root.getChild("right_leg");
        this.rightThighSurface = root.getChild("right_leg").getChild("right_thigh_surface");
        this.rightShin = root.getChild("right_leg").getChild("right_shin");
        this.rightFoot = root.getChild("right_leg").getChild("right_shin").getChild("right_foot");
        this.riderSeat = root.getChild("body").getChild("neck").getChild("head").getChild("rider_seat");
        GreymonAnimations.BY_NAME.forEach((name, definition) -> this.animations.put(name, definition.bake(root)));
    }

    /**
     * Builds the authored geometry and texture layout.
     * @return the layer to register with the client
     */
    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(-9.0F, -10.0F, -9.0F, 18.0F, 13.0F, 15.0F)   // abdomen
                        .texOffs(0, 94).addBox(-8.0F, -8.0F, -11.0F, 16.0F, 9.0F, 2.0F)   // belly_volume
                        .texOffs(88, 47).addBox(-7.0F, 3.0F, -8.0F, 14.0F, 4.0F, 13.0F)   // lower_belly
                        .texOffs(0, 47).addBox(-8.0F, -15.0F, -8.0F, 16.0F, 5.0F, 13.0F)   // chest
                        .texOffs(206, 65).addBox(-7.0F, -11.0F, 4.0F, 14.0F, 11.0F, 3.0F)   // back
                , PartPose.offset(0.0F, 5.0F, 1.0F));

        PartDefinition neck = body.addOrReplaceChild("neck", CubeListBuilder.create()
                        .texOffs(0, 28).addBox(-6.0F, -9.0F, -5.0F, 12.0F, 9.0F, 10.0F)   // neck
                , PartPose.offsetAndRotation(0.0F, -12.0F, -1.0F, rad(12.0F), rad(0.0F), rad(0.0F)));

        PartDefinition head = neck.addOrReplaceChild("head", CubeListBuilder.create()
                        .texOffs(44, 28).addBox(-8.0F, -5.0F, -10.0F, 16.0F, 7.0F, 12.0F)   // cheeks
                        .texOffs(116, 0).addBox(-8.0F, -9.0F, -11.0F, 16.0F, 7.0F, 13.0F)   // skull
                        .texOffs(120, 80).addBox(-6.0F, -11.0F, -9.0F, 12.0F, 2.0F, 10.0F)   // crown
                        .texOffs(50, 80).addBox(-6.0F, -8.0F, -18.0F, 12.0F, 3.0F, 10.0F)   // bridge
                        .texOffs(0, 65).addBox(-8.0F, -5.0F, -20.0F, 16.0F, 4.0F, 11.0F)   // muzzle
                        .texOffs(0, 105).addBox(-7.0F, -5.0F, -24.0F, 14.0F, 4.0F, 4.0F)   // nose
                        .texOffs(54, 65).addBox(-6.0F, -1.0F, -22.0F, 12.0F, 1.0F, 14.0F)   // mouth_roof
                        .texOffs(144, 105).addBox(-7.0F, -1.0F, -24.0625F, 14.0F, 3.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // teeth_front
                        .texOffs(58, 47).addBox(7.5F, -1.0F, -23.0F, 0.0F, 3.0F, 15.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // left_upper_teeth
                        .addBox(-7.5F, -1.0F, -23.0F, 0.0F, 3.0F, 15.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // right_upper_teeth
                , PartPose.offsetAndRotation(0.0F, -7.0F, -2.0F, rad(-12.0F), rad(0.0F), rad(0.0F)));

        head.addOrReplaceChild("left_socket", CubeListBuilder.create()
                        .texOffs(36, 94).addBox(-4.0F, -4.0F, -1.0F, 8.0F, 8.0F, 2.0F)   // left_socket
                        .texOffs(68, 105).addBox(-3.0F, -3.0F, -1.0625F, 6.0F, 6.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_eye
                        .texOffs(122, 105).addBox(-4.0F, -4.0F, -1.5F, 8.0F, 1.0F, 3.0F)   // left_brow
                , PartPose.offsetAndRotation(7.5F, -6.0F, -10.5F, rad(0.0F), rad(-48.0F), rad(0.0F)));

        head.addOrReplaceChild("left_guard", CubeListBuilder.create()
                        .texOffs(164, 80).addBox(-2.0F, 0.0F, -4.0F, 4.0F, 2.0F, 10.0F)   // left_guard
                , PartPose.offsetAndRotation(8.0F, -2.0F, -7.0F, rad(0.0F), rad(-23.0F), rad(0.0F)));

        PartDefinition leftHorn = head.addOrReplaceChild("left_horn", CubeListBuilder.create()
                        .texOffs(56, 94).addBox(-2.0F, -5.0F, -2.0F, 4.0F, 6.0F, 4.0F)   // left_horn
                , PartPose.offsetAndRotation(7.0F, -8.0F, 0.0F, rad(-8.0F), rad(0.0F), rad(58.0F)));

        PartDefinition leftHornMid = leftHorn.addOrReplaceChild("left_horn_mid", CubeListBuilder.create()
                        .texOffs(36, 105).addBox(-1.5F, -5.0F, -1.5F, 3.0F, 5.0F, 3.0F)   // left_horn_mid
                , PartPose.offsetAndRotation(0.0F, -4.0F, 0.0F, rad(0.0F), rad(0.0F), rad(-12.0F)));

        leftHornMid.addOrReplaceChild("left_horn_tip", CubeListBuilder.create()
                        .texOffs(48, 105).addBox(-1.0F, -5.0F, -1.0F, 2.0F, 5.0F, 2.0F)   // left_horn_tip
                        .texOffs(172, 105).addBox(-0.5F, -8.0F, 0.0F, 1.0F, 3.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // left_horn_edge
                , PartPose.offsetAndRotation(0.0F, -4.0F, 0.0F, rad(0.0F), rad(0.0F), rad(-27.0F)));

        head.addOrReplaceChild("right_socket", CubeListBuilder.create()
                        .texOffs(36, 94).addBox(-4.0F, -4.0F, -1.0F, 8.0F, 8.0F, 2.0F)   // right_socket
                        .texOffs(80, 105).addBox(-3.0F, -3.0F, -1.0625F, 6.0F, 6.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_eye
                        .texOffs(122, 105).addBox(-4.0F, -4.0F, -1.5F, 8.0F, 1.0F, 3.0F)   // right_brow
                , PartPose.offsetAndRotation(-7.5F, -6.0F, -10.5F, rad(0.0F), rad(48.0F), rad(0.0F)));

        head.addOrReplaceChild("right_guard", CubeListBuilder.create()
                        .texOffs(164, 80).addBox(-2.0F, 0.0F, -4.0F, 4.0F, 2.0F, 10.0F)   // right_guard
                , PartPose.offsetAndRotation(-8.0F, -2.0F, -7.0F, rad(0.0F), rad(23.0F), rad(0.0F)));

        PartDefinition rightHorn = head.addOrReplaceChild("right_horn", CubeListBuilder.create()
                        .texOffs(56, 94).addBox(-2.0F, -5.0F, -2.0F, 4.0F, 6.0F, 4.0F)   // right_horn
                , PartPose.offsetAndRotation(-7.0F, -8.0F, 0.0F, rad(-8.0F), rad(0.0F), rad(-58.0F)));

        PartDefinition rightHornMid = rightHorn.addOrReplaceChild("right_horn_mid", CubeListBuilder.create()
                        .texOffs(36, 105).addBox(-1.5F, -5.0F, -1.5F, 3.0F, 5.0F, 3.0F)   // right_horn_mid
                , PartPose.offsetAndRotation(0.0F, -4.0F, 0.0F, rad(0.0F), rad(0.0F), rad(12.0F)));

        rightHornMid.addOrReplaceChild("right_horn_tip", CubeListBuilder.create()
                        .texOffs(48, 105).addBox(-1.0F, -5.0F, -1.0F, 2.0F, 5.0F, 2.0F)   // right_horn_tip
                        .texOffs(172, 105).addBox(-0.5F, -8.0F, 0.0F, 1.0F, 3.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // right_horn_edge
                , PartPose.offsetAndRotation(0.0F, -4.0F, 0.0F, rad(0.0F), rad(0.0F), rad(27.0F)));

        PartDefinition noseHorn = head.addOrReplaceChild("nose_horn", CubeListBuilder.create()
                        .texOffs(176, 94).addBox(-2.0F, -4.0F, -2.0F, 4.0F, 5.0F, 4.0F)   // nose_horn
                , PartPose.offsetAndRotation(0.0F, -6.0F, -19.0F, rad(27.0F), rad(0.0F), rad(0.0F)));

        noseHorn.addOrReplaceChild("nose_horn_tip", CubeListBuilder.create()
                        .texOffs(192, 94).addBox(-1.0F, -7.0F, -1.0F, 2.0F, 7.0F, 2.0F)   // nose_horn_tip
                        .texOffs(172, 105).addBox(-0.5F, -10.0F, 0.0F, 1.0F, 3.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // nose_horn_edge
                , PartPose.offsetAndRotation(0.0F, -4.0F, 0.0F, rad(-10.0F), rad(0.0F), rad(0.0F)));

        head.addOrReplaceChild("jaw", CubeListBuilder.create()
                        .texOffs(100, 28).addBox(-7.0F, 0.0F, -16.0F, 14.0F, 3.0F, 16.0F)   // jaw
                        .texOffs(0, 80).addBox(-6.0F, 3.0F, -15.0F, 12.0F, 1.0F, 13.0F)   // chin
                        .texOffs(106, 65).addBox(-6.0F, -1.0F, -15.0F, 12.0F, 1.0F, 14.0F)   // gums
                        .texOffs(72, 94).addBox(-3.0F, -2.0F, -13.0F, 6.0F, 1.0F, 9.0F)   // tongue
                        .texOffs(142, 47).addBox(6.5F, -2.0F, -15.0F, 0.0F, 2.0F, 14.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // left_lower_teeth
                        .addBox(-6.5F, -2.0F, -15.0F, 0.0F, 2.0F, 14.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // right_lower_teeth
                , PartPose.offsetAndRotation(0.0F, 1.0F, -7.0F, rad(9.0F), rad(0.0F), rad(0.0F)));

        head.addOrReplaceChild("rider_seat", CubeListBuilder.create(), PartPose.offset(0.0F, -11.0F, -2.0F));

        PartDefinition tail = body.addOrReplaceChild("tail", CubeListBuilder.create()
                        .texOffs(66, 0).addBox(-6.5F, -5.5F, -1.0F, 13.0F, 11.0F, 12.0F)   // tail
                , PartPose.offsetAndRotation(0.0F, -1.0F, 4.0F, rad(-8.0F), rad(0.0F), rad(0.0F)));

        PartDefinition tailMid = tail.addOrReplaceChild("tail_mid", CubeListBuilder.create()
                        .texOffs(160, 28).addBox(-5.0F, -4.0F, -1.0F, 10.0F, 8.0F, 11.0F)   // tail_mid
                , PartPose.offsetAndRotation(0.0F, 0.0F, 10.0F, rad(13.0F), rad(0.0F), rad(0.0F)));

        PartDefinition tailOuter = tailMid.addOrReplaceChild("tail_outer", CubeListBuilder.create()
                        .texOffs(170, 47).addBox(-3.5F, -3.0F, -1.0F, 7.0F, 6.0F, 10.0F)   // tail_outer
                , PartPose.offsetAndRotation(0.0F, 0.0F, 9.0F, rad(23.0F), rad(0.0F), rad(0.0F)));

        PartDefinition tailTip = tailOuter.addOrReplaceChild("tail_tip", CubeListBuilder.create()
                        .texOffs(94, 80).addBox(-2.0F, -2.0F, -1.0F, 4.0F, 4.0F, 9.0F)   // tail_tip
                , PartPose.offsetAndRotation(0.0F, 0.0F, 8.0F, rad(23.0F), rad(0.0F), rad(0.0F)));

        tailTip.addOrReplaceChild("tail_end", CubeListBuilder.create()
                        .texOffs(102, 94).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 8.0F)   // tail_end
                , PartPose.offsetAndRotation(0.0F, 0.0F, 7.0F, rad(15.0F), rad(0.0F), rad(0.0F)));

        PartDefinition leftArm = body.addOrReplaceChild("left_arm", CubeListBuilder.create()
                        .texOffs(158, 65).addBox(-2.0F, -1.0F, -3.0F, 6.0F, 9.0F, 6.0F)   // left_arm
                , PartPose.offsetAndRotation(9.0F, -12.0F, -2.0F, rad(0.0F), rad(0.0F), rad(-22.0F)));

        PartDefinition leftForearm = leftArm.addOrReplaceChild("left_forearm", CubeListBuilder.create()
                        .texOffs(192, 80).addBox(-2.5F, -3.0F, -7.0F, 5.0F, 5.0F, 7.0F)   // left_forearm
                , PartPose.offsetAndRotation(1.0F, 7.0F, 0.0F, rad(10.0F), rad(0.0F), rad(0.0F)));

        PartDefinition leftHand = leftForearm.addOrReplaceChild("left_hand", CubeListBuilder.create()
                        .texOffs(200, 94).addBox(-3.0F, -2.0F, -5.0F, 6.0F, 4.0F, 5.0F)   // left_hand
                , PartPose.offsetAndRotation(0.0F, -1.0F, -6.0F, rad(0.0F), rad(12.0F), rad(0.0F)));

        leftHand.addOrReplaceChild("left_finger_0", CubeListBuilder.create()
                        .texOffs(92, 105).addBox(-1.0F, -1.0F, -4.0F, 2.0F, 2.0F, 4.0F)   // left_finger_0
                        .texOffs(122, 94).addBox(0.0F, -1.0F, -7.0F, 0.0F, 5.0F, 5.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // left_finger_0_claw
                , PartPose.offsetAndRotation(-2.0F, 0.0F, -3.0F, rad(0.0F), rad(10.0F), rad(0.0F)));

        leftHand.addOrReplaceChild("left_finger_1", CubeListBuilder.create()
                        .texOffs(92, 105).addBox(-1.0F, -1.0F, -4.0F, 2.0F, 2.0F, 4.0F)   // left_finger_1
                        .texOffs(122, 94).addBox(0.0F, -1.0F, -7.0F, 0.0F, 5.0F, 5.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // left_finger_1_claw
                , PartPose.offset(0.0F, 0.0F, -3.0F));

        leftHand.addOrReplaceChild("left_finger_2", CubeListBuilder.create()
                        .texOffs(92, 105).addBox(-1.0F, -1.0F, -4.0F, 2.0F, 2.0F, 4.0F)   // left_finger_2
                        .texOffs(122, 94).addBox(0.0F, -1.0F, -7.0F, 0.0F, 5.0F, 5.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // left_finger_2_claw
                , PartPose.offsetAndRotation(2.0F, 0.0F, -3.0F, rad(0.0F), rad(-10.0F), rad(0.0F)));

        PartDefinition rightArm = body.addOrReplaceChild("right_arm", CubeListBuilder.create()
                        .texOffs(158, 65).addBox(-4.0F, -1.0F, -3.0F, 6.0F, 9.0F, 6.0F)   // right_arm
                , PartPose.offsetAndRotation(-9.0F, -12.0F, -2.0F, rad(0.0F), rad(0.0F), rad(22.0F)));

        PartDefinition rightForearm = rightArm.addOrReplaceChild("right_forearm", CubeListBuilder.create()
                        .texOffs(192, 80).addBox(-2.5F, -3.0F, -7.0F, 5.0F, 5.0F, 7.0F)   // right_forearm
                , PartPose.offsetAndRotation(-1.0F, 7.0F, 0.0F, rad(10.0F), rad(0.0F), rad(0.0F)));

        PartDefinition rightHand = rightForearm.addOrReplaceChild("right_hand", CubeListBuilder.create()
                        .texOffs(200, 94).addBox(-3.0F, -2.0F, -5.0F, 6.0F, 4.0F, 5.0F)   // right_hand
                , PartPose.offsetAndRotation(0.0F, -1.0F, -6.0F, rad(0.0F), rad(-12.0F), rad(0.0F)));

        rightHand.addOrReplaceChild("right_finger_0", CubeListBuilder.create()
                        .texOffs(92, 105).addBox(-1.0F, -1.0F, -4.0F, 2.0F, 2.0F, 4.0F)   // right_finger_0
                        .texOffs(122, 94).addBox(0.0F, -1.0F, -7.0F, 0.0F, 5.0F, 5.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // right_finger_0_claw
                , PartPose.offsetAndRotation(-2.0F, 0.0F, -3.0F, rad(0.0F), rad(10.0F), rad(0.0F)));

        rightHand.addOrReplaceChild("right_finger_1", CubeListBuilder.create()
                        .texOffs(92, 105).addBox(-1.0F, -1.0F, -4.0F, 2.0F, 2.0F, 4.0F)   // right_finger_1
                        .texOffs(122, 94).addBox(0.0F, -1.0F, -7.0F, 0.0F, 5.0F, 5.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // right_finger_1_claw
                , PartPose.offset(0.0F, 0.0F, -3.0F));

        rightHand.addOrReplaceChild("right_finger_2", CubeListBuilder.create()
                        .texOffs(92, 105).addBox(-1.0F, -1.0F, -4.0F, 2.0F, 2.0F, 4.0F)   // right_finger_2
                        .texOffs(122, 94).addBox(0.0F, -1.0F, -7.0F, 0.0F, 5.0F, 5.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // right_finger_2_claw
                , PartPose.offsetAndRotation(2.0F, 0.0F, -3.0F, rad(0.0F), rad(-10.0F), rad(0.0F)));

        PartDefinition leftLeg = root.addOrReplaceChild("left_leg", CubeListBuilder.create()
                        .texOffs(216, 80).addBox(-2.0F, 7.0F, -7.0F, 6.0F, 4.0F, 8.0F)   // left_knee
                , PartPose.offset(9.0F, 3.0F, 1.0F));

        leftLeg.addOrReplaceChild("left_thigh_surface", CubeListBuilder.create()
                        .texOffs(174, 0).addBox(-5.0F, -2.0F, -6.0F, 10.0F, 10.0F, 10.0F)   // left_leg
                        .texOffs(132, 94).addBox(-4.0F, -4.0F, -5.0F, 8.0F, 2.0F, 8.0F)   // left_haunch
                , PartPose.offsetAndRotation(1.0F, 1.0F, 0.0F, rad(-17.0F), rad(0.0F), rad(-8.0F)));

        PartDefinition leftShin = leftLeg.addOrReplaceChild("left_shin", CubeListBuilder.create()
                        .texOffs(182, 65).addBox(-3.0F, 0.0F, 0.0F, 6.0F, 9.0F, 6.0F)   // left_shin
                , PartPose.offset(1.0F, 9.0F, -4.0F));

        leftShin.addOrReplaceChild("left_foot", CubeListBuilder.create()
                        .texOffs(204, 47).addBox(-4.0F, -1.0F, -9.0F, 8.0F, 4.0F, 12.0F)   // left_foot
                        .texOffs(56, 105).addBox(-4.0F, 0.0F, -11.0F, 2.0F, 3.0F, 4.0F)   // left_toe_0
                        .texOffs(164, 94).addBox(-3.0F, -1.0F, -16.0F, 0.0F, 4.0F, 6.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // left_toeclaw_0
                        .texOffs(104, 105).addBox(-4.5F, 1.5F, -16.0F, 3.0F, 0.0F, 6.0F, java.util.Set.of(net.minecraft.core.Direction.UP))   // left_toetop_0
                        .texOffs(56, 105).addBox(-1.0F, 0.0F, -11.0F, 2.0F, 3.0F, 4.0F)   // left_toe_1
                        .texOffs(164, 94).addBox(0.0F, -1.0F, -16.0F, 0.0F, 4.0F, 6.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // left_toeclaw_1
                        .texOffs(104, 105).addBox(-1.5F, 1.5F, -16.0F, 3.0F, 0.0F, 6.0F, java.util.Set.of(net.minecraft.core.Direction.UP))   // left_toetop_1
                        .texOffs(56, 105).addBox(2.0F, 0.0F, -11.0F, 2.0F, 3.0F, 4.0F)   // left_toe_2
                        .texOffs(164, 94).addBox(3.0F, -1.0F, -16.0F, 0.0F, 4.0F, 6.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // left_toeclaw_2
                        .texOffs(104, 105).addBox(1.5F, 1.5F, -16.0F, 3.0F, 0.0F, 6.0F, java.util.Set.of(net.minecraft.core.Direction.UP))   // left_toetop_2
                , PartPose.offset(0.0F, 9.0F, 3.0F));

        PartDefinition rightLeg = root.addOrReplaceChild("right_leg", CubeListBuilder.create()
                        .texOffs(216, 80).addBox(-4.0F, 7.0F, -7.0F, 6.0F, 4.0F, 8.0F)   // right_knee
                , PartPose.offset(-9.0F, 3.0F, 1.0F));

        rightLeg.addOrReplaceChild("right_thigh_surface", CubeListBuilder.create()
                        .texOffs(174, 0).addBox(-5.0F, -2.0F, -6.0F, 10.0F, 10.0F, 10.0F)   // right_leg
                        .texOffs(132, 94).addBox(-4.0F, -4.0F, -5.0F, 8.0F, 2.0F, 8.0F)   // right_haunch
                , PartPose.offsetAndRotation(-1.0F, 1.0F, 0.0F, rad(-17.0F), rad(0.0F), rad(8.0F)));

        PartDefinition rightShin = rightLeg.addOrReplaceChild("right_shin", CubeListBuilder.create()
                        .texOffs(182, 65).addBox(-3.0F, 0.0F, 0.0F, 6.0F, 9.0F, 6.0F)   // right_shin
                , PartPose.offset(-1.0F, 9.0F, -4.0F));

        rightShin.addOrReplaceChild("right_foot", CubeListBuilder.create()
                        .texOffs(204, 47).addBox(-4.0F, -1.0F, -9.0F, 8.0F, 4.0F, 12.0F)   // right_foot
                        .texOffs(56, 105).addBox(-4.0F, 0.0F, -11.0F, 2.0F, 3.0F, 4.0F)   // right_toe_0
                        .texOffs(164, 94).addBox(-3.0F, -1.0F, -16.0F, 0.0F, 4.0F, 6.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // right_toeclaw_0
                        .texOffs(104, 105).addBox(-4.5F, 1.5F, -16.0F, 3.0F, 0.0F, 6.0F, java.util.Set.of(net.minecraft.core.Direction.UP))   // right_toetop_0
                        .texOffs(56, 105).addBox(-1.0F, 0.0F, -11.0F, 2.0F, 3.0F, 4.0F)   // right_toe_1
                        .texOffs(164, 94).addBox(0.0F, -1.0F, -16.0F, 0.0F, 4.0F, 6.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // right_toeclaw_1
                        .texOffs(104, 105).addBox(-1.5F, 1.5F, -16.0F, 3.0F, 0.0F, 6.0F, java.util.Set.of(net.minecraft.core.Direction.UP))   // right_toetop_1
                        .texOffs(56, 105).addBox(2.0F, 0.0F, -11.0F, 2.0F, 3.0F, 4.0F)   // right_toe_2
                        .texOffs(164, 94).addBox(3.0F, -1.0F, -16.0F, 0.0F, 4.0F, 6.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // right_toeclaw_2
                        .texOffs(104, 105).addBox(1.5F, 1.5F, -16.0F, 3.0F, 0.0F, 6.0F, java.util.Set.of(net.minecraft.core.Direction.UP))   // right_toetop_2
                , PartPose.offset(0.0F, 9.0F, 3.0F));
        return LayerDefinition.create(mesh, 256, 256);
    }

    @Override
    public void setupAnim(DigimonRenderState state) {
        super.setupAnim(state);
        // Capture the fixed crown seat before applying the walk.
        org.joml.Vector3f seatTarget = null;
        if (state.isBeingRidden) {
            var restSeat = new com.mojang.blaze3d.vertex.PoseStack();
            this.body.translateAndRotate(restSeat);
            this.neck.translateAndRotate(restSeat);
            this.head.translateAndRotate(restSeat);
            seatTarget = restSeat.last().pose().transformPosition(
                    this.riderSeat.x / 16.0F, this.riderSeat.y / 16.0F, this.riderSeat.z / 16.0F,
                    new org.joml.Vector3f());
        }
        this.animations.get("walk").applyWalk(state.walkAnimationPos, state.walkAnimationSpeed, 4.1666667F, 4.1666667F);
        if (!state.isBeingRidden) {
            this.head.yRot += Mth.clamp(state.yRot, -25.0F, 25.0F) * Mth.DEG_TO_RAD;
            this.head.xRot += Mth.clamp(state.xRot, -15.0F, 15.0F) * Mth.DEG_TO_RAD;
        }
        this.jaw.xRot += Mth.sin(state.ageInTicks * 0.07F) * 0.012F;
        if (seatTarget != null) {
            // Keep the crown beneath the server-authoritative rider seat.
            // Only the head translation is corrected; the body/feet keep the walk.
            var animatedSeat = new com.mojang.blaze3d.vertex.PoseStack();
            this.body.translateAndRotate(animatedSeat);
            this.neck.translateAndRotate(animatedSeat);
            var parentInverse = new org.joml.Matrix4f(animatedSeat.last().pose()).invert();
            this.head.translateAndRotate(animatedSeat);
            var seatNow = animatedSeat.last().pose().transformPosition(
                    this.riderSeat.x / 16.0F, this.riderSeat.y / 16.0F, this.riderSeat.z / 16.0F,
                    new org.joml.Vector3f());
            var correction = parentInverse.transformDirection(seatTarget.sub(seatNow));
            this.head.x += correction.x * 16.0F;
            this.head.y += correction.y * 16.0F;
            this.head.z += correction.z * 16.0F;
        }
    }

    private static float rad(float degrees) {
        return degrees * Mth.DEG_TO_RAD;
    }
}
