package com.digicube.fabric.client.model;

import com.digicube.Constants;
import com.digicube.fabric.client.render.DigimonRenderState;
import net.minecraft.client.animation.KeyframeAnimation;

import java.util.HashMap;
import java.util.Map;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * KoromonModel -- GENERATED by the DigiCube model harness from digimon/koromon.py.
 * Geometry matches the Blender rig bone for bone; edit the spec and regenerate rather
 * than hand-tuning coordinates here. setupAnim is a starting point and may be edited.
 *
 * Vanilla model space: Y down, ground at y=24, front at -Z. Atlas 128x64.
 */
public class KoromonModel extends EntityModel<DigimonRenderState> {

    /** Client model layer used when baking this species. */
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Constants.id("koromon"), "main");

    private final ModelPart body;
    private final ModelPart leftEar;
    private final ModelPart leftEarTip;
    private final ModelPart rightEar;
    private final ModelPart rightEarTip;
    private final ModelPart normalFace;
    private final ModelPart teeth;
    private final ModelPart effort;

    /** Baked once per model instance; keyed by harness animation name. */
    private final Map<String, KeyframeAnimation> animations = new HashMap<>();

    /**
     * Creates the model and binds its animation bones.
     * @param root baked root from this model's layer
     */
    public KoromonModel(ModelPart root) {
        super(root);
        this.body = root.getChild("body");
        this.leftEar = root.getChild("body").getChild("left_ear");
        this.leftEarTip = root.getChild("body").getChild("left_ear").getChild("left_ear_tip");
        this.rightEar = root.getChild("body").getChild("right_ear");
        this.rightEarTip = root.getChild("body").getChild("right_ear").getChild("right_ear_tip");
        this.normalFace = root.getChild("body").getChild("normal_face");
        this.teeth = root.getChild("body").getChild("teeth");
        this.effort = root.getChild("body").getChild("effort");
        KoromonAnimations.BY_NAME.forEach((name, definition) -> this.animations.put(name, definition.bake(root)));
    }

    /**
     * Builds the authored geometry and texture layout.
     * @return the layer to register with the client
     */
    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                        .texOffs(0, 23).addBox(-8.0F, -1.0F, -6.0F, 16.0F, 1.0F, 11.0F)   // base
                        .texOffs(0, 0).addBox(-9.0F, -11.0F, -7.0F, 18.0F, 10.0F, 13.0F)   // face
                        .texOffs(62, 0).addBox(9.0F, -7.0F, -6.0F, 1.0F, 4.0F, 11.0F)   // left_cheek
                        .addBox(-10.0F, -7.0F, -6.0F, 1.0F, 4.0F, 11.0F)   // right_cheek
                        .texOffs(54, 23).addBox(-8.0F, -12.0F, -6.0F, 16.0F, 1.0F, 11.0F)   // brow
                        .texOffs(0, 35).addBox(-7.0F, -14.0F, -5.0F, 14.0F, 2.0F, 10.0F)   // crown
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition leftEar = body.addOrReplaceChild("left_ear", CubeListBuilder.create()
                        .texOffs(120, 35).addBox(-1.0F, -7.0F, -0.5F, 2.0F, 7.0F, 1.0F)   // left_ear
                , PartPose.offsetAndRotation(4.0F, -13.0F, 0.0F, rad(0.0F), rad(0.0F), rad(24.0F)));

        leftEar.addOrReplaceChild("left_ear_tip", CubeListBuilder.create()
                        .texOffs(0, 47).addBox(-1.0F, -2.0F, -0.55F, 8.0F, 5.0F, 0.0F)   // left_ear_tip
                , PartPose.offsetAndRotation(0.0F, -6.0F, 0.0F, rad(-10.0F), rad(-8.0F), rad(0.0F)));

        PartDefinition rightEar = body.addOrReplaceChild("right_ear", CubeListBuilder.create()
                        .texOffs(120, 35).addBox(-1.0F, -7.0F, -0.5F, 2.0F, 7.0F, 1.0F)   // right_ear
                , PartPose.offsetAndRotation(-4.0F, -13.0F, 0.0F, rad(0.0F), rad(0.0F), rad(-24.0F)));

        rightEar.addOrReplaceChild("right_ear_tip", CubeListBuilder.create()
                        .texOffs(16, 47).addBox(-7.0F, -2.0F, -0.55F, 8.0F, 5.0F, 0.0F)   // right_ear_tip
                , PartPose.offsetAndRotation(0.0F, -6.0F, 0.0F, rad(-10.0F), rad(8.0F), rad(0.0F)));

        body.addOrReplaceChild("normal_face", CubeListBuilder.create()
                        .texOffs(48, 35).addBox(-9.0F, -10.0F, 0.0F, 18.0F, 10.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // normal_face
                , PartPose.offset(0.0F, -1.0F, -7.125F));

        body.addOrReplaceChild("teeth", CubeListBuilder.create()
                        .texOffs(32, 47).addBox(-8.0F, -5.0F, -7.25F, 16.0F, 3.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // teeth
                , PartPose.offset(0.0F, 0.0F, 0.0F));

        body.addOrReplaceChild("effort", CubeListBuilder.create()
                        .texOffs(84, 35).addBox(-9.0F, -10.0F, 0.0F, 18.0F, 10.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // effort
                , PartPose.offset(0.0F, -1.0F, -7.125F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    @Override
    public void setupAnim(DigimonRenderState state) {
        super.setupAnim(state);
        float attackTick = state.attackAnimation.getTimeInMillis(state.ageInTicks) / 50.0F;
        boolean blowing = state.attackAnimation.isStarted() && "bubble_blow".equals(state.attackAnimationName)
                && attackTick >= 5.0F && attackTick < 19.0F;
        this.normalFace.visible = !blowing;
        this.teeth.visible = !blowing;
        this.effort.visible = blowing;
        if (state.attackAnimation.isStarted()) {
            KeyframeAnimation attack = this.animations.get(state.attackAnimationName);
            if (attack != null) attack.apply(state.attackAnimation, state.ageInTicks);
        } else {
            this.animations.get("walk").applyWalk(state.walkAnimationPos, state.walkAnimationSpeed, 1.4F, 2.0F);
        }
        float idle = Mth.sin(state.ageInTicks * 0.09F) * 0.018F;
        this.leftEar.zRot += idle;
        this.rightEar.zRot -= idle;
    }

    private static float rad(float degrees) {
        return degrees * Mth.DEG_TO_RAD;
    }
}
