package com.digicube.fabric.client.model;

import com.digicube.Constants;
import com.digicube.fabric.client.render.MarchingFishesRenderState;
import net.minecraft.client.animation.KeyframeAnimation;

import java.util.HashMap;
import java.util.Map;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * MarchingFishesModel -- GENERATED by the DigiCube model harness from digimon/marching_fishes.py.
 * Geometry matches the Blender rig bone for bone; edit the spec and regenerate rather
 * than hand-tuning coordinates here. setupAnim is a starting point and may be edited.
 *
 * Vanilla model space: Y down, ground at y=24, front at -Z. Atlas 512x256.
 */
public class MarchingFishesModel extends EntityModel<MarchingFishesRenderState> {

    private static final net.minecraft.resources.Identifier GEOMETRY = Constants.id("models/entity/marching_fishes.mesh.json");

    /** Client model layer used when baking this species. */
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Constants.id("marching_fishes"), "main");

    private final ModelPart school;
    private final ModelPart water;
    private final ModelPart spray;
    private final ModelPart fishRed;
    private final ModelPart fishRedTail;
    private final ModelPart fishRedFinR;
    private final ModelPart fishRedFinL;
    private final ModelPart fishYellow;
    private final ModelPart fishYellowTail;
    private final ModelPart fishYellowFinR;
    private final ModelPart fishYellowFinL;
    private final ModelPart fishPink;
    private final ModelPart fishPinkTail;
    private final ModelPart fishPinkFinR;
    private final ModelPart fishPinkFinL;
    private final ModelPart fishBlue;
    private final ModelPart fishBlueTail;
    private final ModelPart fishBlueFinR;
    private final ModelPart fishBlueFinL;
    private final ModelPart fishGreen;
    private final ModelPart fishGreenTail;
    private final ModelPart fishGreenFinR;
    private final ModelPart fishGreenFinL;
    private final ModelPart crest0;
    private final ModelPart crest1;
    private final ModelPart crest2;
    private final ModelPart foam;
    private final ModelPart drop0;
    private final ModelPart drop1;
    private final ModelPart drop2;
    private final ModelPart drop3;
    private final ModelPart drop4;
    private final ModelPart drop5;
    private final ModelPart drop6;
    private final ModelPart drop7;
    private final ModelPart drop8;
    private final ModelPart drop9;
    private final ModelPart drop10;
    private final ModelPart drop11;

    /** Baked once per model instance; keyed by harness animation name. */
    private final Map<String, KeyframeAnimation> animations = new HashMap<>();

    /**
     * Creates the model and binds its animation bones.
     * @param root baked root from this model's layer
     */
    public MarchingFishesModel(ModelPart root) {
        super(NativeModelGeometry.apply(root, GEOMETRY));
        this.school = root.getChild("school");
        this.water = root.getChild("water");
        this.spray = root.getChild("spray");
        this.fishRed = root.getChild("school").getChild("fish_red");
        this.fishRedTail = root.getChild("school").getChild("fish_red").getChild("fish_red_tail");
        this.fishRedFinR = root.getChild("school").getChild("fish_red").getChild("fish_red_fin_r");
        this.fishRedFinL = root.getChild("school").getChild("fish_red").getChild("fish_red_fin_l");
        this.fishYellow = root.getChild("school").getChild("fish_yellow");
        this.fishYellowTail = root.getChild("school").getChild("fish_yellow").getChild("fish_yellow_tail");
        this.fishYellowFinR = root.getChild("school").getChild("fish_yellow").getChild("fish_yellow_fin_r");
        this.fishYellowFinL = root.getChild("school").getChild("fish_yellow").getChild("fish_yellow_fin_l");
        this.fishPink = root.getChild("school").getChild("fish_pink");
        this.fishPinkTail = root.getChild("school").getChild("fish_pink").getChild("fish_pink_tail");
        this.fishPinkFinR = root.getChild("school").getChild("fish_pink").getChild("fish_pink_fin_r");
        this.fishPinkFinL = root.getChild("school").getChild("fish_pink").getChild("fish_pink_fin_l");
        this.fishBlue = root.getChild("school").getChild("fish_blue");
        this.fishBlueTail = root.getChild("school").getChild("fish_blue").getChild("fish_blue_tail");
        this.fishBlueFinR = root.getChild("school").getChild("fish_blue").getChild("fish_blue_fin_r");
        this.fishBlueFinL = root.getChild("school").getChild("fish_blue").getChild("fish_blue_fin_l");
        this.fishGreen = root.getChild("school").getChild("fish_green");
        this.fishGreenTail = root.getChild("school").getChild("fish_green").getChild("fish_green_tail");
        this.fishGreenFinR = root.getChild("school").getChild("fish_green").getChild("fish_green_fin_r");
        this.fishGreenFinL = root.getChild("school").getChild("fish_green").getChild("fish_green_fin_l");
        this.crest0 = root.getChild("water").getChild("crest_0");
        this.crest1 = root.getChild("water").getChild("crest_1");
        this.crest2 = root.getChild("water").getChild("crest_2");
        this.foam = root.getChild("water").getChild("foam");
        this.drop0 = root.getChild("spray").getChild("drop_0");
        this.drop1 = root.getChild("spray").getChild("drop_1");
        this.drop2 = root.getChild("spray").getChild("drop_2");
        this.drop3 = root.getChild("spray").getChild("drop_3");
        this.drop4 = root.getChild("spray").getChild("drop_4");
        this.drop5 = root.getChild("spray").getChild("drop_5");
        this.drop6 = root.getChild("spray").getChild("drop_6");
        this.drop7 = root.getChild("spray").getChild("drop_7");
        this.drop8 = root.getChild("spray").getChild("drop_8");
        this.drop9 = root.getChild("spray").getChild("drop_9");
        this.drop10 = root.getChild("spray").getChild("drop_10");
        this.drop11 = root.getChild("spray").getChild("drop_11");
        MarchingFishesAnimations.BY_NAME.forEach((name, definition) -> this.animations.put(name, definition.bake(root)));
    }

    /**
     * Builds the authored geometry and texture layout.
     * @return the layer to register with the client
     */
    public static LayerDefinition createBodyLayer() {
        return NativeModelGeometry.createLayer(GEOMETRY);
    }

    @Override
    public void setupAnim(MarchingFishesRenderState state) {
        super.setupAnim(state);
        this.animations.get(state.splash ? "splash" : "flight").apply((long) ((state.splash ? state.splashTicks : state.ageInTicks) * 50), 1.0F);
    }

    private static float rad(float degrees) {
        return degrees * Mth.DEG_TO_RAD;
    }
}
