package com.digicube.fabric.client.model;

import com.digicube.Constants;
import com.digicube.fabric.client.render.MegaFlameRenderState;
import net.minecraft.client.animation.KeyframeAnimation;

import java.util.HashMap;
import java.util.Map;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * MegaFlameModel -- GENERATED by the DigiCube model harness from digimon/mega_flame.py.
 * Geometry matches the Blender rig bone for bone; edit the spec and regenerate rather
 * than hand-tuning coordinates here. setupAnim is a starting point and may be edited.
 *
 * Vanilla model space: Y down, ground at y=24, front at -Z. Atlas 256x256.
 */
public class MegaFlameModel extends EntityModel<MegaFlameRenderState> {

    /** Client model layer used when baking this species. */
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Constants.id("mega_flame"), "main");

    private final ModelPart core;
    private final ModelPart coreMid;
    private final ModelPart coreHot;
    private final ModelPart lick0;
    private final ModelPart lick1;
    private final ModelPart lick2;
    private final ModelPart lick3;
    private final ModelPart ember0;
    private final ModelPart ember1;
    private final ModelPart ember2;
    private final ModelPart ember3;
    private final ModelPart ember4;
    private final ModelPart ember5;
    private final ModelPart ember6;
    private final ModelPart ember7;

    /** Baked once per model instance; keyed by harness animation name. */
    private final Map<String, KeyframeAnimation> animations = new HashMap<>();

    /**
     * Creates the model and binds its animation bones.
     * @param root baked root from this model's layer
     */
    public MegaFlameModel(ModelPart root) {
        super(root);
        this.core = root.getChild("core");
        this.coreMid = root.getChild("core_mid");
        this.coreHot = root.getChild("core_hot");
        this.lick0 = root.getChild("lick0");
        this.lick1 = root.getChild("lick1");
        this.lick2 = root.getChild("lick2");
        this.lick3 = root.getChild("lick3");
        this.ember0 = root.getChild("ember0");
        this.ember1 = root.getChild("ember1");
        this.ember2 = root.getChild("ember2");
        this.ember3 = root.getChild("ember3");
        this.ember4 = root.getChild("ember4");
        this.ember5 = root.getChild("ember5");
        this.ember6 = root.getChild("ember6");
        this.ember7 = root.getChild("ember7");
        MegaFlameAnimations.BY_NAME.forEach((name, definition) -> this.animations.put(name, definition.bake(root)));
    }

    /**
     * Builds the authored geometry and texture layout.
     * @return the layer to register with the client
     */
    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

        root.addOrReplaceChild("core", CubeListBuilder.create()
                        .texOffs(204, 0).addBox(-5.0F, -5.0F, -6.0F, 10.0F, 10.0F, 11.0F)   // core
                        .texOffs(38, 52).addBox(-7.0F, -3.0F, -3.0F, 14.0F, 6.0F, 7.0F)   // core_wide
                        .texOffs(176, 0).addBox(-3.0F, -7.0F, -4.0F, 6.0F, 14.0F, 8.0F)   // core_tall
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        root.addOrReplaceChild("core_mid", CubeListBuilder.create()
                        .texOffs(0, 52).addBox(-4.0F, -4.0F, -9.0F, 8.0F, 8.0F, 11.0F)   // core_mid
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        root.addOrReplaceChild("core_hot", CubeListBuilder.create()
                        .texOffs(80, 52).addBox(-2.0F, -2.0F, -11.0F, 4.0F, 4.0F, 6.0F)   // core_hot
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        root.addOrReplaceChild("lick0", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(0.0F, -8.0F, 0.0F, 0.0F, 16.0F, 36.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // lick0
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        root.addOrReplaceChild("lick1", CubeListBuilder.create()
                        .texOffs(72, 0).addBox(-8.0F, 0.0F, 0.0F, 16.0F, 0.0F, 36.0F, java.util.Set.of(net.minecraft.core.Direction.UP))   // lick1
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        root.addOrReplaceChild("lick2", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(0.0F, -8.0F, 0.0F, 0.0F, 16.0F, 36.0F, java.util.Set.of(net.minecraft.core.Direction.EAST))   // lick2
                , PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, rad(0.0F), rad(0.0F), rad(22.0F)));

        root.addOrReplaceChild("lick3", CubeListBuilder.create()
                        .texOffs(72, 0).addBox(-8.0F, 0.0F, 0.0F, 16.0F, 0.0F, 36.0F, java.util.Set.of(net.minecraft.core.Direction.UP))   // lick3
                , PartPose.offsetAndRotation(0.0F, 24.0F, 0.0F, rad(0.0F), rad(0.0F), rad(-22.0F)));

        root.addOrReplaceChild("ember0", CubeListBuilder.create()
                        .texOffs(100, 52).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 3.0F)   // ember0
                , PartPose.offset(8.0F, 24.0F, 10.0F));

        root.addOrReplaceChild("ember1", CubeListBuilder.create()
                        .texOffs(100, 52).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 3.0F)   // ember1
                , PartPose.offset(5.65685F, 18.3431F, 12.0F));

        root.addOrReplaceChild("ember2", CubeListBuilder.create()
                        .texOffs(100, 52).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 3.0F)   // ember2
                , PartPose.offset(0.0F, 16.0F, 14.0F));

        root.addOrReplaceChild("ember3", CubeListBuilder.create()
                        .texOffs(100, 52).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 3.0F)   // ember3
                , PartPose.offset(-5.65685F, 18.3431F, 16.0F));

        root.addOrReplaceChild("ember4", CubeListBuilder.create()
                        .texOffs(100, 52).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 3.0F)   // ember4
                , PartPose.offset(-8.0F, 24.0F, 18.0F));

        root.addOrReplaceChild("ember5", CubeListBuilder.create()
                        .texOffs(100, 52).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 3.0F)   // ember5
                , PartPose.offset(-5.65685F, 29.6569F, 20.0F));

        root.addOrReplaceChild("ember6", CubeListBuilder.create()
                        .texOffs(100, 52).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 3.0F)   // ember6
                , PartPose.offset(0.0F, 32.0F, 22.0F));

        root.addOrReplaceChild("ember7", CubeListBuilder.create()
                        .texOffs(100, 52).addBox(-1.0F, -1.0F, -1.0F, 2.0F, 2.0F, 3.0F)   // ember7
                , PartPose.offset(5.65685F, 29.6569F, 24.0F));
        return LayerDefinition.create(mesh, 256, 256);
    }

    @Override
    public void setupAnim(MegaFlameRenderState state) {
        super.setupAnim(state);
        this.animations.get(state.charging ? "charge" : state.burst ? "burst" : "flight").apply(
                (long) ((state.burst ? state.burstTicks : state.ageInTicks) * 50.0F), 1.0F);
        float trail = state.charging || state.burst ? 1.0F : Mth.clamp(state.ageInTicks * 0.55F / 3.04F, 0.02F, 1.0F);
        this.lick0.zScale *= trail;
        this.lick1.zScale *= trail;
        this.lick2.zScale *= trail;
        this.lick3.zScale *= trail;
        this.ember0.visible = state.charging || state.burst || state.ageInTicks >= 1.5341F;
        this.ember1.visible = state.charging || state.burst || state.ageInTicks >= 1.8409F;
        this.ember2.visible = state.charging || state.burst || state.ageInTicks >= 2.1477F;
        this.ember3.visible = state.charging || state.burst || state.ageInTicks >= 2.4545F;
        this.ember4.visible = state.charging || state.burst || state.ageInTicks >= 2.7614F;
        this.ember5.visible = state.charging || state.burst || state.ageInTicks >= 3.0682F;
        this.ember6.visible = state.charging || state.burst || state.ageInTicks >= 3.3750F;
        this.ember7.visible = state.charging || state.burst || state.ageInTicks >= 3.6818F;
    }

    private static float rad(float degrees) {
        return degrees * Mth.DEG_TO_RAD;
    }
}
