package com.digicube.fabric.client.model;

import com.digicube.Constants;
import com.digicube.fabric.client.render.PepperBreathRenderState;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * PepperBreathModel -- GENERATED by the DigiCube model harness from digimon/pepper_breath.py.
 * Geometry matches the Blender rig bone for bone; edit the spec and regenerate rather
 * than hand-tuning coordinates here. setupAnim is a starting point and may be edited.
 *
 * Vanilla model space: Y down, ground at y=24, front at -Z. Atlas 128x32.
 */
public class PepperBreathModel extends EntityModel<PepperBreathRenderState> {

    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Constants.id("pepper_breath"), "main");

    private final ModelPart frame0;
    private final ModelPart flame0A;
    private final ModelPart flame0B;
    private final ModelPart frame1;
    private final ModelPart flame1A;
    private final ModelPart flame1B;
    private final ModelPart frame2;
    private final ModelPart flame2A;
    private final ModelPart flame2B;

    public PepperBreathModel(ModelPart root) {
        super(root);
        this.frame0 = root.getChild("frame0");
        this.flame0A = root.getChild("frame0").getChild("flame0_a");
        this.flame0B = root.getChild("frame0").getChild("flame0_b");
        this.frame1 = root.getChild("frame1");
        this.flame1A = root.getChild("frame1").getChild("flame1_a");
        this.flame1B = root.getChild("frame1").getChild("flame1_b");
        this.frame2 = root.getChild("frame2");
        this.flame2A = root.getChild("frame2").getChild("flame2_a");
        this.flame2B = root.getChild("frame2").getChild("flame2_b");
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

        PartDefinition frame0 = root.addOrReplaceChild("frame0", CubeListBuilder.create()
                        .texOffs(84, 0).addBox(-4.0F, -4.0F, -4.0F, 8.0F, 8.0F, 0.0F)   // core0
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        frame0.addOrReplaceChild("flame0_a", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(0.0F, -4.0F, -14.0F, 0.0F, 8.0F, 14.0F)   // flame0_a
                , PartPose.offsetAndRotation(0.0F, 0.0F, 7.0F, rad(0.0F), rad(0.0F), rad(45.0F)));

        frame0.addOrReplaceChild("flame0_b", CubeListBuilder.create()
                        .texOffs(0, 0).addBox(0.0F, -4.0F, -14.0F, 0.0F, 8.0F, 14.0F)   // flame0_b
                , PartPose.offsetAndRotation(0.0F, 0.0F, 7.0F, rad(0.0F), rad(0.0F), rad(-45.0F)));

        PartDefinition frame1 = root.addOrReplaceChild("frame1", CubeListBuilder.create()
                        .texOffs(100, 0).addBox(-4.0F, -4.0F, -4.0F, 8.0F, 8.0F, 0.0F)   // core1
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        frame1.addOrReplaceChild("flame1_a", CubeListBuilder.create()
                        .texOffs(28, 0).addBox(0.0F, -4.0F, -14.0F, 0.0F, 8.0F, 14.0F)   // flame1_a
                , PartPose.offsetAndRotation(0.0F, 0.0F, 7.0F, rad(0.0F), rad(0.0F), rad(45.0F)));

        frame1.addOrReplaceChild("flame1_b", CubeListBuilder.create()
                        .texOffs(28, 0).addBox(0.0F, -4.0F, -14.0F, 0.0F, 8.0F, 14.0F)   // flame1_b
                , PartPose.offsetAndRotation(0.0F, 0.0F, 7.0F, rad(0.0F), rad(0.0F), rad(-45.0F)));

        PartDefinition frame2 = root.addOrReplaceChild("frame2", CubeListBuilder.create()
                        .texOffs(0, 22).addBox(-4.0F, -4.0F, -4.0F, 8.0F, 8.0F, 0.0F)   // core2
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        frame2.addOrReplaceChild("flame2_a", CubeListBuilder.create()
                        .texOffs(56, 0).addBox(0.0F, -4.0F, -14.0F, 0.0F, 8.0F, 14.0F)   // flame2_a
                , PartPose.offsetAndRotation(0.0F, 0.0F, 7.0F, rad(0.0F), rad(0.0F), rad(45.0F)));

        frame2.addOrReplaceChild("flame2_b", CubeListBuilder.create()
                        .texOffs(56, 0).addBox(0.0F, -4.0F, -14.0F, 0.0F, 8.0F, 14.0F)   // flame2_b
                , PartPose.offsetAndRotation(0.0F, 0.0F, 7.0F, rad(0.0F), rad(0.0F), rad(-45.0F)));
        return LayerDefinition.create(mesh, 128, 32);
    }

    @Override
    public void setupAnim(PepperBreathRenderState state) {
        super.setupAnim(state);

        // Frame flip every 2 ticks: exactly one frame bone visible, like an animated sprite.
        int frame = ((int) (state.ageInTicks / 2.0F)) % 3;
        this.frame0.visible = frame == 0;
        this.frame1.visible = frame == 1;
        this.frame2.visible = frame == 2;

        // Slow roll about the travel axis (-Z) keeps the crossed planes from ever reading as flat.
        float roll = state.ageInTicks * 12.0F * Mth.DEG_TO_RAD;
        this.frame0.zRot = this.frame1.zRot = this.frame2.zRot = roll;
    }

    private static float rad(float degrees) {
        return degrees * Mth.DEG_TO_RAD;
    }
}
