package com.digicube.fabric.client.model;

import com.digicube.Constants;
import com.digicube.fabric.client.render.DigimonRenderState;
import net.minecraft.client.animation.KeyframeAnimation;

import java.util.HashMap;
import java.util.Map;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.util.Mth;

/**
 * TsunomonModel -- GENERATED by the DigiCube model harness from digimon/tsunomon.py.
 * Geometry matches the Blender rig bone for bone; edit the spec and regenerate rather
 * than hand-tuning coordinates here. setupAnim is a starting point and may be edited.
 *
 * Vanilla model space: Y down, ground at y=24, front at -Z. Atlas 128x64.
 */
public class TsunomonModel extends EntityModel<DigimonRenderState> {

    /** Client model layer used when baking this species. */
    public static final ModelLayerLocation LAYER = new ModelLayerLocation(Constants.id("tsunomon"), "main");

    private final ModelPart body;
    private final ModelPart leftFur;
    private final ModelPart leftRearFur;
    private final ModelPart rightFur;
    private final ModelPart rightRearFur;
    private final ModelPart horn;
    private final ModelPart normalFace;
    private final ModelPart effort;

    /** Baked once per model instance; keyed by harness animation name. */
    private final Map<String, KeyframeAnimation> animations = new HashMap<>();

    /**
     * Creates the model and binds its animation bones.
     * @param root baked root from this model's layer
     */
    public TsunomonModel(ModelPart root) {
        super(root);
        this.body = root.getChild("body");
        this.leftFur = root.getChild("body").getChild("left_fur");
        this.leftRearFur = root.getChild("body").getChild("left_rear_fur");
        this.rightFur = root.getChild("body").getChild("right_fur");
        this.rightRearFur = root.getChild("body").getChild("right_rear_fur");
        this.horn = root.getChild("body").getChild("horn");
        this.normalFace = root.getChild("body").getChild("normal_face");
        this.effort = root.getChild("body").getChild("effort");
        TsunomonAnimations.BY_NAME.forEach((name, definition) -> this.animations.put(name, definition.bake(root)));
    }

    /**
     * Builds the authored geometry and texture layout.
     * @return the layer to register with the client
     */
    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();

        PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create()
                        .texOffs(36, 33).addBox(-7.0F, -1.0F, -5.0F, 14.0F, 1.0F, 9.0F)   // base
                        .texOffs(54, 20).addBox(-8.0F, -2.0F, -6.0F, 16.0F, 1.0F, 11.0F)   // chin
                        .texOffs(0, 0).addBox(-9.0F, -11.0F, -7.0F, 18.0F, 9.0F, 11.0F)   // face
                        .texOffs(0, 33).addBox(-8.0F, -11.0F, 4.0F, 16.0F, 9.0F, 2.0F)   // back
                        .texOffs(0, 20).addBox(-8.0F, -13.0F, -6.0F, 16.0F, 2.0F, 11.0F)   // brow
                        .texOffs(82, 33).addBox(-6.0F, -14.0F, -4.0F, 12.0F, 1.0F, 8.0F)   // crown
                        .texOffs(58, 0).addBox(9.0F, -7.0F, -6.0F, 1.0F, 4.0F, 10.0F)   // left_cheek
                        .addBox(-10.0F, -7.0F, -6.0F, 1.0F, 4.0F, 10.0F)   // right_cheek
                , PartPose.offset(0.0F, 24.0F, 0.0F));

        body.addOrReplaceChild("left_fur", CubeListBuilder.create()
                        .texOffs(120, 44).addBox(-1.0F, -3.0F, 0.0F, 4.0F, 6.0F, 0.0F)   // left_fur
                , PartPose.offsetAndRotation(8.0F, -8.0F, 1.0F, rad(0.0F), rad(20.0F), rad(0.0F)));

        body.addOrReplaceChild("left_rear_fur", CubeListBuilder.create()
                        .texOffs(14, 53).addBox(-1.0F, -3.0F, 0.0F, 4.0F, 5.0F, 0.0F)   // left_rear_fur
                , PartPose.offsetAndRotation(6.0F, -5.0F, 5.0F, rad(0.0F), rad(-30.0F), rad(0.0F)));

        body.addOrReplaceChild("right_fur", CubeListBuilder.create()
                        .texOffs(0, 53).addBox(-3.0F, -3.0F, 0.0F, 4.0F, 6.0F, 0.0F)   // right_fur
                , PartPose.offsetAndRotation(-8.0F, -8.0F, 1.0F, rad(0.0F), rad(-20.0F), rad(0.0F)));

        body.addOrReplaceChild("right_rear_fur", CubeListBuilder.create()
                        .texOffs(22, 53).addBox(-3.0F, -3.0F, 0.0F, 4.0F, 5.0F, 0.0F)   // right_rear_fur
                , PartPose.offsetAndRotation(-6.0F, -5.0F, 5.0F, rad(0.0F), rad(30.0F), rad(0.0F)));

        body.addOrReplaceChild("horn", CubeListBuilder.create()
                        .texOffs(0, 44).addBox(-2.0F, -4.0F, -2.0F, 4.0F, 4.0F, 5.0F)   // horn_0
                        .texOffs(90, 44).addBox(-2.0F, -7.0F, -2.0F, 4.0F, 3.0F, 4.0F)   // horn_1
                        .texOffs(106, 44).addBox(-1.5F, -10.0F, -3.0F, 3.0F, 3.0F, 4.0F)   // horn_2
                        .texOffs(30, 53).addBox(-1.0F, -12.0F, -4.0F, 2.0F, 2.0F, 3.0F)   // horn_3
                        .texOffs(40, 53).addBox(-0.5F, -14.0F, -5.0F, 1.0F, 2.0F, 2.0F)   // horn_4
                        .texOffs(8, 53).addBox(0.0F, -16.0F, -7.0F, 0.0F, 3.0F, 3.0F)   // horn_point
                , PartPose.offset(0.0F, -13.0F, 0.0F));

        body.addOrReplaceChild("normal_face", CubeListBuilder.create()
                        .texOffs(18, 44).addBox(-9.0F, -10.0F, 0.0F, 18.0F, 9.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // normal_face
                        .texOffs(46, 53).addBox(-8.0F, -1.0F, 1.0F, 16.0F, 1.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // normal_face_chin
                , PartPose.offset(0.0F, -1.0F, -7.125F));

        body.addOrReplaceChild("effort", CubeListBuilder.create()
                        .texOffs(54, 44).addBox(-9.0F, -10.0F, 0.0F, 18.0F, 9.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // effort
                        .texOffs(78, 53).addBox(-8.0F, -1.0F, 1.0F, 16.0F, 1.0F, 0.0F, java.util.Set.of(net.minecraft.core.Direction.NORTH))   // effort_chin
                , PartPose.offset(0.0F, -1.0F, -7.125F));
        return LayerDefinition.create(mesh, 128, 64);
    }

    @Override
    public void setupAnim(DigimonRenderState state) {
        super.setupAnim(state);
        float attackTick = state.attackAnimation.getTimeInMillis(state.ageInTicks) / 50.0F;
        boolean blowing = state.attackAnimation.isStarted() && "bubble_blow".equals(state.attackAnimationName)
                && attackTick >= 5.0F && attackTick < 19.0F;
        this.normalFace.visible = !blowing;
        this.effort.visible = blowing;
        if (state.attackAnimation.isStarted()) {
            KeyframeAnimation attack = this.animations.get(state.attackAnimationName);
            if (attack != null) attack.apply(state.attackAnimation, state.ageInTicks);
        } else {
            this.animations.get("walk").applyWalk(state.walkAnimationPos, state.walkAnimationSpeed, 1.4F, 2.0F);
        }
    }

    private static float rad(float degrees) {
        return degrees * Mth.DEG_TO_RAD;
    }
}
